### ISSUE TITLE
how to use the equivalente to "require" to use somebody else asset Algorithm

### ISSUE THREAD

**Issue by jimoreira** [r-spatial/rgee#103]
hi, 
I'm trying to use somebody else algorithm, 
I look into the examples and find this option of manage, but I'm not sure if its meant for this. 

Trying it :
`ee_manage_copy("users/...")`
and i'm getting 
`Error in ee_verify_filename(path_asset, strict = strict) : 
  users/khanalnishant/Algorithms:WhittakerSmoothing is not a valid destination. Make sure a correct full path is provided (e.g. either users/user/nameofcollection or projects/myproject/myfolder/newcollection)`

using it from gee works fine.
thanks for your help!!

**Comment by csaybar** [comment]
Hi @jimoreira this is a great package!. Unfortunately is in JavaScript so you will no able to run it together with rgee. `ee_manage_copy` is useful to move somebody else public earth engine asset to your own account.

![image](https://user-images.githubusercontent.com/16768318/93816005-30d76c00-fc57-11ea-9636-ff3e53ef9e8e.png)

**Comment by jimoreira** [comment]
thanks @csaybar for your answer. I'm having the same issue with ee_manage_copy, using another algorithm, from a different source, the same happens. 
Reading the function specification it says (Table, Image, Folder, or ImageCollection).
i don't know what hapen

**Comment by csaybar** [comment]
No ee_manage_* is not for algorithms is only for EE assets. That are ImageCollection, Image, tables (FeatureCollections).
