### ISSUE TITLE
error in ee_Initailize() on OSX

### ISSUE THREAD

**Issue by scra88le** [r-spatial/rgee#104]
* rgee version: rgee_1.0.5
* R version: 3.6.0 (2019-04-26)
* Operating System: x86_64-apple-darwin15.6.0 (64-bit)

### Description

When I try:

> ee_Initialize()

I get

Error in ee_connect_to_py(ee_current_version, n = 5) : 
  reticulate refuse to connect with rgee

Dump of information below - thanks for your help...

#### At submit an issue, please attached the following information of your `rgee` session:

- [x] You have the Python API installed (from terminal):
```
(base) Anthonys-MBP-4:~ anthony$ earthengine -h
Traceback (most recent call last):
  File "/Users/anthony/anaconda3/bin/earthengine", line 6, in <module>
    from ee.cli.eecli import main
  File "/Users/anthony/anaconda3/lib/python3.6/site-packages/ee/__init__.py", line 17, in <module>
    from . import batch
  File "/Users/anthony/anaconda3/lib/python3.6/site-packages/ee/batch.py", line 15, in <module>
    from . import _cloud_api_utils
  File "/Users/anthony/anaconda3/lib/python3.6/site-packages/ee/_cloud_api_utils.py", line 22, in <module>
    from googleapiclient import discovery
  File "/Users/anthony/anaconda3/lib/python3.6/site-packages/googleapiclient/discovery.py", line 50, in <module>
    from google.auth.transport import mtls
ImportError: cannot import name 'mtls'
(base) Anthonys-MBP-4:~ anthony$ 
```

- [x] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
[1] TRUE
```
- [x] You can run a simple EE command from R: 

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

Error in ee_connect_to_py(ee_current_version, n = 5) : 
  reticulate refuse to connect with rgee


# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())
``` 

Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()

python:         /Users/anthony/anaconda3/bin/python
libpython:      /Users/anthony/anaconda3/lib/libpython3.6m.dylib
pythonhome:     /Users/anthony/anaconda3:/Users/anthony/anaconda3
version:        3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/anthony/anaconda3/lib/python3.6/site-packages/numpy
numpy_version:  1.15.1
ee:             /Users/anthony/anaconda3/lib/python3.6/site-packages/ee

python versions found: 
 /usr/bin/python3
 /usr/bin/python
 /Users/anthony/anaconda3/bin/python
 /Users/anthony/.virtualenvs/rgee/bin/python
 /Users/anthony/anaconda3/envs/gee-demo/bin/python
```

**Comment by csaybar** [comment]
Hi @scra88le it seems your system have problems to install the Earth Engine Python API in your anaconda ENV. You will have to do it manually, I highly encourage you use your other Python ENV (`/usr/bin/python3` or  `/Users/anthony/.virtualenvs/rgee/bin/python`) . Something like this works?

```r
library(reticulate)

# 1. Terminate your are R session
# 3. Set your miniconda Python Env
use_python("/usr/bin/python3")
# 4. Run ee_install()
ee_install()
```
Please upgrade your rgee to v.1.0.6 before to run the code above. Let me know if the problem persist

**Comment by scra88le** [comment]
Hi @csaybar , I got `rgee` working by following this [blog](https://philippgaertner.github.io/2019/12/earth-engine-rstudio-reticulate/). The main thing that made a difference was specifying the conda environment:

`use_condaenv("gee-demo", conda = "auto",required = TRUE)`

Then I ran `ee_install()` and everything seemed to work fine.

**Comment by csaybar** [comment]
Thank you for share your answer I going to close this issue but feel free to open again!
