### ISSUE TITLE
sf_as_ee with gcs_to_asset option failing

### ISSUE THREAD

**Issue by giacfalk** [r-spatial/rgee#105]
* rgee version: 0.6.2
* R version: 3.5.1
* Operating System: Windows 10 

I fail to use the sf_as_ee with gcs_to_asset option. 

I created a bucket on GCS, I created the auth JSON key and put it in the right folder, and successfully run ee_Initialize(email=xxx@gmail.com", gcs = TRUE).

I am using this command

a<- read_sf("NUTS_RG_10M_2021_4326_LEVL_0.shp")

```
upload <- sf_as_ee(
  a,
  via = "gcs_to_asset",
  bucket = "accessibility",
  assetId = "users/xxx/attempt",
  monitoring = TRUE,
  proj = "EPSG:4326")

```
and I get the following error

```
Uploading gs://accessibility/file7382eb72c0d.zip to users/xxx/attempt... please wait
State: CANCELLED
ERROR in Earth Engine servers: Cancelled.
Error in ee_monitoring() : 
  ee_monitoring was forced to stop before getting results

```

I must say I never used Google Cloud Storage before, but the bucket seem to be open and I manage to manually upload files within it from the console.

**Comment by giacfalk** [comment]
EDIT: for some reason now it is succeeding (in R):

```
Uploading gs://accessibility/file73867e247a2.zip to to users/xxx/attempt ... please wait
State: COMPLETED
```

but when I open GEE the asset is not there... weird.

**Comment by csaybar** [comment]
Hi @giacfalk everything seems good, could I obtain somehow access to your shapefile?

**Comment by giacfalk** [comment]
Thanks for your reply. Sure. But it seems to me that the issue is not related to the shapefile itself, as changing shapefile leads to the same error!

**Comment by csaybar** [comment]
Server-side errors without additional messages are quite difficult to predict what the real problem is. Can you confirm that the code bellow works?

```r
library(rgee)
library(sf)
ee_Initialize(gcs = TRUE)
bucket_name <- 'rgee_dev' #Put here your bucket name

toy_poly <- matrix(data = c(-35,-10,-35,10,35,10,35,-10,-35,-10),
                   ncol = 2,
                   byrow = TRUE) %>%
  list() %>%
  st_polygon()

assetId <- sprintf("%s/%s", ee_get_assethome(), 'toy_poly_gcs')

eex <- sf_as_ee(
 x = toy_poly,
 overwrite = TRUE,
 assetId = assetId,
 bucket = 'rgee_dev',
 monitoring = FALSE,
 via = 'gcs_to_asset'
)
ee_monitoring()

```

**Comment by giacfalk** [comment]
It seems to work because it yields the following (NB in the meantime I updated rgee to the latest version)

`1. Converting sf object to a compressed ZIP shapefile ... saving in /tmp
2. From local to GCS
3. Creating the manifest
4. From GCS to Earth Engine
Running the OS command: earthengine upload table --manifest C:/Users/GIACOMO/AppData/Local/Temp/RtmpyKDqM4/file4d6429c213a3_manifest.json
Running command using Cloud API.  Set --no-use_cloud_api to go back to using the API

Started upload task with ID: IHMU4LM4UQTUXDJFSRN3KTFG`

But then when I open GEE I found the upload failed with the following error

"Error: File not found: 'file4d6469a24d53.zip'."

I assume there is something wrong with my GCS?

**Comment by csaybar** [comment]
`ee_monitoring` finished with no problem?. If yes you could use the asset with no problems!.
The code bellow if what `sf_as_ee` does in the backend to detect your bucket, if no error appears your GCS connection works fine!
```r
googleCloudStorageR::gcs_get_bucket('rgee_dev') # Put here your bucket name
```

**Comment by giacfalk** [comment]
It's a mistery! `ee_monitoring `reports

```
Polling for task <id: OJZIRUZVX7JBXWMZ3BMGBRSE, time: 0s>.
State: FAILED
ERROR in Earth Engine servers: File not found: 'file4d6475d77bc7.zip'.

```
but `googleCloudStorageR::gcs_get_bucket('accessibility')` seems to be working as it yields

```
==Google Cloud Storage Bucket==
Bucket:          accessibility 
Project Number:  913265133738 
Location:        US 
Class:           STANDARD 
Created:         2020-09-24 10:50:20 
Updated:         2020-09-25 07:38:51 
Meta-generation: 3 
eTag:            CAM= 
```

**Comment by csaybar** [comment]
Ok it seems that there is a problem creating the zip file (`file4d6475d77bc7.zip`), could you confirm that the file does not exist in your GCS?:

```r
# via browser
"https://console.cloud.google.com/storage/browser/PUT_HERE_YOUR_BUCKET_NAME"`
# via R
googleCloudStorageR::gcs_global_bucket('PUT_HERE_YOUR_BUCKET_NAME')
googleCloudStorageR::gcs_get_object('file435d19895fe6.zip')
```
Is the zip file created properly?

```r
toy_poly <- matrix(data = c(-35,-10,-35,10,35,10,35,-10,-35,-10),
                   ncol = 2,
                   byrow = TRUE) %>%
  list() %>%
  st_polygon()
x <- sf::st_sfc(toy_poly, crs = 4326)
shp_dir <- sprintf("%s.shp", "demo_shp")
geozip_dir <- ee_utils_shp_to_zip(x, filename =  shp_dir)
```

![image](https://user-images.githubusercontent.com/16768318/94246385-4b247a80-fee1-11ea-9b14-6161b33985dd.png)

**Comment by giacfalk** [comment]
Thanks for your time! Oddly enough `geozip_dir <- ee_utils_shp_to_zip(x, filename =  shp_dir)` creates the shp shx dbf and prj files in the working directory but not within a zip folder! That's probably the issue! But I wonder why this behaviour. I'm on Windows 10.

**Comment by csaybar** [comment]
Thanks we are going to work on this in the next release!. For the moment you can use `gcs_to_ee_table`, see examples [here](https://r-spatial.github.io/rgee/reference/gcs_to_ee_table.html)

**Comment by giacfalk** [comment]
I found the solution: on Windows you need Rtools to use the utils::zip (on which the `ee_utils_shp_to_zip `function relies ). Also, you need the Rtools path to be in your PATH environment variables (https://stackoverflow.com/questions/12698583/r-function-ziputils-doesnt-work-on-my-machine).

**Comment by csaybar** [comment]
Thanks so much! we will add a condition when Windows users does not have Rtools4 installed :). This error still happens with the toy example that I shared with you?

```r
library(rgee)
library(sf)
ee_Initialize(gcs = TRUE)
bucket_name <- 'rgee_dev' #Put here your bucket name

toy_poly <- matrix(data = c(-35,-10,-35,10,35,10,35,-10,-35,-10),
                   ncol = 2,
                   byrow = TRUE) %>%
  list() %>%
  st_polygon()

assetId <- sprintf("%s/%s", ee_get_assethome(), 'toy_poly_gcs')

eex <- sf_as_ee(
 x = toy_poly,
 overwrite = TRUE,
 assetId = assetId,
 bucket = 'rgee_dev',
 monitoring = FALSE,
 via = 'gcs_to_asset'
)
ee_monitoring()
```

**Comment by giacfalk** [comment]
Yes, it yields the same error of 'File access denied' but I find the file in the bucket. So the problem now occurs in the transfer form GCS to GEE assets.

**Comment by csaybar** [comment]
Ok `sf_as_ee(..., gcs=TRUE)` only create the petition to the [Command Line Tool](https://developers.google.com/earth-engine/guides/command_line). Something like this:
![image](https://user-images.githubusercontent.com/16768318/94771011-ce2f5000-037b-11eb-8db2-f1253f7325a2.png)

If you enter to the .json file you will see something like this:
![image](https://user-images.githubusercontent.com/16768318/94771095-0c2c7400-037c-11eb-875b-73307da5cfc9.png)

Please be sure that `sf_as_ee` is creating correctly the *name* and *uri* of your file

**Comment by MichaelTD83** [comment]
I hope this is acceptable to add onto this thread.

I am having this same problem though slightly different from the original post.
When running my original code 
```
SW <- sf_as_ee(df_1985Test, via = "gcs_to_asset", assetId = "users/mtd25/fires", monitoring = TRUE, bucket = "sw_fires")
```
I get the following

```1. Converting sf object to a compressed ZIP shapefile ... saving in /tmp
2. From local to GCS
2021-01-03 10:50:34 -- File size detected as 50.1 Kb
i 2021-01-03 10:50:34 > Request Status Code:  400
2021-01-03 10:50:34 -- File size detected as 50.1 Kb
i 2021-01-03 10:50:34 > Request Status Code:  400
2021-01-03 10:50:34 -- File size detected as 50.1 Kb
i 2021-01-03 10:50:35 > Request Status Code:  400
2021-01-03 10:50:35 -- File size detected as 50.1 Kb
i 2021-01-03 10:50:35 > Request Status Code:  400
2021-01-03 10:50:35 -- File size detected as 50.1 Kb
i 2021-01-03 10:50:35 > Request Status Code:  400
3. Creating the manifest
4. From GCS to Earth Engine
Running the OS command: earthengine upload table --manifest C:/Users/mtd25/AppData/Local/Temp/RtmpyeHAbu/filec141284466_manifest.json
Started upload task with ID: 4WZAF6WAXMNMLHLRVFVDKBU2


Polling for task <id: 4WZAF6WAXMNMLHLRVFVDKBU2, time: 0s>.
State: FAILED
ERROR in Earth Engine servers: File not found: 'filec1433a26f31.zip'.
Error in ee_monitoring() : 
  ee_monitoring was forced to stop before getting results
```

When running your toy_poly code from September 25th (with "ee_Initialize("mtd***", drive = TRUE, gcs = TRUE")  I get the same message with the different zip file name from the new run.

The zip file is in my temp folder in the path shown above but does not show up in my GCS 

Here are the other diagnostics you asked for above
```googleCloudStorageR::gcs_get_bucket('sw_fires')
==Google Cloud Storage Bucket==
Bucket:          sw_fires 
Project Number:  197285126680 
Location:        US-WEST4 
Class:           STANDARD 
Created:         2021-01-03 17:23:20 
Updated:         2021-01-03 17:23:20 
Meta-generation: 1 
eTag:            CAE= 

#__________________________________________
googleCloudStorageR::gcs_global_bucket('sw_fires')
Set default bucket name to 'sw_fires'
googleCloudStorageR::gcs_get_object('filec141bb52b81.zip')
i 2021-01-03 11:06:24 > Request Status Code:  404
Error : lexical error: invalid char in json text.
                                       No such object: sw_fires/filec1
                     (right here) ------^

No such object: sw_fires/filec141bb52b81.zipError in googleCloudStorageR::gcs_get_object("filec141bb52b81.zip") : 
  File not found. Check object_name and if you have read permissions.
           Looked for filec141bb52b81.zip
#_______________________________________________
toy_poly <- matrix(data = c(-35,-10,-35,10,35,10,35,-10,-35,-10),
                   ncol = 2,
                   byrow = TRUE) %>%
  list() %>%
  st_polygon()
x <- sf::st_sfc(toy_poly, crs = 4326)
shp_dir <- sprintf("%s.shp", "demo_shp")
geozip_dir <- ee_utils_shp_to_zip(x, filename =  shp_dir)
```
the last one downloads the zip and .shp 

![Screenshot (4)](https://user-images.githubusercontent.com/76915529/103485747-d3a29900-4db5-11eb-8c4b-45293cbec460.png)

I do also have Rtools installed and ready I believe, as giacfalk suggested . At least I've followed all of the instructions at  https://cran.r-project.org/bin/windows/Rtools/ 


Any help would be appreciated

**Comment by csaybar** [comment]
Thanks a lot, for your comments!.

This is a bit embarrassing ... I omitted an important step here. Please follow the **[new tutorial](https://github.com/r-spatial/rgee/tree/help/gcs)** to upload data using gcs and rgee. I gonna close this issue but feel free to open the issue again.
