### ISSUE TITLE
Error: Error in reticulate::install_miniconda() : cannot install Miniconda into a path containing spaces

### ISSUE THREAD

**Issue by maritza-ph** [r-spatial/rgee#108]
* rgee version: 
* R version: 4.0.3.
* Operating System: 

#### At submit an issue, please attached the following information of your `rgee` session:

- [ ] You have the Python API installed (from terminal): NO
```
earthengine -h
```

- [ ] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
```
- [ ] You can run a simple EE command from R: 

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())
``` 

Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()
```

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

Error: Error in reticulate::install_miniconda() : 
  cannot install Miniconda into a path containing spaces

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by csaybar** [comment]
Deeply sorry for the last reply. 
Installing **rgee** is easier in the latest version of Rstudio.

- First, please install the Earth Engine API following the [official guide](https://developers.google.com/earth-engine/guides/python_install).
- Second,  please follow the instructions specified in #110 

Thanks for your interest in **rgee**!

**Comment by kevibarcena** [comment]
csaybar i need your help. when i run "rgee" give that line. pls 
Error: package or namespace load failed for ‘rgee’:
 .onLoad failed in loadNamespace() for 'rgee', details:
  call: py_module_import(module, convert = convert)
  error: ModuleNotFoundError: No module named 'ee'
