### ISSUE TITLE
Combine Filter$neq with Filter$calendarRange?

### ISSUE THREAD

**Issue by thiagoveloso** [r-spatial/rgee#109]
* rgee version: 1.0.6
* R version: 4.0.3
* Operating System: macOS 10.15

Thanks for this amazing package!

I am trying to filter an image collection by all months except a few. For example - in the GEE editor, I can select all months except `April To July` with something like this:

```
var not_wanted_filter = ee.Filter.calendarRange(4,7,'month')

var l7col = ee.ImageCollection("LANDSAT/LE07/C01/T1_SR")
            .filter(not_wanted_filter.not())
            .filter(ee.Filter.lt('CLOUD_COVER', 10))
```
(code inspired on https://gis.stackexchange.com/questions/268480/how-to-filter-image-collection-by-date-excluding-a-date-from-a-date-range-in-go)

Now, in `rgee` I am aware of both [`Filter$calendarRange`](https://github.com/r-spatial/rgee/blob/examples/ImageCollection/filtering_by_calendar_range.R) and [`Filter$neq`](https://github.com/r-spatial/rgee/blob/examples/Filter/filter_neq.R). But it doesn't look like `Filter$neq` takes another function as an argument (I might be wrong though, since I am still getting used to this package).

The question is: is it possible to combine both of them in order to achieve the same result as in GEE?

**Comment by csaybar** [comment]
Hi @thiagoveloso thanks for use **rgee**!

`rgee` mimics the **Python API** not Javascript! The syntax is quite similar both not exactly the same. Please take a look at this  [syntax comparison](https://developers.google.com/earth-engine/guides/python_install#syntax).

This code should works:

```r
library(rgee)
ee_Initialize()

not_wanted_filter <- ee$Filter$calendarRange(4, 7, "month")

l7col <- ee$ImageCollection("LANDSAT/LE07/C01/T1_SR") %>% #u can use pipes if u want!
  ee$ImageCollection$filter(not_wanted_filter$Not()) %>% 
  ee$ImageCollection$filter(ee$Filter$lt("CLOUD_COVER", 10))
```

**Comment by thiagoveloso** [comment]
Hey @csaybar thanks a lot for your quick reply! Yes, your proposed solution solved my issue - I appreciate it!
