### ISSUE TITLE
ee_Initialize() failed to connect to the Python ENV specified in ee_install

### ISSUE THREAD

**Issue by WattsMatthew** [r-spatial/rgee#110]
rgee version: latest
R version: 3.62
Operating System: ubuntu 18.04

- [x] You have the Python API installed (from terminal):
```
earthengine -h
```
Yes

- [x] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
```
Yes

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

```
**Description**
I'm getting the following message after running ee_initialize, all packages are up to date, was working fine yesterday. 

ee_Initialize
function (email = NULL, drive = FALSE, gcs = FALSE, display = FALSE, 
    quiet = FALSE) 
{
    init_rgee_message <- ee_search_init_message()
    if (!init_rgee_message) {
        ee_init_message()
    }
    earthengine_python <- Sys.getenv("EARTHENGINE_PYTHON", 
        unset = NA)
    if (!is.na(earthengine_python)) 
        Sys.setenv(RETICULATE_PYTHON = earthengine_python)
    ee_current_version <- system.file("python/ee_utils.py", 
        package = "rgee")
    ee_utils <- ee_connect_to_py(ee_current_version, n = 5)
    earthengine_version <- ee_utils_py_to_r(ee_utils$ee_getversion())
    if (!quiet) {
        cat(rule(left = bold("rgee", packageVersion("rgee")), 
            right = paste0("earthengine-api ", earthengine_version)), 
            "\n")
    }
    if (as.numeric(gsub("\\.", "", earthengine_version)) < 
        1215) {
        warning("Update your earthnengine-api installations to v0.1.232 or greater. ", 
            "Earlier versions are not compatible with recent ", 
            "changes to the Earth Engine backend.")
    }
    if (is.null(email)) {
        email <- "ndef"
    }
    if (!quiet) {
        if (email == "ndef") {
            cat("", green(symbol[["tick"]]), blue("email:"), 
                green("not_defined\n"))
        }
        else {
            cat("", green(symbol[["tick"]]), blue("email:"), 
                green(email), "\n")
        }
    }
    email_clean <- gsub("@gmail.com", "", email)
    ee_path <- ee_utils_py_to_r(ee_utils$ee_path())
    ee_path_user <- sprintf("%s/%s", ee_path, email_clean)
    dir.create(ee_path_user, showWarnings = FALSE, recursive = TRUE)
    unlink(list.files(ee_path, "@gmail.com", full.names = TRUE))
    unlink(list.files(ee_path, ".json", full.names = TRUE))
    drive_credentials <- NA
    gcs_credentials <- list(path = NA, message = NA)
    if (drive) {
        if (!requireNamespace("googledrive", quietly = TRUE)) {
            stop("The googledrive package is not installed. Try", 
                " install.packages(\"googledrive\")", call. = FALSE)
        }
        if (!quiet) {
            cat("", green(symbol$tick), blue("Google Drive credentials:"))
        }
        drive_credentials <- ee_create_credentials_drive(email)
        if (!quiet) {
            cat("\r", green(symbol$tick), blue("Google Drive credentials:"), 
                green(" FOUND\n"))
        }
    }
    if (gcs) {
        if (!requireNamespace("googleCloudStorageR", quietly = TRUE)) {
            stop("The googleCloudStorageR package is not installed. Try", 
                " install.packages(\"googleCloudStorageR\")", 
                call. = FALSE)
        }
        if (!quiet) {
            cat("", green(symbol[["tick"]]), blue("GCS credentials:"))
        }
        gcs_credentials <- tryCatch(expr = ee_create_credentials_gcs(email), 
            error = function(e) {
                list(path = NA, message = NA)
            })
        if (!quiet) {
            if (!is.na(gcs_credentials[["path"]])) {
                cat("\r", green(symbol[["tick"]]), 
                  blue("GCS credentials:"), green(" FOUND\n"))
            }
            else {
                cat("\r", green(symbol[["tick"]]), 
                  blue("GCS credentials:"), red("NOT FOUND\n"))
            }
        }
    }
    options(rgee.gcs.auth = gcs_credentials[["path"]])
    if (!quiet) {
        cat("", green(symbol[["tick"]]), blue("Initializing Google Earth Engine:"))
    }
    ee_create_credentials_earthengine(email_clean, display = display)
    ee$Initialize()
    if (!quiet) {
        cat("\r", green(symbol[["tick"]]), blue("Initializing Google Earth Engine:"), 
            green(" DONE!\n"))
    }
    ee_user_assetroot <- ee$data$getAssetRoots()
    assetroot_exist <- length(ee_user_assetroot) == 0
    if (assetroot_exist) {
        root_text <- paste("Earth Engine Assets home root folder does not exist for the current user.", 
            "Please enter your desired root folder name below. Take into consideration", 
            sprintf("that once created %s Alternatively,", 
                bold("you will not be able to change the folder name again. ")), 
            sprintf("press ESC to interrupt and run: %s", 
                bold("ee$data$createAssetHome(\"users/PUT_YOUR_NAME_HERE\")")), 
            sprintf("to attempt to create it. After that execute again %s.", 
                bold("ee_Initialize()")), sep = "\n")
        message(root_text)
        ee_createAssetHome()
        ee_user_assetroot <- ee$data$getAssetRoots()
    }
    ee_user_assetroot_id <- ee_user_assetroot[[1]]$id
    ee_user <- ee_remove_project_chr(ee_user_assetroot_id)
    options(rgee.ee_user = ee_user)
    ee_sessioninfo(email = email_clean, user = ee_user, drive_cre = drive_credentials, 
        gcs_cre = gcs_credentials[["path"]])
    if (!quiet) {
        cat("\r", green(symbol[["tick"]]), blue("Earth Engine user:"), 
            green(bold(ee_user)), "\n")
        cat(rule(), "\n")
        if (!is.na(gcs_credentials[["message"]])) {
            message(gcs_credentials[["message"]])
        }
    }
    invisible(TRUE)
}
<bytecode: 0x000001d5c196c270>
<environment: namespace:rgee>

```Library(reticulate)
py_config()```

python:         /home/matt/.local/share/r-miniconda/envs/r-reticulate/bin/python
libpython:      /home/matt/.local/share/r-miniconda/envs/r-reticulate/lib/libpython3.6m.so
pythonhome:     /home/matt/.local/share/r-miniconda/envs/r-reticulate:/home/matt/.local/share/r-miniconda/envs/r-reticulate
version:        3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:09:42)  [GCC 7.5.0]
numpy:          /home/matt/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.19.4

**Comment by WattsMatthew** [comment]
I got it working using following the steps here

https://philippgaertner.github.io/2019/12/earth-engine-rstudio-reticulate/

However, i'll leave the ticket open since the issued occurred without me changing any settings on R + python google earth api. So might be worth investigating.

**Comment by csaybar** [comment]
Hi @WattsMatthew,

Your problem seems to be that your current Python ENV (r-reticulate) does not have installed the earthengine-api.

If you are using the latest version of Rstudio (1.4) is easier to use rgee:

**1. Go to Tools -> Project Options -> Python**
![image](https://user-images.githubusercontent.com/16768318/98655490-d47ff700-233f-11eb-90b2-5742029ec859.png)

**2. Then just select the Python version that you want to use! (It's necessary that it have installed [earthengine-api](https://developers.google.com/earth-engine/guides/python_install)).**

![image](https://user-images.githubusercontent.com/16768318/98655766-23c62780-2340-11eb-9a24-0c7d32b1a908.png)

**Comment by WattsMatthew** [comment]
ok thanks that did the trick!
