### ISSUE TITLE
sf_as_ee  can not handle POSIXt objects

### ISSUE THREAD

**Issue by alherca73** [r-spatial/rgee#113]
* rgee version:1.0.6
* R version:4.0.3
* Operating System: MacOS Catalina 10.15.7

#### At submit an issue, please attached the following information of your `rgee` session:

- [ ] You have the Python API installed (from terminal):
```
earthengine -h
```

- [ ] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
> library(rgee)
> ee_path <- path.expand("~/.config/earthengine/credentials")
> file.exists(ee_path)
[1] TRUE

```
- [ ] You can run a simple EE command from R: 

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

> ee_Initialize()
── rgee 1.0.6 ───────────────────────────────────────────────────────────────── earthengine-api 0.1.243 ── 
 ✓ email: not_defined
 ✓ Initializing Google Earth Engine:  DONE!
 ✓ Earth Engine user: users/tallercarbonobid 

# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())

METADATA CAN BE PRINTED SUCCESSFULLY
``` 

Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()

> library(reticulate)
> py_config()
python:         /Users/alexhernandez/.virtualenvs/rgee/bin/python
libpython:      /Users/alexhernandez/miniconda3/envs/gee/lib/libpython3.9.dylib
pythonhome:     /Users/alexhernandez/.virtualenvs/rgee:/Users/alexhernandez/.virtualenvs/rgee
version:        3.9.0 (default, Nov 15 2020, 06:25:35)  [Clang 10.0.0 ]
numpy:          /Users/alexhernandez/.virtualenvs/rgee/lib/python3.9/site-packages/numpy
numpy_version:  1.19.4
ee:             /Users/alexhernandez/.virtualenvs/rgee/lib/python3.9/site-packages/ee

NOTE: Python version was forced by RETICULATE_PYTHON
```

### Description

Describe what you were trying to get done.

TRYING TO GET A SIMPLE Map$addLayer or exporting an image with ee_as_raster

Tell us what happened, what went wrong, and what you expected to happen.

I get the error:

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  EEException: Can't encode object: ['NaT']

Detailed traceback: 
  File "/Users/alexhernandez/.virtualenvs/rgee/lib/python3.9/site-packages/ee/data.py", line 557, in getMapId
    serializer.encode(params['image'], for_cloud_api=True),
  File "/Users/alexhernandez/.virtualenvs/rgee/lib/python3.9/site-packages/ee/serializer.py", line 288, in encode
    return serializer._encode(obj)  # pylint: disable=protected-access
  File "/Users/alexhernandez/.virtualenvs/rgee/lib/python3.9/site-packages/ee/serializer.py", line 74, in _encode
    return self._encode_for_cloud_api(obj)
  File "/Users/alexhernandez/.virtualenvs/rgee/lib/python3.9/site-packages/ee/serializer.py", line 92, in _encode_for_cloud_api
    value = self._encode_cloud_object(obj)
  File "/Users/alexhernandez/.virtualenvs/rgee/lib/python3.9/site-packages/ee/serializer.py", line 215, in _encode_cloud_object
    result = obj.encode_cloud_value(self._encode_cloud_object)
  File "/Users/alexhernandez/.virtualenvs/rgee/lib/p

### What I Did
aguan<-st_read("/Users/alexhernandez/Desktop/GEDI_Tests/Aguan_Valley.kml")
ee_x <- sf_as_ee(
  x = aguan)
Map$addLayer(ee_x)

```
Paste the command(s) you ran and the output.

Map$addLayer(ee_x)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  EEException: Can't encode object: ['NaT']

Detailed traceback: 
  File "/Users/alexhernandez/.virtualenvs/rgee/lib/python3.9/site-packages/ee/data.py", line 557, in getMapId
    serializer.encode(params['image'], for_cloud_api=True),
  File "/Users/alexhernandez/.virtualenvs/rgee/lib/python3.9/site-packages/ee/serializer.py", line 288, in encode
    return serializer._encode(obj)  # pylint: disable=protected-access
  File "/Users/alexhernandez/.virtualenvs/rgee/lib/python3.9/site-packages/ee/serializer.py", line 74, in _encode
    return self._encode_for_cloud_api(obj)
  File "/Users/alexhernandez/.virtualenvs/rgee/lib/python3.9/site-packages/ee/serializer.py", line 92, in _encode_for_cloud_api
    value = self._encode_cloud_object(obj)
  File "/Users/alexhernandez/.virtualenvs/rgee/lib/python3.9/site-packages/ee/serializer.py", line 215, in _encode_cloud_object
    result = obj.encode_cloud_value(self._encode_cloud_object)
  File "/Users/alexhernandez/.virtualenvs/rgee/lib/p
If there was a crash, please include the traceback here.
```

**Comment by csaybar** [comment]
Thanks @alherca73 for open this issue!
Could I have access for some way to the .kml file?

**Comment by alherca73** [comment]
Sure. Here's a zip.
[Aguan_Valley.kml.zip](https://github.com/r-spatial/rgee/files/5609284/Aguan_Valley.kml.zip)

**Comment by alherca73** [comment]
It seems like the original KML file had some attribute columns with issues. I eliminated those columns within R (prior to using rgee::sf_as_ee) and from then on was able to use it. So I guess the issue was not with rgee instalation but rather with my *.kml file.

Thanks for your quick reply!

**Comment by csaybar** [comment]
The problem is that `sf_as_ee` doesn't know what to do with POSIXt objects.  Change POSIXt columns to character type or delete those columns and the code will work!

```r
geo <- read_sf("Aguan_Valley.kml")T
geo %>% head %>% collect %>% lapply(class) %>% unlist()
#>          Name   description    timestamp1    timestamp2        begin1 
#>   "character"   "character"     "POSIXct"      "POSIXt"     "POSIXct" 
#>        begin2          end1          end2  altitudeMode    tessellate 
#>      "POSIXt"     "POSIXct"      "POSIXt"   "character"     "integer" 
#>       extrude    visibility     drawOrder          icon           fid 
#>     "integer"     "integer"     "integer"   "character"     "numeric" 
#>            DN     geometry1     geometry2 
#>     "integer" "sfc_POLYGON"         "sfc"
```
