### ISSUE TITLE
rgee won't load when publishing ShinyApp

### ISSUE THREAD

**Issue by MVanDenburg92** [r-spatial/rgee#119]
* rgee version: 1.0.8.9999
* R version 4.0.2 
* Operating System: Windows 10 

#### At submit an issue, please attached the following information of your `rgee` session:

- [X] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("C:/Users/mvand/.config/earthengine/credentials")
file.exists(ee_path)
```

- [X] You can run a simple EE command from R: 

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())
``` 

Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()
```
python:         C:/Users/mvand/anaconda3/envs/rgee/python.exe
libpython:      C:/Users/mvand/anaconda3/envs/rgee/python39.dll
pythonhome:     C:/Users/mvand/anaconda3/envs/rgee
version:        3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:29:07) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/mvand/anaconda3/envs/rgee/Lib/site-packages/numpy
numpy_version:  1.20.0
ee:             C:\Users\mvand\ANACON~1\envs\rgee\lib\site-packages\ee\__init__.p

NOTE: Python version was forced by RETICULATE_PYTHON

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

So I have this Shiny App that my partner and I made to analyze phenology metrics using the R greenbrown package. The app works fine on our personal computers. I want to publish the shiny app (it's just a single app.R with the UI and Server all in one) and whenever I publish it and try to see the results of the app online I get the following image:

![image](https://user-images.githubusercontent.com/54696014/106685377-46aa5580-6596-11eb-86f1-2ad5de909806.png)

It should just host online and allow the user to select the dates of interest for the analysis and one of three polygons of interest. Again, the app runs fine on my own computer and my research partner's (both windows 10 users). It's only when attempting to publish the app that I run into the below error. I even tried creating an isolated Python virtual environment with all rgee dependencies using the link https://r-spatial.github.io/rgee/reference/ee_install.html. 

I have been looking around and it seems like this problem occurs with people using Reticulate on ShinyApps as well. 

I can post my full app code but it's quite a lot and the failure seems to be in getting rgee to be found. 

### What I Did

I was attempting to publish a shiny app I made using rgee to shinyapps.io. When I publish it using Rstudio I get the below message.

Here are the packages I am using along with the load up method for rgee before initializing: 
```
library(shiny)
# install.packages("shinybusy")
library(shinybusy)
library(slickR)
library(svglite)
library(greenbrown)
library(sf)
library(sp)
library(tidyverse)

library(raster)
library(qdapRegex)
library(lubridate)

library(doParallel)  #Foreach Parallel Adaptor 
library(foreach)
library(parallel)
library(gsubfn)

library(rgdal)
library(DT)
library(magrittr)
library(kimisc)
library(rgee)

# ee_install()
# ee_install(py_env = "rgee")

ee_install(
    py_env = "rgee",
    earthengine_version = ee_version(),
    confirm = interactive()
)

ee_Initialize()

```

```
Error in value[[3L]](cond) : package or namespace load failed for ‘rgee’:
 .onLoad failed in loadNamespace() for 'rgee', details:
  call: py_module_import(module, convert = convert)
  error: ModuleNotFoundError: No module named 'ee'

Detailed traceback: 
  File "/opt/R/4.0.2/lib/R/library/reticulate/python/rpytools/loader.py", line 19, in _import_hook
    module = _import(
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

**Comment by csaybar** [comment]
Hi @MVanDenburg92  did you trying creating a Dockerfile?.  I don't have experience deploying ShinyApps but it seems is possible deploy a ShinyApp with Docker.  https://www.statworx.com/ch/blog/how-to-dockerize-shinyapps/

The problem is that you will have to handle manually all the requirements of authentification (it means without using ee_install). I have a DockerFile that we created for testing purposes https://github.com/csaybar/rgee-docker. It is not well implemented but definitely can give you some ideas.

This is not something particular of rgee, the same is with Python https://github.com/giswqs/geemap-heroku/blob/master/config_vars.py. Let me know if you continue having problems deploying your app, 
this is something that we give more support in the future!

**Comment by csaybar** [comment]
Hi, I added a template that should make the deployment process easier.
https://github.com/csaybar/shiny_rgee_template
