### ISSUE TITLE
ee_install_set_pyenv ignores local .Renviron file

### ISSUE THREAD

**Issue by myoung3** [r-spatial/rgee#121]
`rgee::ee_install_set_pyenv()` sets environment variables in `~/.Renviron` even if there's a `./.Renviron` file.  It should really check for a local file and modify that if there is one, and otherwise set the global file.

**Comment by csaybar** [comment]
Sorry, what do you mean with local file?. `ee_install_set_pyenv` set the variable EARTHENGINE_PYTHON and EARTHENGINE_ENV in your .Renviron

**Comment by myoung3** [comment]
So you can have an .Renviron file local to your working directory which supersedes the .Renviron file in `~/.Renviron`.

see `?Startup` ([here](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html)), specifically


> In R, the startup mechanism is as follows.
> 
> Unless --no-environ was given on the command line, R searches for site and user files to process for setting environment variables. 
> The name of the site file is the one pointed to by the environment variable R_ENVIRON; if this is unset, ‘R_HOME/etc/Renviron.site’ is used (if it exists, which it does not in a ‘factory-fresh’ installation). 
> The name of the user file can be specified by the R_ENVIRON_USER environment variable; if this is unset, *the files searched for are ‘.Renviron’ in the current or in the user's home directory (in that order). See ‘Details’ for how the files are read.*
> 
(emphasis added)

**Comment by myoung3** [comment]
The idea is that users may want multiple projects with different `.Renviron` configurations and thus they create different `.Renviron` files. Right now `rgee` ignores the `.Renviron` file in the working directory and writes to the global .Renviron. But if there is a local `.Renviron` file, that global file is ignored entirely.

**Comment by csaybar** [comment]
I didn't know anything about this. It has a lot of sense, I will implement in the next release of rgee, thanks :)

**Comment by csaybar** [comment]
Hi @myoung3 now `ee_install_set_pyenv` can set local `.Renviron` files and `rgee` read local `.Renviron` files.

```r
library(rgee)
ee_install_set_pyenv(py_path = "/usr/bin/python3", Renviron = "local")
ee_install_set_pyenv(py_path = "/usr/bin/python3", Renviron = "/home/zgis/")
```

Please let us know if you persist having problem!
