### ISSUE TITLE
ee_install() doesn't work.

### ISSUE THREAD

**Issue by caio-valente14** [r-spatial/rgee#123]
Hi everyone.

I've searched for tutorials to help configure the package in my PC, and I've found this one: https://www.youtube.com/watch?v=_fDhRL_LBdQ

I executed every part of the code interactively with the tutorial, but when I run `ee_install()` (after installing miniconda with `py_discover_config()` and other packages previously, such as `reticulate`), but it keeps me returning an error saying that anaconda is mandatory for the package since I'm a windows user.

Here is the error I get:

`Error in ee_install_set_pyenv_env(py_env = py_env, py_path = python_path,  :
  Windows users must install miniconda/anaconda to use rgee. The use of a Python environment is mandatory.`

I've just installed Anaconda (full version with navigator) and I set a new python environment called "py2r" and tried to use the function `ee_install_set_pyenv()`, passing the path to the environment created through Anaconda Navigator (which has a `python.exe`) as paremeter to `py_path` and the name "py2r" as paremeter for `py_env` arg. And yet, it didn't work.

What am I missing? 

In case you want to take a look at the code, I can provide it, but I don't think it's necessary because is a simple test script that follows as I described.

Thanks for your attention and congratulations for the library, it will be very usefull for me at work!

**Comment by csaybar** [comment]
Hi @caio-valente14,

You just need to run **ee_install** no more than that!. More of the step that the video shows are automatic, so you don't need to do it (like install previously reticulate or use ee_install_set_pyenv). Also, Windows users can use either miniconda or anaconda.

1. Terminated your R session.
2. Run:
```r
library(rgee)
ee_install()
```
3. Restart your R session.
4. Run ee_Initiliaze().
```r
library(rgee)
ee_Initialize()
```
Please let us know which of the previous steps (number) you have problems.

**Comment by caio-valente14** [comment]
Hi @csaybar !

Thanks so much for helping me.

What happened is that when the console returns some question asking if I would like to continue, after the console returns the message that `rgee` wants to store some environment variables in my `.Renviron`.

Here I can show you what is the message and the error returned by console:
```
rgee::ee_install want to store the environment variables: EARTHENGINE_PYTHON

and EARTHENGINE_ENV in your .Renviron file to use the Python path:

C:\Users\CLEITE\AppData\Local\r-miniconda\envs\rgee\python.exe in future sessions.

Would you like to continues? [Y/n]:Y

Error in ee_install_set_pyenv_env(py_env = py_env, py_path = python_path, : Windows users must install miniconda/anaconda to use rgee. The use of a Python environment is mandatory.
```

What is strange is that I have Anaconda installed in my PC, but I didn't add the path to the system path variables.

Do you think that could be the issue?

Again, thanks a lot man!

**Comment by csaybar** [comment]
Hi @caio-valente14 can you upgrade rgee  and try it again? 
It should work now

**Comment by caio-valente14** [comment]
Man, thanks a lot!

Now it worked for me!

I'll recommend this package to others who are interested in this GIS topics with programming!

And congratulations for the tutorial video in youtube! 

Since I'm new in proramming (less than a year working with) it's very usefull to have this kind of tutorials to promote such a great package for beginners like me.

I really appreciate your help!

**Comment by csaybar** [comment]
Happy to hear that :+1: . I committed a shameful error :), that was the problem.
