### ISSUE TITLE
Cannot run "ee_Initialize()" to initialize python environment

### ISSUE THREAD

**Issue by caio-valente14** [r-spatial/rgee#125]
I just posted some issue related to `ee_install()` function, and you solved the problem, and for that thanks once more, but I need another help here.

Now I'm having problems with `ee_Initialize()` function. 

After it connects to GEE, with my login, and generate the token, when I enter the token as input to console it returns some error:

```
> ##### Initialize Python environment #####

> ee_Initialize()

-- rgee 1.0.8.9999 ------------------------------------------------------------------------------ earthengine-api 0.1.250 --

 √ email: not_defined

√ Initializing Google Earth Engine:Error in py_call_impl(callable, dots$args, dots$keywords) :

  SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

 

Detailed traceback:

  File "C:\Users\CLEITE\AppData\Local\R-MINI~1\envs\rgee\lib\site-packages\ee\__init__.py", line 120, in Initialize

    http_transport=http_transport)

  File "C:\Users\CLEITE\AppData\Local\R-MINI~1\envs\rgee\lib\site-packages\ee\data.py", line 199, in initialize

    _install_cloud_api_resource()

  File "C:\Users\CLEITE\AppData\Local\R-MINI~1\envs\rgee\lib\site-packages\ee\data.py", line 273, in _install_cloud_api_resource

    http_transport=_http_transport)

  File "C:\Users\CLEITE\AppData\Local\R-MINI~1\envs\rgee\lib\site-packages\ee\_cloud_api_utils.py", line 151, in build_cloud_resource

    cache_discovery=False)

  File "C:\Users\CLEITE\AppData\Local\R-MINI~1\envs\rgee\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper

    return wrapped(*args, **kwargs)

  File "C:\Users\CLEITE\AppData\Local\R-MINI~1\envs\rgee\lib\site-packages\googleapiclient\di
```

I'm using a mail account from my university, but it's vinculated to Google, it is a simple gmail but with the sufix "@usp.com.br" instead of "@gmail.com", could be this the problem?

I really don't know if it's the problem, since I successfully logged in with my account in the browser to GEE, and it did generate a code to enter, which was copied and pasted as it was.

**Comment by csaybar** [comment]
Very odd. The use of  "@usp.com.br" shouldn't be a problem. Can you run:

```r
oauth_func_path <- system.file("python/ee_utils.py", package = "rgee")
utils_py <- rgee:::ee_source_python(oauth_func_path)
ee_path <- ee_utils_py_to_r(utils_py$ee_path())
list.files(ee_path)
```
Do you have an activated Earth Engine account right?

**Comment by caio-valente14** [comment]
@csaybar ,

The activated Earth Engine account is the same I use with Earth Engine through browser, right?

If so, I do have an activated account, and it's open in browser right now by the way.

I tried to run the code above in my PC, but it returns an error message with the part `utils_py <- rgee:::ee_source_python(oauth_func_path)`.

```
Error in py_module_import(module, convert = convert) :
    ModuleNotFoundError: No module named: 'ee'

Detailed traceback:
    File: "C:\Users\CLEITE\Documents\R\win-library\4.0\reticulate\python\rpytools\loader.py", line24, in _import_hook
        level = level
    File: "C:\Users\CLEITE\Documents\R\win-library\4.0\rgee\python\ee_utils.py", line 8, in <module>
        import ee
    File: "C:\Users\CLEITE\Documents\R\win-library\4.0\reticulate\python\rpytools\loader.py, line 24, in _import_hook
        level = level
```

**Comment by caio-valente14** [comment]
@csaybar , another information, I don't know if it is relevant...

I had success in initializing the python environment in my personal computer, but in my company's PC isn't working yet.

**Comment by csaybar** [comment]
Sorry I don't understand well windows systems, but it seems it is a problem of privileges of your OS systems instead of earth-
engine. There are some other similar issues here https://github.com/google/earthengine-api/issues?q=SSL and here https://stackoverflow.com/questions/64856038/error-ssl-certificate-verify-failed-when-running-earthengine-authenticate

**Comment by caio-valente14** [comment]
@csaybar ,

Maybe it could be some security issues due to company's privacy policy. 

I really don't have a clue about it, I'm contacting de IT team to ask them if they imagine what could cause something like that, but, sadely, maybe I'll won't be able to use this package in my projects =/

One last question, I saw that my personal computer (which is running the package fine) has a different version of `net framework`, could it be possible that if I update the `net framework` it will work? The version in my personal computer is 4.8.04084, and company's 4.8.03752. 

I really have tried all possible ways I know, and those that I'm not familiar with I cannot test in company's computer because it could put me into trouble with IT team and company's privacy policy.

 Maybe I'll try it from Python, but I have to talk to my boss first because I work at cellulose company, people there are not familiar even with R, which is being required a lot to new professionals now, and the main issue my boss talked about is that, since I'm an intern, if I don't stay at company for a long period there won't be anyone capable of supporting the tool.

I'll do my best here.

Thanks a lot for your attention and congrats for the package again, I'll use it in my PC for study porpouses.

**Comment by csaybar** [comment]
Thanks for your supportive words :), I hope you will solve the problem soon. I will close the issue but feel free to open it again if you consider it pertinent.

**Comment by caio-valente14** [comment]
Ok @csaybar .

I'm having a meeting with IT team next week to talk about this issue.

It seems there is a security issue with running this package, and it happens on Python package too, because there is this SSL verification of certificates from a web server.

Thanks for your help! :)
