### ISSUE TITLE
How to addLayer() multiple times? Seemd to overwrite previous one?

### ISSUE THREAD

**Issue by MatthieuStigler** [r-spatial/rgee#126]
I am not able to `addLayer()` on top of a previous one? Calling twice `addLayer()` will show only the most recent one?

Reproducible code:

```
library(rgee)
rgee::ee_Initialize()

CDL_19 = ee$Image("USDA/NASS/CDL/2019");

point = ee$Geometry$Point(-98.8285, 41.3369)
point_buf = point$buffer(250)


Map$setCenter(-98.8285, 41.3369, zoom=12)
Map$addLayer(CDL_19$select("cropland"))
Map$addLayer(point_buf)
```

* rgee version: 1.0.8
* R version: 4.0.3
* Operating System: Ubuntu 20.04

**Comment by csaybar** [comment]
rgee support to operator `+` and `|`.

```r
library(rgee)
ee_Initialize()

CDL_19 = ee$Image("USDA/NASS/CDL/2019");

point = ee$Geometry$Point(-98.8285, 41.3369)
point_buf = point$buffer(250)


Map$setCenter(-98.8285, 41.3369, zoom=12)
Map$addLayer(CDL_19$select("cropland")) +
Map$addLayer(point_buf)

Map$addLayer(CDL_19$select("cropland")) |
Map$addLayer(point_buf)
```
You can also obtain the metadata of the interactive map.

```r
m1 <- Map$addLayer(CDL_19$select("cropland"))
m1$rgee$tokens
```

**Comment by MatthieuStigler** [comment]
Thanks!

Is the need of using `+` operator intentional, or a constraint from the implementation?

Given that the java and Python interfaces don't require the `+`, and don't have `addLayer` overwriting the previous layer, it would be nice if this could be also the default with `rgee`!? Thanks!!

**Comment by csaybar** [comment]
It's intentional! to make rgee more similar to other packages (i.e. mapview, tmap, leaflet, etc.). I see no problem with both ways of stacking EE objects coexisting. I will add this feature in the next release. Thanks a lot for the feedback :)

**Comment by MatthieuStigler** [comment]
oh great, having rgee follow closely the EE workflow with `addLayer` would be great indeed, thanks for all the good work Cesar!!

**Comment by csaybar** [comment]
Hi @MatthieuStigler it took me more time than I expected but now `rgee` supports an OOP-oriented style like Python. We change all the map viz module now **rgee** depends on R6 OOP system

You can see all the examples running `?R6Map`.

```r
library(rgee)
ee_Initialize()

# Load an Image
image <- ee$Image("LANDSAT/LC08/C01/T1/LC08_044034_20140318")

# Create
Map <- R6Map$new()
Map$centerObject(image)

# Simple display: Map just will
Map$addLayer(image, list(min=0, max = 10000, bands = c("B4", "B3", "B2")), name = "l8_01")
Map$addLayer(image, list(min=0, max = 20000, bands = c("B4", "B3", "B2")), name = "l8_02")
Map
# Simple display: Map just will (if the position is not specified it will
# be saved on the right side)
Map$reset() # Reset Map to the initial arguments.
Map$centerObject(image)
Map$addLayer(image, list(min=0, max=10000, bands = c("B4", "B3", "B2")), name = "l8_left", position = "left")
Map$addLayer(image, list(min=0, max=20000, bands = c("B4", "B3", "B2")), name = "l8_right")
Map
```

This module has no been tested yet, so if you find a bug please let us know!

**Comment by MatthieuStigler** [comment]
Nice. thanks a lot Cesar! It is great to have rgee follow closely the java and Python implementation!
