### ISSUE TITLE
reduceRegion() vs. reduceRegions() vs. for-loop

### ISSUE THREAD

**Issue by joshualerickson** [r-spatial/rgee#127]
* rgee version:
* R version:
* Operating System:

#### At submit an issue, please attached the following information of your `rgee` session:

- [x ] You have the Python API installed (from terminal):
```
earthengine -h
```

- [x ] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
```
- [x ] You can run a simple EE command from R: 

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())
``` 

Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()
python:         C:/Users/joshualerickson/AppData/Local/r-miniconda/envs/rgee/python.exe
libpython:      C:/Users/joshualerickson/AppData/Local/r-miniconda/envs/rgee/python38.dll
pythonhome:     C:/Users/joshualerickson/AppData/Local/r-miniconda/envs/rgee
version:        3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 18:22:52) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/joshualerickson/AppData/Local/r-miniconda/envs/rgee/Lib/site-packages/numpy
numpy_version:  1.19.1
ee:             C:\Users\JOSHUA~1\AppData\Local\R-MINI~1\envs\rgee\lib\site-packages\ee\__init__.p

NOTE: Python version was forced by RETICULATE_PYTHON
```

### Description

As always, thanks for the awesome work on this PACKAGE and making it available!

When using reduceRegion or reduceRegions I keep getting an error when using maxPixels or bestEffort. Now I'm assuming that's either a GEE/reticulate/R thing or maybe I'm not using it correctly? Which is normally not a big deal (just up the scale and map/for-loop numerous features, etc) but the issue starts to show its head when wanting to use future processing on the expression, i.e. if a future is possible then one can still work on other processes while the big pixel, big featureCollection is being processed in the background. I'm working on doing this in a function currently; however, when the featureCollection is too big and you don't want to compromise scale the next logical step would be to up the pixels but this doesn't work? I'm sure you're aware of the message but i'll post it anyways. So, more of a enhancement/work around/thoughts but also wondering if it's possible to get maxPixels enabled. Hope this makes sense.... 

### What I Did

```
> stats_test <- mg$reduceRegions(
+   reducer = ee$Reducer$median(),
+   collection = rge$reg,
+   scale = 30,
+   maxPixels = 1e10
+ )
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  EEException: Unrecognized arguments {'maxPixels'} to function: Apply a reducer over the area of each feature in the given collection. The
reducer must have the same number of inputs as the input image has bands.
Returns the input features, each augmented with the corresponding reducer
outputs.

Args:
  image: The image to reduce.
  collection: The features to reduce over.
  reducer: The reducer to apply.
  scale: A nominal scale in meters of the projection to work in.
  crs: The projection to work in. If unspecified, the projection of
      the image's first band is used. If specified in addition to
      scale, rescaled to the specified scale.
  crsTransform: The list of CRS transform values.  This is
      a row-major ordering of the 3x2 transform matrix.
      This option is mutually exclusive with 'scale', and
      will replace any transform already set on the
      projection.
  tileScale: A scaling factor used to reduce aggregation tile
      size; using a larger tileS 
```

**Comment by csaybar** [comment]
Hi @joshualerickson thanks for the word of encouragement, we are really happy to see rgee useful :).
reduceRegions does not support maxPixels but reduceRegion, did you try our addin for Rstudio?

![ezgif-2-7499f28e66e4](https://user-images.githubusercontent.com/16768318/107670086-af7a8780-6c92-11eb-8e76-2619427d2537.gif)

The use of lazy in **ee_extract** is something we are planning to support in the next release. Unfortunately, at this time, **ee_extract ** fetch and returns data with getInfo which might not be the most efficient for large queries.

**Comment by joshualerickson** [comment]
Thanks Cesar and no I haven't looked at the addin but will give it a looksy! I'll be looking for the update as well, thanks again!

**Comment by csaybar** [comment]
Sorry it seems that the gif is not complete :)
https://twitter.com/csaybar/status/1292015511547580416

**Comment by csaybar** [comment]
Hi @joshualerickson now `ee_extract` has support to download via `drive` and `gcs` and lazzy evaluation.

```r
library(rgee)
library(sf)

ee_Initialize(gcs = TRUE, drive = TRUE)

# Define a Image or ImageCollection: Terraclimate
terraclimate <- ee$ImageCollection("IDAHO_EPSCOR/TERRACLIMATE") %>%
  ee$ImageCollection$filterDate("2001-01-01", "2002-01-01") %>%
  ee$ImageCollection$map(
    function(x) {
      date <- ee$Date(x$get("system:time_start"))$format('YYYY_MM_dd')
      name <- ee$String$cat("Terraclimate_pp_", date)
      x$select("pr")$rename(name)
    }
  )

# Define a geometry
nc <- st_read(
  dsn = system.file("shape/nc.shp", package = "sf"),
  stringsAsFactors = FALSE,
  quiet = TRUE
)


#Extract values - getInfo
ee_nc_rain <- ee_extract(
  x = terraclimate,
  y = nc["NAME"],
  scale = 250,
  fun = ee$Reducer$mean(),
  via = "drive",
  lazy = TRUE,
  sf = TRUE
)

ee_nc_rain <- ee_nc_rain %>% ee_utils_future_value()
plot(
  ee_nc_rain["X200101_Terraclimate_pp_2001_01_01"],
  main = "2001 Jan Precipitation - Terraclimate",
  reset = FALSE
)
```

**Comment by joshualerickson** [comment]
Thanks @csaybar! I'll give it a test in the next few days. Nice addition :)
