### ISSUE TITLE
rgee compatability with mapview

### ISSUE THREAD

**Issue by jobbo90** [r-spatial/rgee#128]
* rgee version: 
* R version: Version 1.3.1093
* Operating System: Windows 10 Enterprise (v1809)

#### At submit an issue, please attached the following information of your `rgee` session:

- [ ] You have the Python API installed (from terminal):
```
earthengine -h
```

- [ ] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
```

"//soliscom.uu.nl/users/5600944/My Documents/.config/earthengine/credentials"
TRUE

- [ ] You can run a simple EE command from R: 

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()
# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())
``` 

-- rgee 1.0.8 ---------------------------------------------------------------------------------------------------------------- 
earthengine-api 0.1.248 -- 
 √ email: not_defined
 √ Initializing Google Earth Engine:  DONE!
 √ Earth Engine user: users/jobdevries90 

Both work fine

Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()
```

python:         C:/Users/5600944/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/5600944/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/5600944/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.6.12 (default, Dec  9 2020, 00:11:44) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/5600944/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.19.4

``` run ee_check()
(*)  Python version
√ [Ok] C:/Users/5600944/AppData/Local/r-miniconda/envs/r-reticulate/python.exe v3.6
(*)  Python packages:
√ [Ok] numpy
√ [Ok] earthengine-api
```

### Description

I'm experiencing some issues lately with making the rgee library work with mapview, all examples used to work previously but I guess after some updates they no longer do. I reinstalled following all kinds of settings but can't seem to find the conflict between mapView and rgee

### What I Did

```
library(rgee)
 ee_Initialize()
 
 vizParams = list(
    bands = c("B5", "B4", "B3"),
    min = 0.05, max = 0.4, gamma = 1.4
  )

 collection<- ee$ImageCollection("LANDSAT/LT05/C01/T1_TOA")$
    filterBounds(ee$Geometry$Point(-55.54, 5.94))

i <- c("2000-05-22")

 filtCollect <- collection$filterDate(as.character(as.Date(i)-100), 
                                       as.character(as.Date(i)+100))
 dates <- ee_get_date_ic(filtCollect, time_end = FALSE)
  
 Map$centerObject(filtCollect$first())
 first <- Map$addLayer(filtCollect$first(), vizParams, paste0('landsat: ',i))
stp1 <- st_sfc(st_point(c(-55.6, 6.02)), crs=4326)

stp2 <- st_sfc(st_point(c(-55.6, 6.02)), crs=4326)

first  # as expected, the image is plotted
mapview(stp1) # also, as expected the point is plotted

Now try combining:
first + mapview(stp1) # throws error
mapview(first, stp1)  # error
mapview(stp1, first)  # no error!!
```

Error in +.EarthEngineMap(first, mapview(stp)) :
right map is not an EarthEngineMap object

So here it gets confusing for me:

mapview(stp1, first) works but mapview(first, stp1) doesn't and throws me a whole other error:

Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function ‘mapView’ for signature ‘"leaflet"’

because I was thinking this had to do with my python & earthegine environments I tried to reinstall, without succes of improving. Also because I didn't have the error before, I'm not sure where to proceed. I have a sense it has to do with the fact that this is company laptop where the relative paths are always a bit messed up (e.g. Earth Engine credentials in //soliscom.uu.nl/users/5600944/My Documents/.config/earthengine/credentials). But who knows I'm totally missing something..

**Comment by csaybar** [comment]
Hi @jobbo90 thanks for open this issue.

rgee in the latest version does not return a `mapview` object but a `leaflet` object. 

```r
class(first)
#  "leaflet"      "htmlwidget"   "EarthEngineMap"
```

That is why you got an error when you run:

```r
first + mapview(stp1) # throws error
mapview(first, stp1)  # error
```

The proper way to merge `rgee` and `mapview` is:

```
mapview(x = stp1, map = first)
```

The changes made are because we want to avoid strong dependencies to a specific R package to display interactive maps. Currently `rgee` only depends on `leafem` (A nice R package with helpful JS widgets) and `leaflet` to display Earth Engine on-the-fly-resources.

Here there is a nice introduction about how to integrate `rgee` with other R packages and QGIS.

- https://r-earthengine.github.io/image_01/
- https://r-earthengine.github.io/image_02/

**Comment by jobbo90** [comment]
Ah thanks for the clarification, missed that bit about the update. 

A pitty though because mapview seems to have a nice 'clickable' lay-out, especially when there is multiple spatial datasets involved.  For example when I try to plot 2 spatial point datasets over the rgee satellite image, I can't figure out how that works:

mapview(list(stp1, stp2), first) # error: Error in FUN(X[[i]], ...) : 
  'options' must be a fully named list, or have no names (NULL)

mapview(stp1, first) + mapview(stp2) # same

Yet just adding the points seems to work: 

mapview(list(stp1, stp2))

**Comment by csaybar** [comment]
I think this way is much better because `mapview` is no the only package that offers support to display interactive maps. Makes that **Map.addLayer** that only depends on `leaflet` and returns a `leaflet` object will increase the interoperability with other geoviz packages like `tmap` for instance. 

If you want to display two spatial objects in mapview with an Earth Engine on-the-fly resource in the backend you just need to use the second argument of **mapview::mapview**(x, **map**). However, it seems this argument is a bit buggy (it seems it has some problems with deal with WMSTiles and XYZtiles). I will investigate the errors that you reported a bit deeper, but for now, something like this should works:


```r
library(cptcity)
library(mapview)
library(leaflet)
library(rgee)
library(sf)


ee_Initialize() # Initialize Google Earth Engine (Just One time)

# 1. world map ------------------------------------------------------------
cpt_pal <- cpt(pal = "mpl_inferno")
image <- ee$Image('CGIAR/SRTM90_V4')
m1 <- Map$addLayer(
  eeObject = image,
  visParams = list(min = 0, max = 5000, palette= cpt_pal),
  name = 'SRTM90_V4'
)

m2 <- mapview(franconia)
m3 <- mapview(breweries)
m4 <- m2 + m3
m4@map + m1
```

**Comment by joshualerickson** [comment]
@csaybar really like the approach you presented. I'm going to change some of my code after reading this issue and encourage people to use your above example to add onto a 'leaflet' map. Thanks!

**Comment by csaybar** [comment]
We already upload a new version of Map that uses R6 rather than just env. Although It is not properly tested yet.

**Comment by jobbo90** [comment]
Thanks @csaybar this works like a charm!
