### ISSUE TITLE
Error: unexpected 'repeat': Conflict of ee$Reducer$repeat versus R's reserved repeat?

### ISSUE THREAD

**Issue by MatthieuStigler** [r-spatial/rgee#129]
I believe there is a conflict between `ee$Reducer$repeat` and R base `repeat`. The problem is that as `repeat` is a reserved word in R, using `repeat` will throw an error: *Error: unexpected 'repeat'*

A simple solution is to quote `'repeat'` like: `ee$Reducer$'repeat'`. This will then work. I guess it will be hard to solve this at the rgee level, so hopefully this post will help people facing the same issue?

```
library(rgee)
rgee::ee_Initialize()

point = ee$Geometry$Point(c(-103.44862, 25.90856))
box = point$buffer(50)$bounds()


coords = ee$List(box$coordinates()$get(0))
minMax = ee$Dictionary(coords$reduce(ee$Reducer$minMax()$repeat(2))) # does not work
minMax = ee$Dictionary(coords$reduce(ee$Reducer$minMax()$'repeat'(2))) # works
```

**Comment by csaybar** [comment]
Yes!, unfortunately, this is something that is impossible to solve without making changes to the Python EarthEngine API. The same issue was open here: https://stackoverflow.com/questions/65027506/problems-with-eelistrepeat. Thanks, I will maintain open this issue until I upgrade the documentation.

**Comment by csaybar** [comment]
Hi @MatthieuStigler I added a new section in the *consideration* vignette reporting this problem. Thanks :)
