### ISSUE TITLE
Using `map(function(x)...)` returns error: Evaluation error: argument "x" is missing, with no default. 

### ISSUE THREAD

**Issue by MatthieuStigler** [r-spatial/rgee#130]
I am trying to map a simple function over a ee.list, but I get an error *Evaluation error: argument "x" is missing, with no default. *. I am not sure what is wrong? The code works in [javaScript](https://code.earthengine.google.com/44d87376be8c3d71aefd1dec6cd26f23) and python (`li.map(lambda x: ee.Number(x).ceil()).getInfo()`) but no in rgee 1.0.8?

```
library(rgee)
rgee::ee_Initialize("Matthieu.Stigler@gmail.com")

li = ee$List(c(1.5, 2.1))

## Function to round numbers:
fo <- function(x) ee$Number(x)$ceil()
fo(2.1)$getInfo()

## But does not work with map()?
li$map(fo)
li$map(function(x) ee$Number(x)$ceil())

```

**Comment by csaybar** [comment]
Hi @MatthieuStigler 
Maybe this post can help:
 - https://r-spatial.github.io/rgee/articles/rgee02.html#the-map-message-error

```r
library(rgee)
rgee::ee_Initialize()

li <- ee$List(c(1.5, 2.1))

## Function to round numbers:
fo <- function(x) ee$Number(x)$ceil()
fo(2.1)$getInfo()

## But does not work with map()?
li$map(ee_utils_pyfunc(fo))$getInfo()

```

**Comment by MatthieuStigler** [comment]
Oh sorry, I missed that post! That solves it, thanks!
