### ISSUE TITLE
 Error in py_call_impl(callable, dots$args, dots$keywords) in ee_Initialize()

### ISSUE THREAD

**Issue by javortegar** [r-spatial/rgee#131]
Hi! I just installed rgee succesfully on my Rstudio and I have some troubles when I try to run the ee_Initialize() function, the error was with the next message:
> ee$Initialize()
>-- rgee 1.0.8 ----------------------------------------------- earthengine-api 0.1.248 -- 
> √ email: not_defined
> √ Initializing Google Earth Engine:
>  Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   AttributeError: module 'six.moves' has no attribute 'collections_abc' 

I don't have troubles when I use the functions: ee_check(). ee_check_credentials(), etc... everything is ok with that.

Any suggestion about what I'm doing wrong?
Thanks.

**Comment by csaybar** [comment]
Hi @javortegar this is a problem in Python not R. 
Upgrade the EarthEngine Python API works?

1. Terminate your R session. 
2. Upgrade ee.
```r
library(rgee)
ee_install_upgrade()
```
Maybe these links could help.

https://github.com/googleapis/google-api-python-client/issues/1039
https://github.com/gee-community/qgis-earthengine-plugin/issues/67

**Comment by javortegar** [comment]
Hi @csaybar, thanks for your response. Effectively, it was a problem in Python.

Finally, I could find there was a trouble with the version of the package 'six' 1.12.0. I upgraded to the 1.13.0 version that fix a bug related to the message that I was getting. 

So, I could use many rgee functions succesfully after that.

Regards and thank you again.
