### ISSUE TITLE
ee_as_sf when bands have too long names: more informative warning?

### ISSUE THREAD

**Issue by MatthieuStigler** [r-spatial/rgee#132]
This is just a small detail, but if band names are too long, using with `ee_as_sf` the default dsn (default to shp), band names will be trimmed (to 10 characters), and in that case, trimming could lead to duplicate band names. This happened to me trying to use `ee_as_sf` with band names *201904_tmmn* and *201904_tmmx* (wide version of Terraclim data). They became both *X201904_tmm*, which trigger a quite obscure error (see code below):  

> Unknown field name `X201804_tmmn': updating a layer with improper field name(s)?
> Error in CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  : 
>   Write error

As user, a simple solution is to use another default driver, say: `dsn =paste0(tempfile(), ".geojson")`

From the `rgee` perspective, a simple solution would be to check, whenever the shp driver is used, that the trimmed band names are unique, and if not throw simply a warning (see code sample)? Or another solution could be to use another driver by default, maybe *.geojson*? What was the reason for choosing shp as default? My understanding is that there's quite a few issues with that format?

Suggested pseudo code (add in *rgee:::ee_fc_to_sf_getInfo*, just before *suppressWarnings(sf::write_sf(x_sf...*)

```
if(tools::file_ext(dsn)=="shp"){
  cols <- colnames(x_sf)
  if(any(nchar(cols)>10)){
    trim <- substr(cols, start=0, stop = 10)
    if(any(duplicated(trim))) warning("Too long columns names will be trimmed and lead to duplicates?\nSpecify shorter name or specify a different driver than shp with argument 'dsn'")
  }
}
```

rgee code with error:

```
library(rgee)
rgee::ee_Initialize()


## Import data
TerClim = ee$ImageCollection("IDAHO_EPSCOR/TERRACLIMATE")$filter(ee$Filter$calendarRange(2018, 2019, "year"))
TerClim_wide = TerClim$filter(ee$Filter$calendarRange(4, 5, "month"))$toBands()


## get point
point = ee$Feature(ee$Geometry$Point(c(35.32541, -0.7992849)), list(id="aa"))


## function
reduce_mean <- function(f) {
  out = f$set(TerClim_wide$reduceRegion(
    geometry= f$geometry(),
    reducer= ee$Reducer$mean(), 
    scale= 10,
    crs="EPSG:4326"))##$combine(nonempty, FALSE))
  out
}

## Apply function
check_1 <- reduce_mean(point)$getInfo()
geojsonio::geojson_sf(check_1)
check_1$properties$'201904_tmmn'

## problem with ee_as_sf?
tmp_2 <- paste0(tempfile(), ".geojson")
ee_as_sf(reduce_mean(point))
ee_as_sf(reduce_mean(point), dsn= tmp_2)

```

**Comment by csaybar** [comment]
Hi @MatthieuStigler, thanks a lot  to bring new ideas and always reporting rgee bugs! We really appreciate it. 

Honestly, I also don't understand why my past self used a shapefile as a default format (this is really embarrassing). This weekend I will start to solve all rgee bugs and I definitely will start with this thanks! :)

```r
check_1 <- reduce_mean(point)$getInfo()
class(check_1) <- "geo_list"
geojsonio::geojson_sf(check_1)
```

**Comment by MatthieuStigler** [comment]
These two lines are actually very useful, thanks!

I am not sure actually why `ee_as_sf` is writing a file, even if `dsn=NULL`? It seems geojsonio::geojson_sf(check_1) is enough?

**Comment by csaybar** [comment]
Yes! It is. `ee_as_sf` supports three forms to move data from Earth Engine to your local environment: `via='drive'`, `via='gcs'`, and `via='getInfo'`. The two first options will always write a file in your system, and to make everything more homogeneous we gave this functionality also to `via='getInfo'`. When `dsn=NULL` rgee will create a file in your `temp()` folder.

**Comment by MatthieuStigler** [comment]
I see... I understand the idea of consistency among methods, but for the gDrive/Gcs, the reason for downloading the file is to be able to read it in R after, right? Here it is first read in R, and then written to file, but not re-used by rgee, unless the user wrote down the temp path?

**Comment by csaybar** [comment]
> the reason for downloading the file is to be able to read it in R after, right?

Yes, only for 'drive' and 'gcs' options.

It has a lot of sense that when users set 'getInfo' and do not specify any path in `dsn` the file is not be written. We implemented this in the new dev version, also `ee_as_sf` save by default a GeoJSON instead of a shapefile.

Thanks!
