### ISSUE TITLE
Map$addLayer with same layer name: Error in if (!e2_shown[x]) e2_name[x] else NULL :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by MatthieuStigler** [r-spatial/rgee#133]
With `rgee` 1.0.8, if one uses `Map$addLayer` with the same layer name, this will trigger an R error: *Error in if (!e2_shown[x]) e2_name[x] else NULL :  missing value where TRUE/FALSE needed*. 

This is admittedly not good practice from the user side and not rgee's fault, but maybe rgee could throw a more informative error message?

Example:

```
library(rgee)
rgee::ee_Initialize()


point = ee$Geometry$Point(c(-103.44862, 25.90856))
point2 = ee$Geometry$Point(c(-103.44872, 25.90809))
LS = ee$ImageCollection("LANDSAT/LC8_L1T_32DAY_NDVI")

Map$centerObject(point, 18)

Map$addLayer(ee$Image(LS$first()), list(min=0.1, max=0.2), 'LS')+
  Map$addLayer(point, list(), 'box')+
  Map$addLayer(point2, list(), 'box')
```

**Comment by csaybar** [comment]
Good catch thanks.

To avoid this I added a random string in hex to the name. I'm not sure if this is the better approach to deal with this problem ... If you have a better idea let us know!

![image](https://user-images.githubusercontent.com/16768318/109718911-317e1200-7ba8-11eb-969c-786ea4f231cf.png)

**Comment by MatthieuStigler** [comment]
nice! I would have eventually just used a `warning("Duplicated layer names, please change one)`. But your solution is even nicer for the user :-)
