### ISSUE TITLE
UnknownApiNameOrVersion: name: earthengine  version: v1alpha 

### ISSUE THREAD

**Issue by michielvandijk** [r-spatial/rgee#136]
I just installed rgee for the first time. I followed the instructions in the article provided on the rgee website. I used the latest version of RStudio to refer to the correct Conda file in Project Settings. When I run Initialize() I receive an error after email and Google credentials are set to green. See below for the information on versions, traceback etc. 

* rgee version: 1.08
* R version: 4.02
* Operating System: Windows 10

> rgee::ee_Initialize(email = 'miguel.van.dijk@gmail.com', drive = TRUE)
-- rgee 1.0.8 --------------------------------------------------------------------- earthengine-api 0.1.248 -- 
 √ email: miguel.van.dijk@gmail.com 
 √ Google Drive credentials:  FOUND
 √ Initializing Google Earth Engine:
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  UnknownApiNameOrVersion: name: earthengine  version: v1alpha 

### Description

Traceback: 
3.
stop(structure(list(message = "UnknownApiNameOrVersion: name: earthengine  version: v1alpha", 
    call = py_call_impl(callable, dots$args, dots$keywords), 
    cppstack = NULL), class = c("Rcpp::exception", "C++Error", 
"error", "condition"))) 
2.
ee$Initialize() 
1.
rgee::ee_Initialize(email = "miguel.van.dijk@gmail.com", drive = TRUE)

**Comment by jdbcode** [comment]
Hi @michielvandijk - please see https://github.com/google/earthengine-api/issues/157
The issue should be resolved in the next version of the `earthengine-api` library.

**Comment by csaybar** [comment]
Thanks, @jdbcode to mention it! I didn't know about it :)

**Comment by jdbcode** [comment]
@csaybar is `rgee` always trying to install the most recent version of the `earthengine-api` library or do you freeze the version in each `rgee` release?

**Comment by csaybar** [comment]
Hi @michielvandijk to solve the problem just follow the next steps in R:

```r
library(rgee)
ee_Initialize() # UnknownApiNameOrVersion: name: earthengine version: v1alpha
reticulate::py_install("google-api-python-client==1.12.8")

# Restart R
.rs.restartR() # if you are using Rstudio

#
ee_Initialize() # it will work now!



```
