### ISSUE TITLE
Knit R markdown with rgee code to html

### ISSUE THREAD

**Issue by khouakhi** [r-spatial/rgee#137]
I can't see where to input the gee credentials when trying to knit an R Markdown with rgee code. The gee Authenticator web page pops up but not sure where to paste the code. 

Here is the R Markdown error I got: 
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Exception: Problem requesting tokens. Please try again.  HTTP Error 400: Bad Request b'{\n  "error": "invalid_request",\n  "error_description": "Missing required parameter: code"\n}'

Detailed traceback: 
  File "C:\Users\e806872\AppData\Local\Continuum\anaconda3\envs\rgee\lib\site-packages\ee\oauth.py", line 89, in request_token
    raise Exception('Problem requesting tokens. Please try again.  %s %s' %
Calls: <Anonymous> ... ee_save_eecredentials -> <Anonymous> -> py_call_impl
Execution halted
```

**Comment by LBautistaB13** [comment]
Hi @khouakhi sorry for the late response. Is it not possible to authenticate `rgee` with Rmarkdown. Please, authenticate your Google Earth Engine account in an R console, it is just necessary once, after that you will not have a problem when you initialize Google Earth Engine with Rmarkdown.

**Comment by khouakhi** [comment]
Tried to `ee_clean_credentials()`  and then `ee_Initialize()` from the console but got the same issue when using the RStudio's "Knit" button however, what worked is `rmarkdown::render('rmd_file .Rmd') ` from the console.

**Comment by LBautistaB13** [comment]
Thanks, can you show us what your R console display after running this:
```r
library(rgee)
ee_Initialize()
```
Share the `traceback()` is really appreciated!

**Comment by khouakhi** [comment]
Now it works: after `library(rgee)` and `ee_Initialize()` from the console, I restarted the R session. The `ee_Initialize()` needs to be within the Rmd code after the first initialization from the console. I think you can close the issue - thanks
