### ISSUE TITLE
ee_initialize - Google Drive credentials:Error: Can't get Google credentials

### ISSUE THREAD

**Issue by MichaelTD83** [r-spatial/rgee#139]
* rgee version: 1.0.9
* R version: R version 4.0.4 (2021-02-15)
* Operating System: Windows 10 x64 

#### At submit an issue, please attached the following information of your `rgee` session:

- [ ] You have the Python API installed (from terminal):
The first time I ran this it said 
```
earthengine -h
M:\Desktop>earthengine -h
Cannot open C:\Users\Michael_Daugherty\AppData\Local\r-miniconda\envs\rgee\Scripts\earthengine-script.py
```
pretty sure I'm doing something wrong here though because after restarting Rstudio I now get a different file path and result
```
C:\Users\Michael_Daugherty\Documents>earthengine -h
'earthengine' is not recognized as an internal or external command,
operable program or batch file.
```

- [ ] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
[1] FALSE
> ee_path
[1] "C:/Users/Michael_Daugherty/Documents/.config/earthengine/credentials"
```
Though this file does exist at C:\Users\Michael_Daugherty\.config\credentials 

- [ ] You can run a simple EE command from R: 

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())

$type
[1] "Image" 
....
$properties$visualization_0_bands
[1] "elevation"
``` 

Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()

python:         C:/Users/Michael_Daugherty/AppData/Local/r-miniconda/envs/rgee/python.exe
libpython:      C:/Users/Michael_Daugherty/AppData/Local/r-miniconda/envs/rgee/python39.dll
pythonhome:     C:/Users/Michael_Daugherty/AppData/Local/r-miniconda/envs/rgee
version:        3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 04:59:43) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/Michael_Daugherty/AppData/Local/r-miniconda/envs/rgee/Lib/site-packages/numpy
numpy_version:  1.20.1

NOTE: Python version was forced by use_python function
```

### Description

After updating the R version and multiple packages I was no longer able to run the ee_initialize function with the drive = TRUE portion. 

```
> library(rgee)
> library(googledrive)
> library(googleCloudStorageR)
> ee_Initialize("mtd25@nau.edu", drive = TRUE, gcs = TRUE)
-- rgee 1.0.9 --------------------------------------------------------------------------- earthengine-api 0.1.257 -- 
 √ email: mtd25@nau.edu 
 √ Google Drive credentials:Error: Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.
  * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html
```

### What I Did
I have attempted to pre-authorize token discovery as mentioned in the link above with no success
```_
> library(rgee)
> library(googledrive)
> library(googleCloudStorageR)
> drive_auth(email = "mtd25@nau.edu")
> ee_Initialize("mtd25@nau.edu", drive = TRUE, gcs = TRUE)
-- rgee 1.0.9 --------------------------------------------------------------------------- earthengine-api 0.1.257 -- 
 √ email: mtd25@nau.edu 
 √ Google Drive credentials:Error: Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.
  * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html
```
The rest of the function works as expected but the googledrive portion does not
```
> library(rgee)
> library(googledrive)
> library(googleCloudStorageR)
> ee_Initialize("mtd25@nau.edu", gcs = TRUE)
-- rgee 1.0.9 --------------------------------------------------------------------------- earthengine-api 0.1.257 -- 
 √ email: mtd25@nau.edu 
 √ GCS credentials:  FOUND
 √ Initializing Google Earth Engine:  DONE!
 √ Earth Engine user: users/mtd25 
--------------------------------------------------------------------------------------------------------------------  
```
Googledrive functions work on their own 
```
> library(googledrive)
> folder <- drive_get(as_id("https://drive.google.com/drive/folders/1eFX87MlJtCde9q9P7TgZfWN6V-1ByhEV"))
The googledrive package is requesting access to your Google account. Select a pre-authorised account or enter '0' to obtain a new token. Press Esc/Ctrl + C to abort.

1: mtd25@nau.edu

Selection: 1
Auto-refreshing stale OAuth token.
> folder
# A tibble: 1 x 3
  name         id                                drive_resource   
* <chr>        <chr>                             <list>           
1 Sample_fires 1eFX87MlJtCde9q9P7TgZfWN6V-1ByhEV <named list [33]>
```
and with pre-authorization
```
> library(googledrive)
> drive_auth(email = TRUE)
> folder <- drive_get(as_id("https://drive.google.com/drive/folders/1eFX87MlJtCde9q9P7TgZfWN6V-1ByhEV"))
> folder
# A tibble: 1 x 3
  name         id                                drive_resource   
* <chr>        <chr>                             <list>           
1 Sample_fires 1eFX87MlJtCde9q9P7TgZfWN6V-1ByhEV <named list [33]>
```
I have also attempted to install earlier versions of the earthengine-api based on the ee_check but with the same results as seen in the description. 
```
> library(rgee)
> ee_check()
(*)  Python version
√ [Ok] C:/Users/Michael_Daugherty/AppData/Local/r-miniconda/envs/rgee/python.exe v3.9
(*)  Python packages:
√ [Ok] numpy
√ [Ok] earthengine-api
NOTE: The Earth Engine Python API version 0.1.257 is installed
correctly in the system but rgee was tested using the version
0.1.254. To avoid possible issues, we recommend install the
version used by rgee (0.1.254). You might use:
* rgee::ee_install_upgrade()
* reticulate::py_install('earthengine-api==0.1.254')
* pip install earthengine-api==0.1.254 (Linux and Mac0S)
* conda install earthengine-api==0.1.254 (Linux, Mac0S, and Windows)
```
Unfortunately earthengine-api==0.1.254 does not exist as far as I can tell. 
https://anaconda.org/conda-forge/earthengine-api/files    and
```
> reticulate::py_install('earthengine-api==0.1.254')
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - earthengine-api==0.1.254

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Error: one or more Python packages failed to install [error code 1]
```
I have also contatced the person in charge of the googledrive package and they seem to thin that the that the problem is not with that package, though there has been recent changes to the authentication process.  https://github.com/tidyverse/googledrive/issues/328

Any guidance would be appreciated,

**Comment by LBautistaB13** [comment]
Hi @MichaelTD83 for open this issue :) and sorry for the inconvenience. It is a weird bug I try to reproduce this error but with no success. Maybe I can explain a bit what `ee_Initialize` does internally ... there are three main functions: `rgee:::ee_create_credentials_drive`,  `rgee:::ee_create_credentials_gcs`, `rgee:::ee_create_credentials_earthengine` each of them try to retrieve and initialize the connection with the google service required. In the case of `drive=TRUE` we rely on the fantastic package `googledrive`  see https://github.com/r-spatial/rgee/blob/f78aa0468a370c7267a9daea41b8872ca74cdf99/R/ee_Initialize.R#L332.

It seems that the problem is related to your institutional account. Can you show us if after running the bellow a Google Drive token is saved in the  `ee_path_user` (FOR SECURITY REASON DO NOT SHARE IT HERE!)?. 

```r
email <- "mtd25@nau.edu"
oauth_func_path <- system.file("python/ee_utils.py", package = "rgee")
utils_py <- rgee:::ee_source_python(oauth_func_path)
ee_path <- ee_utils_py_to_r(utils_py$ee_path())
email_clean <- gsub("@gmail.com", "", email)
ee_path_user <- sprintf("%s/%s", ee_path, email_clean)
print(ee_path_user)

# Is there some Google Drive Token in this Folder?
full_credentials <- list.files(path = ee_path_user, full.names = TRUE)
drive_condition <- grepl(".*_.*@.*", basename(full_credentials))

googledrive::drive_auth(
  email = NULL,
  cache = ee_path_user
)
```

do you see something similar to this?

![image](https://user-images.githubusercontent.com/54723897/112128499-c7fd8c00-8bc6-11eb-87de-43b8854af7e1.png)

Thanks @csaybar

**Comment by MichaelTD83** [comment]
Yes, I there actually two files there ending in my .edu email address (The file type is also listed as EDU file if that makes a difference). There are also several other files and folders there including a .json, credentials.

**Comment by LBautistaB13** [comment]
Hi Michael thanks, just to be sure can u share with us, the result of running this.

```r
email <- "mtd25@nau.edu"
oauth_func_path <- system.file("python/ee_utils.py", package = "rgee")
utils_py <- rgee:::ee_source_python(oauth_func_path)
ee_path <- ee_utils_py_to_r(utils_py$ee_path())
email_clean <- gsub("@gmail.com", "", email)
ee_path_user <- sprintf("%s/%s", ee_path, email_clean)

# Is there some Google Drive Token in this Folder?
full_credentials <- list.files(path = ee_path_user, full.names = TRUE)
drive_condition <- grepl(".*_.*@.*", basename(full_credentials))


drive_credentials <- full_credentials[drive_condition]
email <- sub("^[^_]*_", "", basename(drive_credentials))

print(ee_path_user)
print(email)
```

**Comment by MichaelTD83** [comment]
Here are the results.
```
> library(rgee)
> email <- "mtd25@nau.edu"
> oauth_func_path <- system.file("python/ee_utils.py", package = "rgee")
> utils_py <- rgee:::ee_source_python(oauth_func_path)
> ee_path <- ee_utils_py_to_r(utils_py$ee_path())
> email_clean <- gsub("@gmail.com", "", email)
> ee_path_user <- sprintf("%s/%s", ee_path, email_clean)
> 
> # Is there some Google Drive Token in this Folder?
> full_credentials <- list.files(path = ee_path_user, full.names = TRUE)
> drive_condition <- grepl(".*_.*@.*", basename(full_credentials))
> 
> 
> drive_credentials <- full_credentials[drive_condition]
> email <- sub("^[^_]*_", "", basename(drive_credentials))
> 
> print(ee_path_user)

[1] "C:\\Users\\Michael_Daugherty/.config/earthengine//mtd25@nau.edu"
> print(email)
[1] "mtd25@nau.edu" "mtd25@nau.edu"
```

**Comment by LBautistaB13** [comment]
I think I finally caught the bug :bug: :smile:.

It seems your account has a double credential for google drive. This is a really strange case, see:

```r
googledrive::drive_auth(
  email = c("test1", "test2"),
  cache = "any_path"
)
#> Error: Can't get Google credentials. ....
```

To fix this bug, just run:

```r
library(rgee)
ee_clean_credentials("mtd25@nau.edu")
ee_Initialize("mtd25") #> there is no need to put all your email. The email parameter is just the folder name in your "C:\\Users\\Michael_Daugherty/.config/earthengine/"  path.
```
We will add some extra messages for this in the next release thanks!.  Please let us know if the problem continues.

**Comment by MichaelTD83** [comment]
Thank you! I just had to go download my service account key (SAK) again and it was good to go.

```
> library(rgee)
> library(googledrive)
> library(googleCloudStorageR)
> ee_Initialize("mtd25", drive = TRUE, gcs = TRUE)
-- rgee 1.0.9 ------------------------------------------------------------------------------------- earthengine-api 0.1.257 -- 
 √ email: mtd25 
 √ Google Drive credentials:  FOUND
 √ GCS credentials: NOT FOUND
 √ Initializing Google Earth Engine:  DONE!
 √ Earth Engine user: users/mtd25 
------------------------------------------------------------------------------------------------------------------------------ 
Unable to find a service account key (SAK) file in: C:\Users\Michael_Daugherty/.config/earthengine//mtd25
Please, download and save the key manually on the path mentioned
before. A compressible tutorial to obtain their SAK file is available in:
> https://github.com/r-spatial/rgee/tree/help/gcs/
> https://cloud.google.com/iam/docs/creating-managing-service-account-keys/
> https://console.cloud.google.com/apis/credentials/serviceaccountkey/
Until you do not save a SKA file, the following functions will not work:
- rgee::ee_gcs_to_local()
- ee_extract(..., via = "gcs")
- ee_as_raster(..., via = "gcs")
- ee_as_stars(..., via = "gcs")
- ee_as_sf(..., via = "gcs")
- sf_as_ee(..., via = "gcs_to_asset")
- gcs_to_ee_image
- raster_as_ee
- local_to_gcs
- stars_as_ee
```

```
> library(rgee)
> library(googledrive)
> library(googleCloudStorageR)
> ee_Initialize("mtd25", drive = TRUE, gcs = TRUE)
-- rgee 1.0.9 ------------------------------------------------------------------------------------- earthengine-api 0.1.257 -- 
 √ email: mtd25 
 √ Google Drive credentials:  FOUND
 √ GCS credentials:  FOUND
 √ Initializing Google Earth Engine:  DONE!
 √ Earth Engine user: users/mtd25 
------------------------------------------------------------------------------------------------------------------------------ 
```

**Comment by alanfalcaothe** [comment]
Hello everyone. I am new to programming in R and am trying to execute a R code where I access the google drive and the google earth engine. However, two situations are happening: first on my personal laptop at home I run the code and it works perfectly and doesn't even open a browser to ask for access permission.
While in the second case, when I use the remote desktop connection and access the company's computer, the code cannot get google credentials.

What could it be? will it be related to remote access or to the package version? follows data below:

---
In my personal laptop:

```r
> ## Initialize GEE ----
> ee_Initialize(email = gee_email, drive = TRUE)
-- rgee 1.0.9 ------------------------------------------------------------ earthengine-api 0.1.248 --
 √ email: my.email@colaborator.company.br 
 √ Google Drive credentials:  FOUND
 √ Initializing Google Earth Engine:  DONE!
 √ Earth Engine user: users/rcode
-----------------------------------------------------------------------------------------------------
```
The same code in company's computer by remote desktop connection:

```r
> ## Initialize GEE ----
> ee_Initialize(email = gee_email, drive = TRUE)
-- rgee 1.0.9 ------------------------------------------------------------------------------- earthengine-api 0.1.263 -- 
 √ email: my.email@colaborator.company.br 
 √ Google Drive credentials:Erro: Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.
  * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html
```
after of execute the commands:

>options (gargle_quiet = FALSE)
>googledrive :: drive_auth ("my.email@colaborator.company.br ")

```r
> trying `token_fetch()`
> trying `credentials_service_account()`
> Error caught by `token_fetch()`:
  Argument 'txt' must be a JSON string, URL or file.
> trying `credentials_app_default()`
> trying `credentials_gce()`
> trying `credentials_byo_oauth()`
> Error caught by `token_fetch()`:
  inherits(token, "Token2.0") is not TRUE
> trying `credentials_user_oauth2()`
> Gargle2.0 initialize
> attempt to access internal gargle data from: googledrive
> adding 'userinfo.email' scope
> loading token from the cache
> no matching token in the cache
> initiating new token
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
> Error caught by `token_fetch()`:
  Failed to connect to accounts.google.com port 443: Timed out
Erro: Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.
  * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html
 ```
---
I know it is very similar to this error, so I tried to execute the commands:
>googledrive::drive_auth(
  email = c("my.email@colaborator.company.br "),
  cache = "any_path"
)

and the answer was again: 
```r
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Erro: Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.
  * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html
```

I tried too:
>library(rgee)
ee_clean_credentials()
ee_Initialize("my.email@colaborator.company.br ")

The commandoes execute, but the problem remains the same. I saw that friend MichaelTD83 downloaded a credential, however it is very complicated to me do and as I showed in the first example on my personal computer work fine and never had to download anything to use. Never gave credentials error. 

I'm sorry about the enormous text and for my limited knowledge, but I wanted to show the options that I already tested and that didn’t work to try to help delimit the problem.

**Comment by MichaelTD83** [comment]
@alanfalcaothe I am pretty new at this myself but if you tried the above and it didn't work, then if you haven't already I would suggest would be to update R, Rstudio, and all of your packages on both computers and then try it again. Part of my problem was that I had different versions of several applications and packages on my two computers.

**Comment by jpmeteor** [comment]
Hello everyone, the problem I have after this script: `#https://cran.r-project.org/web/packages/rgee/vignettes/rgee01.html#6_Installation


library(rgee)
#ee_install(py_env = "rgee")

library(rgee)
library(googleCloudStorageR)
#ee_reattach() # reattach ee as a reserve word
# Initialize just Earth Engine


ee_clean_credentials("pozotjesus@gmail.com")
ee_Initialize(user = 'pozotjesus@gmail.com', drive = TRUE, gcs = TRUE)
` 
I get this :
`> ee_Initialize(user = 'pozotjesus@gmail.com', drive = TRUE, gcs = TRUE)
── rgee 1.1.5 ─────────────────────────────── earthengine-api 0.1.364 ── 
 ✔ user: pozotjesus@gmail.com 
 ✔ Google Drive credentials:  FOUND
 ✔ GCS credentials: NOT FOUND
 ✔ Initializing Google Earth Engine:Fetching credentials using gcloud
Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
Exception: gcloud failed. Please check for any errors above.
*Possible fixes: If you loaded a page with a "redirect_uri_mismatch" error, run earthengine authenticate with the --quiet flag; if the error page says "invalid_request", be sure to run the entire gcloud auth command that is shown.
More information: https://developers.google.com/earth-engine/guides/python_install

Run `reticulate::py_last_error()` for details.`  What's happening ?

**Comment by jpmeteor** [comment]
Hi everyone, this is my code:

#https://cran.r-project.org/web/packages/rgee/vignettes/rgee01.html#6_Installation


library(rgee)
#ee_install(py_env = "rgee")

library(rgee)
library(googleCloudStorageR)
#ee_reattach() # reattach ee as a reserve word
# Initialize just Earth Engine


ee_clean_credentials("pozotjesus@gmail.com")
ee_Initialize(user = 'pozotjesus@gmail.com', drive = TRUE, gcs = TRUE)


. . . and this are my results, whats happening? :

> ee_Initialize(user = 'pozotjesus@gmail.com', drive = TRUE, gcs = TRUE)
── rgee 1.1.5 ─────────────────────────────── earthengine-api 0.1.364 ── 
 ✔ user: pozotjesus@gmail.com 
 ✔ Google Drive credentials:  FOUND
 ✔ GCS credentials: NOT FOUND
 ✔ Initializing Google Earth Engine:Fetching credentials using gcloud
Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
Exception: gcloud failed. Please check for any errors above.
*Possible fixes: If you loaded a page with a "redirect_uri_mismatch" error, run earthengine authenticate with the --quiet flag; if the error page says "invalid_request", be sure to run the entire gcloud auth command that is shown.
More information: https://developers.google.com/earth-engine/guides/python_install

Run `reticulate::py_last_error()` for details.

**Comment by marciolegal** [comment]
I had this issue. I downloaded the ee_Initialize code and removed the parameter opt_url=opt_url from ee$Initialize(...) to make it work. It looks like it doesnt exist anymore in the version of the stuff I'm using, so was being caught by the TryCatch block, givning an wrong error message. It had nothing to do authentication.
