### ISSUE TITLE
rgee functions don't exist anymore????

### ISSUE THREAD

**Issue by RussellGrayxd** [r-spatial/rgee#144]
* rgee version:1.0.8
* R version: 4.0.3
* Operating System: Windows 10

### Description

Trying to run functions from several different tutorials. I expected them to work.

### What I Did
They did not work. All of them say the functions are not part of the rgee namespace. There is no indication anywhere that they were deprecated

```
ee_search_dataset() %>%
  ee_search_title("mod13") %>%
  ee_search_title("1km") %>%
  ee_search_display()                 

Error in ee_search_display(.) : 
  could not find function "ee_search_display"
```

**Comment by LBautistaB13** [comment]
Hi @RussellGrayxd we will encourage you to use `Dataset` module. We believe it is easier to use.

```r
library(rgee)

# Install rgee v.1.0.9
remotes::install_github("r-spatial/rgee")

ee_Initialize()

# ImageCollection
ee$ImageCollection$Dataset$CAS_IGSNRR_PML_V2 %>% 
  ee_utils_dataset_display()

# Image
ee$Image$Dataset$CGIAR_SRTM90_V4 %>% 
  ee_utils_dataset_display()

# FeatureCollection
ee$FeatureCollection$Dataset$FAO_GAUL_2015_level0 %>% 
  ee_utils_dataset_display()
```

**Comment by RussellGrayxd** [comment]
Thanks for letting me know. However, if the former functions were deprecated it would be helpful if you could make that note on the rgee pages with the updates, I searched for any mention of function deprecation and there was nothing. The vast majority of tutorials use this chunk of code (many of which are on the rgee csaybar website) so they could be very confusing to those who don't know these functions don't exist at all anymore.

**Comment by LBautistaB13** [comment]
![image](https://user-images.githubusercontent.com/54723897/113135693-b3eb0780-9222-11eb-8041-72d04f28315d.png)

**Comment by csaybar** [comment]
Hi @RussellGrayxd deeply sorry for the inconveniences, we are planning to upgrade the documentation soon, we had to delete the `ee_search` module because it needs to create constantly a file on their system and  this is against [CRAN's policies](https://cran.r-project.org/web/packages/policies.html). 

I will close this issue but let us know if you have some ideas for improving the EarthEngine Catalog user experience from R.
