### ISSUE TITLE
numpy not installed error

### ISSUE THREAD

**Issue by kevinhawkshaw** [r-spatial/rgee#151]
* rgee version: 1.09
* R version: 4.0.3
* Operating System: Windows 10

#### At submit an issue, please attached the following information of your `rgee` session:

- [ ] You have the Python API installed (from terminal):
```
earthengine -h
```

- [ ] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
```
FALSE

- [ ] You can run a simple EE command from R: 

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

Error in ee_connect_to_py(path = ee_current_version, n = 5) : 
  The current Python PATH: C:/Users/kevin_000/AppData/Local/r-miniconda/envs/rgee/python.exe
does not have the Python package "earthengine-api" installed. Are you restarted/terminated.
your R session after install miniconda or run ee_install()?
If no do it, please try again:
> ee_install(): To create and set a Python environment with all rgee dependencies.
> ee_install_set_pyenv(): To set a specific Python environment.

# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())
``` 

Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()
```
python:         C:/Users/kevin_000/AppData/Local/r-miniconda/envs/rgee/python.exe
libpython:      C:/Users/kevin_000/AppData/Local/r-miniconda/envs/rgee/python39.dll
pythonhome:     C:/Users/kevin_000/AppData/Local/r-miniconda/envs/rgee
version:        3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 04:59:43) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]
ee:             C:\Users\KEVIN_~1\AppData\Local\R-MINI~1\envs\rgee\lib\site-packages\ee\__init__.p

NOTE: Python version was forced by RETICULATE_PYTHON

### Description

Last August I was running rgee with no issues whatsoever. Today I went back to my code to extract data for a new analysis, and all of a sudden I got this when using ee_check():

ee_check()
(*)  Python version
√ [Ok] C:/Users/kevin_000/AppData/Local/r-miniconda/envs/rgee/python.exe v3.9
√ [X] numpy not installed

And obviously the package does not work for me anymore.

### What I Did
I have uninstalled and reinstalled Anaconda, Miniconda, rgee, reticulate many times over in all kinds of different orders (including uninstalling everything and then just reinstalling rgee and allowing it to set everything up). No luck. I cannot get rid of the "numpy not installed" error. And ee_initialize() says I don't have earthengine-api installed either. Both apparently install successfully if I call ee_install(), but it does not prevent the error. 

I simply do not know what else to try at this point, but I really found the package useful earlier, so I'm hoping I can eventually get it installed and useable again. Any advice?

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by csaybar** [comment]
Hi @kevinhawkshaw, we are sorry that you have problems installing `rgee`.

It seems that your conda env does not have installed `numpy`. Therefore no just `rgee` but also `reticulate` should not work.
Can you run the code below and copy the results to be sure of this?

```r
library(reticulate)

use_python("C:/Users/kevin_000/AppData/Local/r-miniconda/envs/rgee/python.exe")
np <- import("numpy") # Is there and error here?

reticulate::py_discover_config()

py_install("numpy") #  Is there and error here?

# Terminate your R session!, sometimes in windows restart R is not enough
```

**Comment by kevinhawkshaw** [comment]
Hi there, thanks for your help. Here's what I get:

`> library(reticulate)
> 
> use_python("C:/Users/kevin_000/AppData/Local/r-miniconda/envs/rgee/python.exe")
> np <- import("numpy") # Is there and error here?
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'version'

Detailed traceback:
  File "C:\Users\kevin_000\Documents\R\win-library\4.0\reticulate\python\rpytools\loader.py", line 39, in _import_hook
    module = _import(
  File "C:\Python27\ArcGIS10.2\Lib\site-packages\numpy\__init__.py", line 128, in <module>
    from version import git_revision as __git_revision__
  File "C:\Users\kevin_000\Documents\R\win-library\4.0\reticulate\python\rpytools\loader.py", line 39, in _import_hook
    module = _import(
> 
> reticulate::py_discover_config()
python:         C:/Users/kevin_000/AppData/Local/Programs/Python/Python39/python.exe
libpython:      C:/Users/kevin_000/AppData/Local/Programs/Python/Python39/python39.dll
pythonhome:     C:/Users/kevin_000/AppData/Local/Programs/Python/Python39
version:        3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]

NOTE: Python version was forced by use_python function
> 
> py_install("numpy") #  Is there and error here?
Error: could not find a Python environment for C:/Users/kevin_000/AppData/Local/Programs/Python/Python39/python.exe`

**Comment by csaybar** [comment]
It seems that your ArcGIS Python2 has conflicts with your conda rgee ENV (numpy). This problem should occur also in Python, not just in R. https://gis.stackexchange.com/questions/609/will-arcgis-desktop-support-latest-python-2-x-or-python-3-x-versions#697

@ryali93 any idea to solve this? You mention me this problem one time. How can I call python Env in Windows?

```r
use_python("C:/Users/kevin_000/AppData/Local/r-miniconda/envs/rgee/python.exe")  
```

or 

```r
use_python("C:/Users/kevin_000/AppData/Local/r-miniconda/envs/rgee")  
```

**Comment by ryali93** [comment]
Hi @kevinhawkshaw ,
It is possible that your problem is because you have more than one python installed and reticulate is calling another python by default. I recommend that, first of all, delete environment variables related to python, especially the Rstudio one "C:\Users******Documents.Renviron".
Otherwise, also delete the r-miniconda folder, including all created envs, and try to install again.

**Comment by kevinhawkshaw** [comment]
Hi @ryali93 ,
I did as you said, deleting the environmental variables and then reinstalling rgee. Here's the output 

> ee_install()
------------------------------------- Python configuration used to create rgee --
python:         C:/Users/kevin_000/AppData/Local/Programs/Python/Python39/python.exe
libpython:      C:/Users/kevin_000/AppData/Local/Programs/Python/Python39/python39.dll
pythonhome:     C:/Users/kevin_000/AppData/Local/Programs/Python/Python39
version:        3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]
ee:             [NOT FOUND]

NOTE: Python version was forced by use_python function
--------------------------------------------------------------------------------- 
1. Removing the previous Python Environment (rgee), if it exists ...

2. Creating a Python Environment (rgee)
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\kevin_000\.conda\envs\rgee

  added / updated specs:
    - python


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.12.5  |       h5b45459_0         173 KB  conda-forge
    certifi-2020.12.5          |   py39hcbf5309_1         144 KB  conda-forge
    openssl-1.1.1k             |       h8ffe710_0         5.7 MB  conda-forge
    pip-21.1.1                 |     pyhd8ed1ab_0         1.1 MB  conda-forge
    python-3.9.2               |h7840368_0_cpython        19.9 MB  conda-forge
    python_abi-3.9             |           1_cp39           4 KB  conda-forge
    setuptools-49.6.0          |   py39hcbf5309_3         954 KB  conda-forge
    sqlite-3.35.5              |       h8ffe710_0         1.2 MB  conda-forge
    tzdata-2021a               |       he74cb21_0         121 KB  conda-forge
    vc-14.2                    |       hb210afc_4          13 KB  conda-forge
    vs2015_runtime-14.28.29325 |       h5e1d092_4         2.3 MB  conda-forge
    wheel-0.36.2               |     pyhd3deb0d_0          31 KB  conda-forge
    wincertstore-0.2           |py39hcbf5309_1006          15 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        31.6 MB

The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/win-64::ca-certificates-2020.12.5-h5b45459_0
  certifi            conda-forge/win-64::certifi-2020.12.5-py39hcbf5309_1
  openssl            conda-forge/win-64::openssl-1.1.1k-h8ffe710_0
  pip                conda-forge/noarch::pip-21.1.1-pyhd8ed1ab_0
  python             conda-forge/win-64::python-3.9.2-h7840368_0_cpython
  python_abi         conda-forge/win-64::python_abi-3.9-1_cp39
  setuptools         conda-forge/win-64::setuptools-49.6.0-py39hcbf5309_3
  sqlite             conda-forge/win-64::sqlite-3.35.5-h8ffe710_0
  tzdata             conda-forge/noarch::tzdata-2021a-he74cb21_0
  vc                 conda-forge/win-64::vc-14.2-hb210afc_4
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.28.29325-h5e1d092_4
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  wincertstore       conda-forge/win-64::wincertstore-0.2-py39hcbf5309_1006



Downloading and Extracting Packages
wheel-0.36.2         | 31 KB     | ########## | 100% 
python-3.9.2         | 19.9 MB   | ########## | 100% 
ca-certificates-2020 | 173 KB    | ########## | 100% 
setuptools-49.6.0    | 954 KB    | ########## | 100% 
pip-21.1.1           | 1.1 MB    | ########## | 100% 
sqlite-3.35.5        | 1.2 MB    | ########## | 100% 
tzdata-2021a         | 121 KB    | ########## | 100% 
openssl-1.1.1k       | 5.7 MB    | ########## | 100% 
certifi-2020.12.5    | 144 KB    | ########## | 100% 
vs2015_runtime-14.28 | 2.3 MB    | ########## | 100% 
wincertstore-0.2     | 15 KB     | ########## | 100% 
python_abi-3.9       | 4 KB      | ########## | 100% 
vc-14.2              | 13 KB     | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base -c defaults conda


#
# To activate this environment, use
#
#     $ conda activate rgee
#
# To deactivate an active environment, use
#
#     $ conda deactivate


rgee::ee_install want to store the environment variables: EARTHENGINE_PYTHON 
and EARTHENGINE_ENV in your .Renviron file to use the Python path:
C:\Users\kevin_000\.conda\envs\rgee\python.exe in future sessions.
Would you like to continues? [Y/n]:Y

3. The Environment Variables: 'EARTHENGINE_PYTHON=C:\Users\kevin_000\.conda\envs\rgee\python.exe' and 'EARTHENGINE_ENV=rgee'
were saved in the .Renviron (C:\Users\kevin_000\Documents/.Renviron) file. Remember that you
could remove EARTHENGINE_PYTHON and EARTHENGINE_ENV using rgee::ee_clean_pyenv().

4. Installing the earthengine-api. Running: 
reticulate::py_install(packages = 'earthengine-api', envname = 'C:/Users/kevin_000/.conda/envs/rgee')

No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]: Y
* Downloading "https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe" ...
trying URL 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe'
Content type 'application/octet-stream' length 59801432 bytes (57.0 MB)
downloaded 57.0 MB

* Installing Miniconda -- please wait a moment ...
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\KEVIN_~1\AppData\Local\R-MINI~1

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2021.4.13  |       haa95532_1         115 KB
    certifi-2020.12.5          |   py38haa95532_0         141 KB
    cffi-1.14.5                |   py38hcd4344a_0         224 KB
    chardet-4.0.0              |py38haa95532_1003         211 KB
    conda-4.10.1               |   py38haa95532_1         2.9 MB
    conda-package-handling-1.7.3|   py38h8cc25b3_1         721 KB
    cryptography-3.4.7         |   py38h71e12ea_0         643 KB
    idna-2.10                  |     pyhd3eb1b0_0          52 KB
    openssl-1.1.1k             |       h2bbff1b_0         4.8 MB
    pip-21.0.1                 |   py38haa95532_0         1.8 MB
    pyopenssl-20.0.1           |     pyhd3eb1b0_1          49 KB
    requests-2.25.1            |     pyhd3eb1b0_0          52 KB
    ruamel_yaml-0.15.100       |   py38h2bbff1b_0         273 KB
    setuptools-52.0.0          |   py38haa95532_0         726 KB
    sqlite-3.35.4              |       h2bbff1b_0         761 KB
    tqdm-4.59.0                |     pyhd3eb1b0_1          93 KB
    urllib3-1.26.4             |     pyhd3eb1b0_0         105 KB
    vc-14.2                    |       h21ff451_1           8 KB
    vs2015_runtime-14.27.29016 |       h5e58377_2        1007 KB
    wheel-0.36.2               |     pyhd3eb1b0_0          33 KB
    ------------------------------------------------------------
                                           Total:        14.6 MB

The following packages will be REMOVED:

  zlib-1.2.11-h62dcd97_4

The following packages will be UPDATED:

  ca-certificates                              2020.10.14-0 --> 2021.4.13-haa95532_1
  certifi            pkgs/main/noarch::certifi-2020.6.20-p~ --> pkgs/main/win-64::certifi-2020.12.5-py38haa95532_0
  cffi                                1.14.3-py38hcd4344a_2 --> 1.14.5-py38hcd4344a_0
  chardet                           3.0.4-py38haa95532_1003 --> 4.0.0-py38haa95532_1003
  conda                                4.9.2-py38haa95532_0 --> 4.10.1-py38haa95532_1
  conda-package-han~                   1.7.2-py38h76e460a_0 --> 1.7.3-py38h8cc25b3_1
  cryptography                         3.2.1-py38hcd4344a_1 --> 3.4.7-py38h71e12ea_0
  openssl                                 1.1.1h-he774522_0 --> 1.1.1k-h2bbff1b_0
  pip                                 20.2.4-py38haa95532_0 --> 21.0.1-py38haa95532_0
  pyopenssl                             19.1.0-pyhd3eb1b0_1 --> 20.0.1-pyhd3eb1b0_1
  requests                                      2.24.0-py_0 --> 2.25.1-pyhd3eb1b0_0
  ruamel_yaml                        0.15.87-py38he774522_1 --> 0.15.100-py38h2bbff1b_0
  setuptools                          50.3.1-py38haa95532_1 --> 52.0.0-py38haa95532_0
  sqlite                                  3.33.0-h2a8f88b_0 --> 3.35.4-h2bbff1b_0
  tqdm                                  4.51.0-pyhd3eb1b0_0 --> 4.59.0-pyhd3eb1b0_1
  urllib3                                      1.25.11-py_0 --> 1.26.4-pyhd3eb1b0_0
  vc                                        14.1-h0510ff6_4 --> 14.2-h21ff451_1
  vs2015_runtime                     14.16.27012-hf0eaf9b_3 --> 14.27.29016-h5e58377_2
  wheel                                 0.35.1-pyhd3eb1b0_0 --> 0.36.2-pyhd3eb1b0_0

The following packages will be DOWNGRADED:

  idna                                            2.10-py_0 --> 2.10-pyhd3eb1b0_0



Downloading and Extracting Packages
chardet-4.0.0        | 211 KB    | ########## | 100% 
conda-4.10.1         | 2.9 MB    | ########## | 100% 
ruamel_yaml-0.15.100 | 273 KB    | ########## | 100% 
sqlite-3.35.4        | 761 KB    | ########## | 100% 
tqdm-4.59.0          | 93 KB     | ########## | 100% 
pip-21.0.1           | 1.8 MB    | ########## | 100% 
vc-14.2              | 8 KB      | ########## | 100% 
requests-2.25.1      | 52 KB     | ########## | 100% 
certifi-2020.12.5    | 141 KB    | ########## | 100% 
ca-certificates-2021 | 115 KB    | ########## | 100% 
cffi-1.14.5          | 224 KB    | ########## | 100% 
cryptography-3.4.7   | 643 KB    | ########## | 100% 
wheel-0.36.2         | 33 KB     | ########## | 100% 
idna-2.10            | 52 KB     | ########## | 100% 
setuptools-52.0.0    | 726 KB    | ########## | 100% 
conda-package-handli | 721 KB    | ########## | 100% 
pyopenssl-20.0.1     | 49 KB     | ########## | 100% 
vs2015_runtime-14.27 | 1007 KB   | ########## | 100% 
urllib3-1.26.4       | 105 KB    | ########## | 100% 
openssl-1.1.1k       | 4.8 MB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\KEVIN_~1\AppData\Local\R-MINI~1\envs\r-reticulate

  added / updated specs:
    - numpy
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2020.12.5          |   py36ha15d459_1         144 KB  conda-forge
    intel-openmp-2021.2.0      |     h57928b3_616         2.6 MB  conda-forge
    libblas-3.9.0              |            8_mkl         3.9 MB  conda-forge
    libcblas-3.9.0             |            8_mkl         3.9 MB  conda-forge
    liblapack-3.9.0            |            8_mkl         3.9 MB  conda-forge
    mkl-2020.4                 |     hb70f87d_311       172.4 MB  conda-forge
    numpy-1.19.5               |   py36hd1b969e_1         4.9 MB  conda-forge
    python-3.6.13              |h39d44d4_0_cpython        19.0 MB  conda-forge
    python_abi-3.6             |          1_cp36m           4 KB  conda-forge
    setuptools-49.6.0          |   py36ha15d459_3         921 KB  conda-forge
    wincertstore-0.2           |py36ha15d459_1006          15 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       211.6 MB

The following NEW packages will be INSTALLED:

  certifi            conda-forge/win-64::certifi-2020.12.5-py36ha15d459_1
  intel-openmp       conda-forge/win-64::intel-openmp-2021.2.0-h57928b3_616
  libblas            conda-forge/win-64::libblas-3.9.0-8_mkl
  libcblas           conda-forge/win-64::libcblas-3.9.0-8_mkl
  liblapack          conda-forge/win-64::liblapack-3.9.0-8_mkl
  mkl                conda-forge/win-64::mkl-2020.4-hb70f87d_311
  numpy              conda-forge/win-64::numpy-1.19.5-py36hd1b969e_1
  pip                conda-forge/noarch::pip-21.1.1-pyhd8ed1ab_0
  python             conda-forge/win-64::python-3.6.13-h39d44d4_0_cpython
  python_abi         conda-forge/win-64::python_abi-3.6-1_cp36m
  setuptools         conda-forge/win-64::setuptools-49.6.0-py36ha15d459_3
  vc                 conda-forge/win-64::vc-14.2-hb210afc_4
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.28.29325-h5e1d092_4
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  wincertstore       conda-forge/win-64::wincertstore-0.2-py36ha15d459_1006




Downloading and Extracting Packages
brotlipy-0.7.0       | 369 KB    | ########## | 100% 
libcrc32c-1.1.1      | 25 KB     | ########## | 100% 
six-1.15.0           | 14 KB     | ########## | 100% 
simplejson-3.17.2    | 103 KB    | ########## | 100% 
urllib3-1.26.4       | 99 KB     | ########## | 100% 
typing_extensions-3. | 25 KB     | ########## | 100% 
zlib-1.2.11          | 126 KB    | ########## | 100% 
cachetools-4.2.2     | 12 KB     | ########## | 100% 
packaging-20.9       | 35 KB     | ########## | 100% 
google-auth-httplib2 | 13 KB     | ########## | 100% 
google-api-python-cl | 48 KB     | ########## | 100% 
google-auth-1.30.0   | 77 KB     | ########## | 100% 
typing-extensions-3. | 8 KB      | ########## | 100% 
async-timeout-3.0.1  | 11 KB     | ########## | 100% 
google-cloud-storage | 51 KB     | ########## | 100% 
aiohttp-3.7.4        | 600 KB    | ########## | 100% 
cffi-1.14.5          | 228 KB    | ########## | 100% 
google-crc32c-1.1.2  | 26 KB     | ########## | 100% 
numpy-1.20.2         | 5.3 MB    | ########## | 100% 
pysocks-1.7.1        | 28 KB     | ########## | 100% 
multidict-5.1.0      | 63 KB     | ########## | 100% 
google-cloud-core-1. | 26 KB     | ########## | 100% 
google-resumable-med | 40 KB     | ########## | 100% 
google-api-core-1.26 | 59 KB     | ########## | 100% 
httplib2-0.19.1      | 94 KB     | ########## | 100% 
requests-2.25.1      | 51 KB     | ########## | 100% 
pyopenssl-20.0.1     | 48 KB     | ########## | 100% 
googleapis-common-pr | 128 KB    | ########## | 100% 
pycparser-2.20       | 94 KB     | ########## | 100% 
uritemplate-3.0.1    | 16 KB     | ########## | 100% 
pyasn1-0.4.8         | 53 KB     | ########## | 100% 
pytz-2021.1          | 239 KB    | ########## | 100% 
libprotobuf-3.15.8   | 2.3 MB    | ########## | 100% 
rsa-4.7.2            | 28 KB     | ########## | 100% 
chardet-4.0.0        | 218 KB    | ########## | 100% 
pyasn1-modules-0.2.7 | 60 KB     | ########## | 100% 
win_inet_pton-1.1.0  | 8 KB      | ########## | 100% 
earthengine-api-0.1. | 129 KB    | ########## | 100% 
protobuf-3.15.8      | 262 KB    | ########## | 100% 
pyparsing-2.4.7      | 60 KB     | ########## | 100% 
cryptography-3.4.7   | 706 KB    | ########## | 100% 
idna-2.10            | 52 KB     | ########## | 100% 
yarl-1.6.3           | 135 KB    | ########## | 100% 
future-0.18.2        | 733 KB    | ########## | 100% 
attrs-20.3.0         | 41 KB     | ########## | 100% 
grpcio-1.37.1        | 2.0 MB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

Well done! rgee was successfully set up in your system.
You need restart R to see changes. After doing that, we recommend
run ee_check() to perform a full check of all non-R rgee dependencies.
Do you want restart your R session? 

1: yes
2: no

Selection: yes

###################################################
###################################################

I get a warning about there being a new version of conda available, but other than that the installation process seems to work. 

So I restart my R session, load rgee and run ee_check(), but once again I get:
(*)  Python version
√ [Ok] C:/Users/kevin_000/AppData/Local/Programs/Python/Python39/python.exe v3.9
√ [X] numpy not installed

So I rerun @csaybar 's recommended reticulate check
> library(reticulate)
> 
> use_python("C:/Users/kevin_000/AppData/Local/r-miniconda/envs/rgee/python.exe")
> np <- import("numpy") # Is there and error here?
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'version'

Detailed traceback:
  File "C:\Users\kevin_000\Documents\R\win-library\4.0\reticulate\python\rpytools\loader.py", line 39, in _import_hook
    module = _import(
  File "C:\Python27\ArcGIS10.2\Lib\site-packages\numpy\__init__.py", line 128, in <module>
    from version import git_revision as __git_revision__
  File "C:\Users\kevin_000\Documents\R\win-library\4.0\reticulate\python\rpytools\loader.py", line 39, in _import_hook
    module = _import(
> 
> reticulate::py_discover_config()
python:         C:/Users/kevin_000/AppData/Local/Programs/Python/Python39/python.exe
libpython:      C:/Users/kevin_000/AppData/Local/Programs/Python/Python39/python39.dll
pythonhome:     C:/Users/kevin_000/AppData/Local/Programs/Python/Python39
version:        3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]

NOTE: Python version was forced by use_python function
> 
> py_install("numpy") #  Is there and error here?
Error: could not find a Python environment for C:/Users/kevin_000/AppData/Local/Programs/Python/Python39/python.exe

#############################################################
#############################################################

so same issue

**Comment by kevinhawkshaw** [comment]
I also tried using both versions of use_python() that @csaybar mentioned prior to calling ee_check(), but that does not work. Still "numpy not installed"

**Comment by csaybar** [comment]
@kevinhawkshaw Did you try removing the ArcGis Python from `%PATH%` variable? 

https://github.com/r-spatial/rgee/issues/56#issuecomment-621948126

**Comment by kevinhawkshaw** [comment]
there is no reference to the ArcGIS python in my Path. Only Python 3.9, which is what I want to use. 

here are the contents of my .Renviron 

EARTHENGINE_PYTHON="C:\Users\kevin_000\.conda\envs\rgee\python.exe"
EARTHENGINE_ENV="rgee"

numpy does exist within that rgee folder, as does earthengine-api, i.e., the rgee installer seems to have worked, i just can't access it. 

i tried fully removing the ArcGIS python folder, and then tried rerunning your reticulate check. I still can't import numpy, but the output is different now:

> library(reticulate)
> 
> use_python("C:/Users/kevin_000/.conda/envs/rgee/python.exe")
> np <- import("numpy") # Is there and error here?
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'numpy'

Detailed traceback:
  File "C:\Users\kevin_000\Documents\R\win-library\4.0\reticulate\python\rpytools\loader.py", line 39, in _import_hook
    module = _import(
> 
> reticulate::py_discover_config()
python:         C:/Users/kevin_000/AppData/Local/Programs/Python/Python39/python.exe
libpython:      C:/Users/kevin_000/AppData/Local/Programs/Python/Python39/python39.dll
pythonhome:     C:/Users/kevin_000/AppData/Local/Programs/Python/Python39
version:        3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]

NOTE: Python version was forced by use_python function
> 
> py_install("numpy") 
Error: could not find a Python environment for C:/Users/kevin_000/AppData/Local/Programs/Python/Python39/python.exe

**Comment by csaybar** [comment]
hi @kevinhawkshaw!. Can you share your `PATH`, it will help us to try to reproduce the error.

```r
Sys.getenv("PATH")
```

Are you sure if you deleted ARCGIS Python 2.7 still not working?

```r
library(rgee)
Sys.setenv("PATH"="PUT_HERE_YOUR_NEW_PATH_WITHOUT_ARCGIS_PYTHON2.7")

ee_Initialize()
```

**Comment by ryali93** [comment]
Have you installed python 3.9 by conda?  Remove all of conda from your environment variables and try removing the .Renviron file as well.

**Comment by kevinhawkshaw** [comment]
> Sys.getenv("PATH")
[1] "C:\\Program Files\\R\\R-4.0.5\\bin\\x64;C:\\ProgramData\\Oracle\\Java\\javapath;c:\\Rtools\\bin;c:\\Rtools\\gcc-4.6.3\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Lenovo\\Fingerprint Manager Pro\\;C:\\ProgramData\\Lenovo\\ReadyApps;C:\\Program Files (x86)\\Intel\\OpenCL SDK\\3.0\\bin\\x86;C:\\Program Files (x86)\\Intel\\OpenCL SDK\\3.0\\bin\\x64;C:\\Program Files (x86)\\Common Files\\lenovo\\easyplussdk\\bin;C:\\Program Files (x86)\\Windows Live\\Shared;C:\\Program Files\\R\\R-3.2.2\\bin\\x64;C:\\Program Files\\gs\\gs9.25\\lib;C:\\Program Files\\gs\\gs9.25\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64\\;C:\\Program Files\\Git\\bin;C:\\rtools40\\usr\\bin;C:\\rtools40\\mingw64;C:\\rtools40\\mingw32;C:\\Users\\kevin_000\\Documents\\.cmdstanr\\cmdstan-2.26.0\\stan\\lib\\stan_math\\lib\\tbb;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Users\\kevin_000\\miniconda3\\condabin;C:\\Users\\kevin_000\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\;C:\\Users\\kevin_000\\AppData\\Local\\Programs\\MiKTeX\\miktex\\bin\\x64\\;C:\\Users\\kevin_000\\AppData\\Local\\Microsoft\\WindowsApps;"

**Comment by csaybar** [comment]
Hi @kevinhawkshaw I give up let me know when you have time to a zoom call, maybe we can solve the problem together csaybar@gmail.com

**Comment by kevinhawkshaw** [comment]
just to follow up on this complicated story, it seems like I have solved my problem. The issue does appear to be that rgee/reticulate was picking up the python installation used for ArcGIS. While that version was not in my PATH variable, it was set as my PYTHONPATH. Changing PYTHONPATH to "C:\Users\kevin_000\AppData\Local\r-miniconda\envs\rgee" partially solved my problem. 

When I then ran ee_check(), it found numpy, but not earthengine-api. That led me to this issue thread https://github.com/r-spatial/rgee/issues/91, and after following the steps, the issue was solved. Strangely, as for that user, running ee_check() before ee_Initialize() at the start of my R session causes a problem (earthengine-api not found). If I run ee_Initialize() first, there are no issues.

Hopefully this can help other users, and it seems something is still off with ee_check()

**Comment by csaybar** [comment]
Hi @kevinhawkshaw thank you so much for have the time to explain to us better the problem. 
I think I know why `ee_check` generated the problem:

```r
ee_check <- function(user = NULL, quiet = FALSE) {
  ee_check_python(quiet = quiet)
  ee_check_python_packages(quiet = quiet)
  if (!is.null(user)) {
    ee_check_credentials(quiet = quiet)
  }
  invisible(TRUE)
}

ee_check_python <- function(quiet = FALSE) {
  python_test <- py_available(initialize = TRUE) # HERE IS THE PROBLEM
  if (python_test) {
    py_version <- as.numeric(py_discover_config()[["version"]])
    if (!quiet) {
      cat_line(
        blue(symbol[["circle_filled"]]),
        blue("  Python version\n"),
        green(symbol[["tick"]], "[Ok]"),
        blue(
          "",
          py_discover_config()[["python"]],
          sprintf("v%s", py_version)
        )
      )
    }
  } else {
    stop(
      "Unable to find a Python version, you will need to fix before run ",
      "rgee::ee_Initialize(). For more details run reticulate::py_available()"
    )
  }
  if (py_version < 3.5) stop("rgee needs Python 3.5 >=")
  return(invisible(TRUE))
}
```

It seems your reticulate is calling a different Python environment by default. Defining EARTHENGINE_PYTHON or RETICULATE_PYTHON in a local or global `.Renviron` should solve the problem.  I will force `ee_users` to always read the env `EARTHENGINE_PYTHON` if it exists. I think this should solve the problem. Thanks a lot

https://github.com/r-spatial/rgee/blob/ecb3080759e8425ca386a5403f3584dea9c2d9f8/R/ee_Initialize.R#L65
