### ISSUE TITLE
Erro in credentials googledrive and google earth engine.

### ISSUE THREAD

**Issue by alanfalcaothe** [r-spatial/rgee#152]
Hello everyone. I am new to programming in R and am trying to execute an R code where I access google drive and the google earth engine. However, two situations are happening: first on my personal laptop at home I run the code and it works perfectly and doesn't even open a browser to ask for access permission.
While in the second case, when I use the remote desktop connection and access the company's computer, the code cannot get google credentials.

What could it be? will it be related to remote access or to the package version? follows data below:

---
In my personal laptop:

```r
> ## Initialize GEE ----
> ee_Initialize(email = gee_email, drive = TRUE)
-- rgee 1.0.9 ------------------------------------------------------------ earthengine-api 0.1.248 --
 √ email: my.email@colaborator.company.br 
 √ Google Drive credentials:  FOUND
 √ Initializing Google Earth Engine:  DONE!
 √ Earth Engine user: users/rcode
-----------------------------------------------------------------------------------------------------
```
The same code in company's computer by remote desktop connection:

```r
> ## Initialize GEE ----
> ee_Initialize(email = gee_email, drive = TRUE)
-- rgee 1.0.9 ------------------------------------------------------------------------------- earthengine-api 0.1.263 -- 
 √ email: my.email@colaborator.company.br 
 √ Google Drive credentials:Erro: Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.
  * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html
```
after of execute the commands:

>options (gargle_quiet = FALSE)
>googledrive :: drive_auth ("my.email@colaborator.company.br ")

```r
> trying `token_fetch()`
> trying `credentials_service_account()`
> Error caught by `token_fetch()`:
  Argument 'txt' must be a JSON string, URL or file.
> trying `credentials_app_default()`
> trying `credentials_gce()`
> trying `credentials_byo_oauth()`
> Error caught by `token_fetch()`:
  inherits(token, "Token2.0") is not TRUE
> trying `credentials_user_oauth2()`
> Gargle2.0 initialize
> attempt to access internal gargle data from: googledrive
> adding 'userinfo.email' scope
> loading token from the cache
> no matching token in the cache
> initiating new token
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
> Error caught by `token_fetch()`:
  Failed to connect to accounts.google.com port 443: Timed out
Erro: Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.
  * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html
 ```
---
I know it is very similar to this error, so I tried to execute the commands:
>googledrive::drive_auth(
  email = c("my.email@colaborator.company.br "),
  cache = "any_path"
)

and the answer was again: 
```r
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Erro: Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.
  * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html
```

I tried too:
>library(rgee)
ee_clean_credentials()
ee_Initialize("my.email@colaborator.company.br ")

The commandoes execute, but the problem remains the same. I saw that friend MichaelTD83 downloaded a credential, however, it is very complicated for to me do, and as I showed in the first example on my personal computer work fine, and never had to download anything to use. Never gave credentials error. 

I'm sorry about the enormous text and for my limited knowledge, but I wanted to show the options that I already tested and that didn’t work to try to help delimit the problem.

**Comment by csaybar** [comment]
Hi @alanfalcaothe it does not look like a problem with `rgee`. It seems like `googledrive` cannot direct you to a web browser to get the GD credentials via your remote desktop connection (although I'm not sure). 

Are you take a look at this?
https://github.com/tidyverse/googledrive/issues/325

I'm afraid that the only way to solve this problem is to copy manually your credentials in:

```
library(rgee)
oauth_func_path <- system.file("python/ee_utils.py", package = "rgee")
utils_py <- rgee:::ee_source_python(oauth_func_path)
ee_path <- rgee:::ee_utils_py_to_r(utils_py$ee_path())
ee_path
```

**Comment by alanfalcaothe** [comment]
hello, thanks for responding and trying to help.
I am very frustrated about that.

I've looked at questions on googledrive, gargle, tydiverse and rgee. Nobody can solve it.
I installed curl and httr and it didn't work either.

tidyverse/googledrive/issues/328
r-spatial/rgee/issues/152
r-spatial/rgee/issues/139
r-lib/gargle/issues/177
tidyverse/googledrive/issues/276
