### ISSUE TITLE
equivalent for 'require' used in gee

### ISSUE THREAD

**Issue by jimoreira** [r-spatial/rgee#155]
Can i use a code stored in .js file?, in this opportunity on my own repositories.
 
in javascript would look like 
`var LandsatLST = require('users/javiermoreira/lstsofiaermida:modules/Landsat_LST.js')
`
i ask this about an year ago, trying to use ee_manage_asset() and already been answered that was the wrong solution. 
Perhaps there are some new developments to be able to use this .js files. 
many thanks and congratulations on your work, it is really really helpful!

**Comment by csaybar** [comment]
mmm, I think this feature is possible but will not work well for all the cases. Let see what we can do on the next releases :)

**Comment by csaybar** [comment]
@davemlz

**Comment by davemlz** [comment]
I'm on it :wink:

**Comment by ConservationAlpha** [comment]
I am having the same challenge trying to access gee-cdcc-tools , i cent get it to work via RGEE, i need to use
"var utils = require('users/parevalo_bu/gee-ccdc-tools:ccdcUtilities/api')"

**Comment by csaybar** [comment]
@ConservationAlpha  and @jimoreira, we added this feature to [rgeeExtra ](https://github.com/r-earthengine/rgeeExtra).
Feel free to open an issue in rgeeExtra if your Javascript module doesn't work.

**Comment by jimoreira** [comment]
Great! I will give it a try. Thanks

**Comment by csaybar** [comment]
@jimoreira I forgot to mention that rgeeExtra depends on **reticulate 1.22.9000**. Please install as follow:

```r
remotes::install_github("rstudio/reticulate")
remotes::install_github("r-earthengine/rgeeExtra")
```

**Comment by ConservationAlpha** [comment]
Thank you Cesar, much appreciated!
