### ISSUE TITLE
Question  - implementation of landtrendr

### ISSUE THREAD

**Issue by pdbentley** [r-spatial/rgee#161]
Hey, great package. 

Wondering if is is possible to implement the algorithm for landtrendr through rgee at this stage? 

https://developers.google.com/earth-engine/apidocs/ee-algorithms-temporalsegmentation-landtrendr

If so, a simple worked example would be much appreciated. 

Regards, 

Paul

**Comment by jdbcode** [comment]
You should be able to run LandTrendr using rgee. I've started a simple demo of it. I'll share it here when it is complete (likely within a week).

**Comment by jdbcode** [comment]
Sorry, Cesar! Just not enough time.

**Comment by csaybar** [comment]
Hi Justin, no sorry at all! :D ... I'm just putting a bit of order to the issues, to know what it has done, and wasn't. I'm re-coding some poor coding parts and taking back rgeeExtra project :)
