### ISSUE TITLE
 EEException: GeometryConstructors.Rectangle, argument 'coordinates': Invalid type.

### ISSUE THREAD

**Issue by silcordero** [r-spatial/rgee#162]
* rgee version: 1.0.9.999
* R version: R-4.0.5
* Operating System: WIN10

#### At submit an issue, please attached the following information of your `rgee` session:

- [ ] You have the Python API installed (from terminal):

I have Python 3.9.5

- [ ] You can find the credentials file on your system: 

The operation indicated FALSE. However, I have an active GEE account and wile running _ee_Initialize()_, my credentials were verified.

- [ ] You can run a simple EE command from R: 

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())
``` 
Yes, I can.
Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()
```
python:         C:/anaconda/envs/rgee/python.exe
libpython:      C:/anaconda/envs/rgee/python39.dll
pythonhome:     C:/anaconda/envs/rgee
version:        3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:22:33) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/anaconda/envs/rgee/Lib/site-packages/numpy
numpy_version:  1.21.0
ee:             C:\anaconda\envs\rgee\lib\site-packages\ee\__init__.p

NOTE: Python version was forced by use_python function
### Description

Employ the function  ee_as_raster(). However, it is not recognizing my polygon.
I followed this example: https://r-spatial.github.io/rgee/reference/ee_as_raster.html

### What I Did

```
library(rgee)
library(sf)
library(geojsonio)

L1 <- ee$Image("LANDSAT/LC08/C01/T1_SR/LC08_021028_20150624")
NDVI <- L1$normalizedDifference(c("B5", "B4"))

# Converting shapefile (polygon) to an ee.geometry.Geomety object:

bo_sf <- st_read("myshapefile.shp")
bo_geoJ <- sf_geojson(bo_sf)
geo_b <- ee$Geometry(bo_geoJ)
class(geo_b)
#[1] "ee.geometry.Geometry"   "ee.computedobject.ComputedObject" "ee.encodable.Encodable" "python.builtin.object"  

#Clipping image and saving it as a raster

NDVI_ras <- ee_as_raster(
  image = NDVI,
  region = geo_b,
  via = "drive"  
)


##This is the error I get:
##Error in py_call_impl(callable, dots$args, dots$keywords) : 
 ##EEException: GeometryConstructors.Rectangle, argument 'coordinates': Invalid type.
##Expected type: List<Object>.
##Actual type: FeatureCollection.


```
However, if I compare the example's objects class and my imported shapefile, they are the same type:

```
geometry <- ee$Geometry$Rectangle(
  coords = c(-110.8, 44.6, -110.6, 44.7),
  proj = "EPSG:4326",
  geodesic = FALSE
)

```
> class(geometry)==class(geo_b)
[1] TRUE TRUE TRUE TRUE

Therefore, I a bit confused about the source of the error. I will appreciate your help.

**Comment by csaybar** [comment]
Hi @silcordero! Can you try the code below?. Thanks

```r
library(rgee)
library(sf)
library(geojsonio)

L1 <- ee$Image("LANDSAT/LC08/C01/T1_SR/LC08_021028_20150624")
NDVI <- L1$normalizedDifference(c("B5", "B4"))

# Converting shapefile (polygon) to an ee.geometry.Geomety object:

bo_sf <- st_read("myshapefile.shp") %>% sf_as_ee()
geo_b <- bo_sf$geometry()
class(geo_b)
#[1] "ee.geometry.Geometry"   "ee.computedobject.ComputedObject" "ee.encodable.Encodable" "python.builtin.object"  

#Clipping image and saving it as a raster

NDVI_ras <- ee_as_raster(
  image = NDVI,
  region = geo_b,
  via = "drive"  
)

```

**Comment by silcordero** [comment]
> Hi @silcordero! Can you try the code below?. Thanks
> 
> ```r
> library(rgee)
> library(sf)
> library(geojsonio)
> 
> L1 <- ee$Image("LANDSAT/LC08/C01/T1_SR/LC08_021028_20150624")
> NDVI <- L1$normalizedDifference(c("B5", "B4"))
> 
> # Converting shapefile (polygon) to an ee.geometry.Geomety object:
> 
> bo_sf <- st_read("myshapefile.shp") %>% sf_as_ee()
> geo_b <- bo_sf$geometry()
> class(geo_b)
> #[1] "ee.geometry.Geometry"   "ee.computedobject.ComputedObject" "ee.encodable.Encodable" "python.builtin.object"  
> 
> #Clipping image and saving it as a raster
> 
> NDVI_ras <- ee_as_raster(
>   image = NDVI,
>   region = geo_b,
>   via = "drive"  
> )
> ```

**Comment by silcordero** [comment]
Thank you! It worked. I still have a lot to learn but I am enjoying the package
