### ISSUE TITLE
ee_imagecollection_to_local() cannot renew Google drive credentials

### ISSUE THREAD

**Issue by philament** [r-spatial/rgee#163]
I am using `ee_imagecollection_to_local()` to download 3 years of images for a small spatial subset of S2 imagery (a few hundred images total). 

In essence I am running this code (let me know if you need a reproducible example but aoi and date range are probably not relevant for this):
`s2_l1c = ee$ImageCollection('COPERNICUS/S2')$filterDate(start_date,end_date)$filterBounds(aoi)$map(ee$Image$toUint16)
s2files = ee_imagecollection_to_local(s2_l1c, region = aoi, dsn = paste0(l1c_path, 's2_l1c_'), scale = 10)`

After several hours the tasks always stops with the following error message:

![image](https://user-images.githubusercontent.com/31984490/124378932-7d56da00-dcb4-11eb-990a-eb7130a2d7d3.png)

Any idea how to fix this? Is there something I can do with drive_auth() on my end or does this have to be fixed within the `ee_imagecollection_to_local()` function itself? I am running rgee 1.0.9 with earthengine-api 0.1.26 on R 4.0.2 on Windows 10.

**Comment by ambarja** [comment]
Hi @philament  is possible to show me your info about user , for example:
```{js}
> ee_users()
 user               EE      GCS      GD 

 antony.barja8       ✓       x       x
 antonybarja8        ✓       ✓       x
 ndef                ✓       ✓       x
```

**Comment by philament** [comment]
The problem seems to have resolved itself now on my end by re-installing rgee and re-initalizing. I will close the issue for now but might re-open if it occurs again.
