### ISSUE TITLE
Convert feature collection to multiband image

### ISSUE THREAD

**Issue by lopezjuana** [r-spatial/rgee#165]
* rgee version:
* R version:
* Operating System: Windows

I have a feature collection of points with properties and I need to convert those properties to image bands. When I map over the list of properties I get a list of images. How can I transform that list or get directly a multiband image? 

nuevaImagen <- predictoras$map(ee_utils_pyfunc(function(field){
  image_reduced <- setDatos$reduceToImage(list(field), ee$Reducer$first())$reproject(crs = "EPSG:4326", scale = 1000)
  ee$Image(image_reduced)
}))
ee_print(ee$Image(nuevaImagen))

predictoras is a list with the names of the properties. When printing it shows this.

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  EEException: Image.bandNames, argument 'image': Invalid type.
Expected type: Image<unknown bands>.
Actual type: List<Image<[first]>>.
Actual value: [<Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>, <Image<[first]>>]

**Comment by csaybar** [comment]
I think your problem is discussed here: https://gis.stackexchange.com/questions/318754/earth-engine-map-over-list-versus-ee-list. The best  option is to use client-side lists:

```r
library(rgee)
library(sf)

ee_Initialize(drive = TRUE)

# 1. fc points
ee_fc_toy <- data.frame(
  x = sample(10, 10),
  y = sample(10, 10),
  z = sample(10, 10)
) %>% 
  st_as_sf(coords = c("x", "y"), crs = 4326) %>% 
  sf_as_ee()


# Get the desired property
z_property <- ee_fc_toy %>% 
  ee$FeatureCollection$aggregate_array("z") %>% 
  ee$List$getInfo()

# from List to ee.Image
img <- lapply(z_property, function(x) ee$Image(x)) %>% 
  ee$ImageCollection() %>% 
  ee$ImageCollection$toBands() %>% 
  ee$Image$rename(sprintf("prope_%02d", seq_along(z_property)))

img$bandNames()$getInfo()
```

**Comment by lopezjuana** [comment]
**csaybar** Thank you very much, I was able to generate the multiband image. Now I need to convert the image to a grd or similar format to use the **predict function of the caret package**.
One of the parameters is "Raster* object. Typically a multi-layer type (RasterStack or RasterBrick)"
I can't find a way to convert the Image from GEE obtained to raster. Best regards

**Comment by csaybar** [comment]
https://www.rdocumentation.org/packages/rgee/versions/1.0.9/topics/ee_as_raster

**Comment by lopezjuana** [comment]
Good afternoon: I exported the image to the drive, downloaded it and was able to run the predict function. Thank you!!!
The code used is:
imgPred <- ee_as_raster(
  image = stack,
  region = region,
  via = "drive",
  scale = 1000,
  maxPixels = 1e+09,
)
I leave as a comment the message that appears to me, in case it is useful:
Error: Internal error: `what` must refer to arguments in the LHS of `=`.

  # Good:
  deprecate_warn("some_googledrive_function(arg = )")

  # Bad:
  deprecate_warn("some_googledrive_function(arg)")

Run `rlang::last_error()` to see where the error occurred.
Best regards, thank you very much!!!!
