### ISSUE TITLE
Feature request - Export gif from collection of images

### ISSUE THREAD

**Issue by AlvaroMCMC** [r-spatial/rgee#166]
Hi César, I searched for this in the documentation but I didn't find it, maybe if it exists you can redirect me to it, if don't, I think it would be a great feature of rgee, Thanks.
```

**Comment by csaybar** [comment]
Hi @AlvaroMCMC we exported to rgeeExtra. Sorry, we are still working on the documentation. 
https://github.com/r-earthengine/rgeeExtra
