### ISSUE TITLE
Clean all files in rgee_backup folder. Alternative to ee_clean_container()

### ISSUE THREAD

**Issue by kamapu** [r-spatial/rgee#168]
* rgee version: 1.0.9.999
* R version: 4.1.0
* Operating System: Ubuntu Focal Fossa

After doing a loop with NDVI calculations I tried to delete all the files in the container at Google Drive by using the command:

```r
ee_clean_container(name = "rgee_backup", type = "drive")
```

I realized that this command deletes only one file at time. Thus I tried to define an own function to delete everything after a loop was concluded:

```r
absolute_clean <- function(name = "rgee_backup", type = "drive", ...) {
	repeat {
		Check <- ee_clean_container(name = name, type = type, ...)
		if(!Check) break
	}
}

## Executing the function
absolute_clean()
```

Here I was expecting to get a value **FALSE** for `Check` if the container is empty but instead the value was still **TRUE**. Luckily the empty container also causes an error, preventing the loop to run for ever:

```
Deleting rgee_backup/NA.
Error: Invalid <dribble>. Can't confirm `kind = "drive#file"` or
`kind = "drive#drive"` for all elements of the `drive_resource` column.
Run `rlang::last_error()` to see where the error occurred.
```

In this context I have two alternative questions:

- Is it possible to change the behavior of `ee_clean_container()`, returning a value **FALSE** for an empty container and a warning message instead of an error?
- Is there another (better?) option to delete everything in the folder **rgee_backup**?

**Comment by csaybar** [comment]
Hi @kamapu thanks for open this issue, this has a lot of sense to me. Thanks, I will work on it soon :)

For now, you can directly use the `googledrive` package.

```r
library(rgee)
library(googledrive)

ee_Initialize(drive=TRUE) #load your Google Drive credentials

->googledrive::drive_rm
```

**Comment by csaybar** [comment]
Hi @kamapu I solved this problem related to the release of googledrive 2.0.0. Now `ee_clean_container` works faster and recursively. Thanks for your contribution :) 

```r
library(rgee)
remotes::install_github("r-spatial/rgee")
```

If the problem persists, feel free to re-open the issue.

**Comment by kamapu** [comment]
I just checked the new version of the package and it works perfect. This time also the folder **rgee_backup** gets deleted.
