### ISSUE TITLE
ee_extract returns error 'incorrect number of dimensions'

### ISSUE THREAD

**Issue by MichelineCampbell** [r-spatial/rgee#169]
* rgee version: 1.0.9
* R version: 4.1.0
* Operating System: Windows 10

### Description
Hello, I am new to rgee (and GEE), so apologies if this is an obvious question with an obvious solution.
I am trying to extract a timeseries following the example here: https://github.com/r-spatial/rgee/blob/examples/rgee/08_extract.R
```
library(tidyverse)
library(gganimate)
library(rgee)
library(sf)

ee_Initialize()
ee_user_info()

# Define a Image or ImageCollection: Terraclimate
terraclimate <- ee$ImageCollection("IDAHO_EPSCOR/TERRACLIMATE")$
  filterDate("2001-01-01", "2002-01-01")$
  map(function(x){
    date <- ee$Date(x$get("system:time_start"))$format('YYYY_MM_dd')
    name <- ee$String$cat("Terraclimate_pp_", date)
    x$select("pr")$reproject("EPSG:4326")$set("RGEE_NAME", name)
  })

# Define a geometry
nc <- st_read(
  dsn = system.file("shape/nc.shp", package = "sf"),
  stringsAsFactors = FALSE,
  quiet = TRUE
)

# Extract values
ee_nc_rain <- ee_extract(
  x = terraclimate,
  y = nc,
  scale = 250,
  fun = ee$Reducer$mean(),
  sf = FALSE
)
```

And get the error: 
```Error in `[.default`(x, index, ) : incorrect number of dimensions```

I have tried redefining y using ```nc["NAME"]``` to get just the geometry , but that also doesn't work.

Many thanks,
Micha

**Comment by csaybar** [comment]
Hi @MichelineCampbell sorry for the inconvenience. I'm almost 100% sure that we already solved this bug :). Can you install the latest rgee version?

```r
remotes::install_github("r-spatial/rgee")
```

Please let us know if the problem persists.

**Comment by MichelineCampbell** [comment]
Oh I'm so sorry, I never got around to replying, but yes, this solved it! Thank-you!
