### ISSUE TITLE
How display imageCollection one to one in the map view

### ISSUE THREAD

**Issue by luisdiazc** [r-spatial/rgee#172]
I have consulted a collection of Sentinel 1 images for a specific ROI and a given time window. I want to visualize these one by one in the map view. I would appreciate some help on this as I am totally new to using rgee. 

```
# Librerias 

library(rgee)
library(googledrive)
library(reticulate)
library(raster)
library(sf)
library(mapedit)
library(mapview)
library(tidyverse)

ee_Initialize(email = "cienciacondatoss", drive = TRUE)
ee_users()

RR <- read_sf("F:/INESAG/Propuestas de extensión/SIG con R - Basico/Datos/shp/Cuenca_rio_Rancheria.shp") %>% 
  sf_as_ee()

S1RRVV <- ee$ImageCollection('COPERNICUS/S1_GRD')$
  filterBounds(RR)$
  filter(ee$Filter$eq('instrumentMode', 'IW'))$
  filter(ee$Filter$eq('orbitProperties_pass', 'ASCENDING'))$
  filterMetadata('resolution_meters', 'equals', 10)$ 
  filterDate('2021-07-01', '2021-07-22')$
  select('VV')

ee_print(S1RRVV)

S1RRVH <- ee$ImageCollection('COPERNICUS/S1_GRD')$
  filterBounds(RR)$
  filter(ee$Filter$eq('instrumentMode', 'IW'))$
  filter(ee$Filter$eq('orbitProperties_pass', 'ASCENDING'))$
  filterMetadata('resolution_meters', 'equals', 10)$ 
  filterDate('2021-07-01', '2021-07-22')$
  select('VH')

ee_print(S1RRVV)
ee_print(S1RRVH)
```

**Comment by ambarja** [comment]
Hi @luisdiazc thanks for open this issue, for visualization multiple layers with rgee is using the `Map$addLayers()` function, however, is necessary to install `rgeeExtra`. Here you can check more documentation :next_track_button: [**more info**](https://r-spatial.github.io/rgee/reference/Map.html)

**Comment by luisdiazc** [comment]
How can I access the names of the images within a imageColeection. Thank you, very much!

**Comment by ambarja** [comment]
You can access to band names using the next code `S1RRVH$toBands()$bandNames()$getInfo()`

**Comment by luisdiazc** [comment]
Great!

I triying use addLayers function for display a imageCollection, but jump the next error:

`Map$centerObject(eeObject = RR, zoom = 9)
Map$addLayers(eeObject = RRS1RRVV)

Error: tentativa de aplicar una no-función`

I installed the rgeeExtra package using `remotes::install_github("r-earthengine/rgeeExtra")` and load with `library(rgeeExtra)`. 

Than you for you answers!

**Comment by ambarja** [comment]
@luisdiazc here a reproducible example :arrow_down: 
```
# Librerias 
library(rgee)
library(rgeeExtra)
library(raster)
library(sf)
library(mapedit)
library(tidyverse)

ee_Initialize()

RR <- ee$Geometry$
  Polygon(
    list(
      -70.05, -13.04,-69.93, -13.04,
      -69.93, -12.90,-70.05, -12.90,
      -70.05, -13.04
      )
    )

S1RRVV <- ee$ImageCollection('COPERNICUS/S1_GRD')$
  filterBounds(RR)$
  filter(ee$Filter$eq('instrumentMode', 'IW'))$
  filter(ee$Filter$eq('orbitProperties_pass', 'ASCENDING'))$
  filterMetadata('resolution_meters', 'equals', 10)$ 
  filterDate('2021-07-01', '2021-07-22')$
  select('VV')

Map$centerObject(eeObject = RR,zoom = 8)
Map$addLayers(eeObject = S1RRVV,visParams = list(min=-25,max=5))

```
![Captura de pantalla de 2021-07-24 09-55-38](https://user-images.githubusercontent.com/23284899/126872324-05f19010-a781-40c7-8200-c5a557efde34.png)

**Comment by luisdiazc** [comment]
@ambarja , I think that my problem is that R is not recognizing the Map $ addLayers method, therefore the error that I indicated before jumps🤔

Also, the comparison between layers with the operator `|` does not work. I think that `rgeeExtra` is bad installed.

**Comment by ambarja** [comment]
Hi @luisdiazc you can update your rgee package with the dependencies and after to use the last code. If you have the same problem Would you mind attached us your sessionInfo?

```
sessionInfo()
```

**Comment by luisdiazc** [comment]
Hi @ambarja , i managed to do it. Thank you very much for you suport. I consider this issue closed. Good bye🥳
