### ISSUE TITLE
The problem I met during initializing rgee environment

### ISSUE THREAD

**Issue by jinglez99** [r-spatial/rgee#182]
* rgee version: 1.1.0
* R version: 4.0.3
* Operating System: Windows

#### At submit an issue, please attached the following information of your `rgee` session:
> library(rgee)
Warning message:
程辑包‘rgee’是用R版本4.0.5 来建造的 
> library(reticulate)
Warning message:
程辑包‘reticulate’是用R版本4.0.5 来建造的 
> ee_check()
(*)  Python version
√ [Ok] C:/Users/jingl/AppData/Local/r-miniconda/envs/rgee/python.exe v3.9
(*)  Python packages:
√ [Ok] numpy
√ [Ok] earthengine-api
> ee_Initialize()
-- rgee 1.1.0 ---------------------------------------------------------- earthengine-api 0.1.277 -- 
 √ user: not_defined
 √ Initializing Google Earth Engine:
Enter Earth Engine Authentication: 4/1AX4XfWiu8qnjEdXMz-gMYm8YIo1R1AS_KbvZHltBke01oXd9WsldK-CVzP1
Error in py_call_impl(callable, dots$args, dots$keywords) : URLError: <urlopen error [WinError 10060] 鐢变簬杩炴帴鏂瑰湪涓€娈垫椂闂村悗娌℃湁姝ｇ‘绛斿鎴栬繛鎺ョ殑涓绘満娌℃湁鍙嶅簲锛岃繛鎺ュ皾璇曞け璐ャ€?
> ee_path <- path.expand("~/.config/earthengine/credentials")
> file.exists(ee_path)
[1] FALSE

Description: I am trying to initialize the environment of rgee, however, URLError happens all the time so that I am unable to successfully accomplish it. I have attempted to find the solutions in google, while there is no correct way that can truly solve it. Therefore, I copy the code here, looking for a helpful solution.
![屏幕截图 2021-09-16 101335](https://user-images.githubusercontent.com/67906075/133538168-df255723-8d02-4c2d-8586-91b68efdfc88.jpg)

**Comment by csaybar** [comment]
I think this bug is related #63. Not solved yet.
