### ISSUE TITLE
How to export all bands separately of one satelital image (one image per band)?

### ISSUE THREAD

**Issue by AlvaroMCMC** [r-spatial/rgee#183]
### What I do is export an image after selecting its bands with the same resolution. In this example, I selected the 4, 3 and 2 of some sentinel image. Is there a way to export all bands (one image per band)?. I know they have different spatial resolutions (10, 30, 60 m..).

```
library(rgee)

What I do:

#selecting bands with the same resolution (image is sentinel)
image_432 <- image$select(c('B4','B3','B2'))

imagen_descargada <- ee_as_raster(image = image_432, 
                                   region = image_432$geometry(),
                                   dsn = "image.tif",
                                   scale = 10) 
```

**Comment by csaybar** [comment]
See https://developers.google.com/earth-engine/guides/scale
