### ISSUE TITLE
RGB loadGeoTIFF in GCP Storage

### ISSUE THREAD

**Issue by Tartomas** [r-spatial/rgee#184]
* rgee version:1.1.0
* R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

### Description
Hello Cesar, gracias por tu aporte a la comunidad de GEE en R, realmente has hecho un tremendo trabajo y no cabe duda que seguiras aportando por muchos años más !

### Issue or question

I'm trying to get a Sentinel RGB image that I have exported previously into GoogleStorage as RGB.tif. It's an options? or this functions is only for single band calling? 

When I try to use _loadGeoTIFF_ function to grab it, it's appear that only get one band. 
  ```
  uriRGB = paste0("gs://bucket/RGB/RGB_S2SR_T18GXA_2021-08-31_mask.tif")
  imageRGB <- ee$Image$loadGeoTIFF(uri)

> print(imageRGB$bandNames()$getInfo())
[1] "B0"
> print(imageRGB$bandTypes()$getInfo())
$B0
$B0$type
[1] "PixelType"

$B0$precision
[1] "double"
  print(imageRGB$bandTypes()$getInfo())
  ```

When I use raster package and "*vsicurl*"  I'm able to grab it, like: 
  ```
   rst = raster::brick(paste0("/vsicurl/", res_file$link)) 
  ```
When I download from bucket and drag it to QGIS I can see this
![image](https://user-images.githubusercontent.com/11640130/133908745-22c203d6-f3ef-4e0e-8c43-261d51a3c85a.png)

Thanks you very much !

**Comment by csaybar** [comment]
Hola @Tartomas muchas gracias por tus palabras :D! . Can u give me access to read your bucket? 
csaybar@gmail.com
Thanks!

**Comment by Tartomas** [comment]
Hi @csaybar 
I make public this file [access to the tif.](https://storage.googleapis.com/rgee-test/raster_RGB_S2SR_T18GXA_2021-08-31_mask.tif) and also make you **_Storage Object viewer_**
Let me know if you are able to go through this issue.

What I'm really into is to use _ee$Image$loadGeoTIFF(uri)_ to rendered in leaflet with _addTiles_()

```
# rgee Map$addLayer
uri = paste0("gs://rgee-test/raster_NDVI_S2SR_T18GXA_",last_date,"_mask.tif")
imageas <- ee$Image$loadGeoTIFF(uri)
# This work properly
Map$centerObject(imageas, zoom = 15)
Map$addLayer(imageas, vizParams, "Landsat NDVI")

# This doesn't work
leaflet() %>% 
  addTiles() %>% 
  setView(-72.99389,-40.39703, 12) %>% 
  addTiles(
    urlTemplate = imageas$rgee$tokens,
    layerId = "leaflet_false_color",
    options = leaflet::tileOptions(opacity = 1)
  )
 
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'Image' object has no attribute 'rgee'

```
Tell me what you think
Thanks !

**Comment by csaybar** [comment]
Hi @Tartomas the problem is that their resource is not a COG (https://www.cogeo.org/).

```r
library(httr)

resource  <- "gs://rgee-test/raster_NDVI_S2SR_T18GXA_2021-08-31_mask.tif"
titiler_server_service <- "https://api.cogeo.xyz//cog/tilejson.json"

response <- httr::GET(
  url = titiler_server_service,
  config = httr::accept_json(),
  query = list(
    "url" = resource
  )
)

response$status_code
# 500 Internal Server Error

```

You can use GDAL > 3.1 to convert it running:

```
gdalwarp src1.tif src2.tif out.tif -of COG
```

**Comment by Tartomas** [comment]
Hi Cesar
Thanks you very much, I was able to load RGB from a bucket as a COG files. 
Best, thank again !
