### ISSUE TITLE
Error during wrapup: EEException: Invalid argument specified for ee.List(): 0.0

### ISSUE THREAD

**Issue by victorkorir1** [r-spatial/rgee#192]
* rgee version:1.1.2
* R version:4.1.0 (2021-05-18) -- "Camp Pontanezen"
* Operating System:Ubuntu

#### At submit an issue, please attached the following information of your `rgee` session:

- [1] You have the Python API installed (from terminal):
```
earthengine -h
```

- [1] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
```
- [1] You can run a simple EE command from R: 

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())
``` 

Attach your Python (reticulate) configuration:

```
python:         /home/victor/.local/share/r-miniconda/envs/r-reticulate/bin/python3
libpython:      /home/victor/.local/share/r-miniconda/envs/r-reticulate/lib/libpython3.6m.so
pythonhome:     /home/victor/.local/share/r-miniconda/envs/r-reticulate:/home/victor/.local/share/r-miniconda/envs/r-reticulate
version:        3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01)  [GCC 9.3.0]
numpy:          /home/victor/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.19.5

NOTE: Python version was forced by use_python function
```
I have a function to perform speckle filtering in sentinel 1 as follows:

```
exports_refinedLee <- function(img) {
  #img must be in natural units,i.e not in DB
  #Set up 3*3 kernels
  weights3 <- ee$List$'repeat'(ee$List$'repeat'(1, 3), 3)
  kernel3 <- ee$Kernel$fixed(3, 3, weights3, 1, 1, FALSE)
  mean3 <- img$reduceNeighborhood(ee$Reducer$mean(), kernel3)
  variance3 <- img$reduceNeighborhood(ee$Reducer$variance(), kernel3)
  
  #Use a sample of the 3*3 windows inside a 7*7 windows to determine gradients
  #directions
  sample_weights <- ee$List(c(c(0,0,0,0,0,0,0),c(0,1,0,1,0,1,0),
                              c(0,0,0,0,0,0,0),c(0,1,0,1,0,1,0),
                              c(0,0,0,0,0,0,0),c(0,1,0,1,0,1,0),
                              c(0,0,0,0,0,0,0)))
  
  sample_kernel <- ee$Kernel$fixed(7,7,sample_weights,3,3,FALSE)
  
  #Calculate mean and variance for the sampled windows and store as 9 bands
  sample_mean <- mean3$neighborhoodToBands(sample_kernel)
  sample_var <- variance3$neighborhoodToBands(sample_kernel)
  
  
  #Determine the 4 gradients for the sampled videos
  gradients <- sample_mean$select(1)$subtract(sample_mean$select(7))$abs()
  gradients <- gradients$addBands(sample_mean$select(6)$
                                    subtract(sample_mean$select(2))$abs())
  gradients <- gradients$addBands(sample_mean$select(3)$
                                    subtract(sample_mean$select(5))$abs()) 
  gradients <- gradients$addBands(sample_mean$select(0)$
                                    subtract(sample_mean$select(8))$abs())
  
  #And find the maximum gradient amongst gradient bands
  max_gradient <- gradients$reduce(ee$Reducer$max())
  
  #Create a mask for band pixels that are the maximum gradient
  gradmask <- gradients$eq(max_gradient)
  
  #Duplicate grandmask bands:each gradient represents 2 directions
  gradmask <-gradmask$addBands(gradmask)
  
  #Determine the 8 directions
 directions <- sample_mean$select(1)$subtract(sample_mean$select(4)
                                              $gt(sample_mean$select(4)
                                              $subtract(sample_mean
                                              $select(7)))$multiply(1)) 
 directions <- directions$addBands(sample_mean$select(6)
                                   $subtract(sample_mean$select(4))
                                   $gt(sample_mean$select(4)
                                  $subtract(sample_mean$select(2)))$multiply(2))
 directions <- directions$addBands(sample_mean$select(3)
                                   $subtract(sample_mean$select(4))
                                   $gt(sample_mean$select(4)
                                  $subtract(sample_mean$select(5)))$multiply(3))
 directions <- directions$addBands(sample_mean$select(0)
                                   $subtract(sample_mean$select(4))
                                   $gt(sample_mean$select(4)
                                $subtract(sample_mean$select(8)))$multiply(4))
 
 # The next 4 are the not() of the previous 4
 directions <- directions$addBands(directions$select(0)$Not()$multiply(5))
 directions <- directions$addBands(directions$select(1)$Not()$multiply(6))
 directions <- directions$addBands(directions$select(2)$Not()$multiply(7))
 directions <- directions$addBands(directions$select(3)$Not()$multiply(8))
 
 #Mask all values that are not 1-8
 directions <- directions$updateMask(gradmask)
 
 #collapse the stack into a single band image 
 #due to masking, each pixel has just one value(1-8) in its directional band
 #and is otherwise masked
 directions <- directions$reduce(ee$Reducer$sum())
 
 sample_stats <-sample_var$divide(sample_mean$multiply(sample_mean))
 
 #calculate the local noise variance
 sigmav <- sample_stats$toArray()$arraySort()$arraySlice(0,0,5)$arrayReduce(ee$Reducer$mean(),c(0))
 #setup 7*7 kernels for directional statistics
 rect_weights <- ee$List$'repeat'(ee$List$'repeat'(0.0,7),3)$
                                cat(ee$List$'repeat'(ee$List$'repeat'(1,7),4))
 diag_weights <- ee$List(Array(c(1,0,0,0,0,0,0), c(1,1,0,0,0,0,0), c(1,1,1,0,0,0,0), 
                         c(1,1,1,1,0,0,0), c(1,1,1,1,1,0,0), c(1,1,1,1,1,1,0),
                              c(1,1,1,1,1,1,1)))
 
  rect_kernel <- ee$Kernel$fixed(7,7, rect_weights, 3, 3,FALSE)
  diag_kernel <- ee$Kernel$fixed(7,7, diag_weights, 3, 3, FALSE)
  #Create stacks for mean and variance using the original kernels. Mask with relevant direction.
  dir_mean <- img$reduceNeighborhood(ee$Reducer$mean(), rect_kernel)$updateMask(directions$eq(1))
  dir_var <- img$reduceNeighborhood(ee$Reducer$variance(), rect_kernel)$updateMask(directions$eq(1))
  
  dir_mean <- dir_mean$addBands(img$reduceNeighborhood(ee$Reducer$mean(),
                                    diag_kernel)$updateMask(directions$eq(2)))
  dir_var <- dir_var.addBands(img$reduceNeighborhood(ee$Reducer$variance(),
                                    diag_kernel)$updateMask(directions$eq(2)))
  # and add the bands for rotated kernels
  for (i in 1:4 ) {
    dir_mean <- dir_mean$addBands(img$reduceNeighborhood(ee$Reducer$mean(),
                        rect_kernel$rotate(i))$updateMask(directions$eq(2*i+1)))
    dir_var <- dir_var$addBands(img$reduceNeighborhood(ee$Reducer$variance(),
                      rect_kernel$rotate(i))$updateMask(directions$eq(2*i+1)))
    dir_mean <- dir_mean$addBands(img$reduceNeighborhood(ee$Reducer$mean(), 
                        diag_kernel$rotate(i))$updateMask(directions$eq(2*i+2)))
    dir_var <- dir_var$addBands(img$reduceNeighborhood(ee$Reducer$variance(),
                        diag_kernel$rotate(i))$updateMask(directions$eq(2*i+2)))
  }
  #"collapse" the stack into a single band image (due to masking, each pixel has just one value in it's directional band, and is otherwise masked)
  dir_mean <- dir_mean$reduce(ee$Reducer$sum())
  dir_var <- dir_var$reduce(ee$Reducer$sum())
  
  # finally generate the filtered value
  varX <- dir_var$subtract(dir_mean$multiply(dir_mean)$multiply(sigmaV))$divide(sigmaV.add(1.0))
  
  b <- varX$divide(dir_var)
  
  result <- dir_mean$add(b$multiply(img$subtract(dir_mean)))
  return(result$arrayFlatten(c(c('sum'))))
}
```

I try to pass an ee image object through the function as follows:
```
leefiltered <- exports_refinedLee(test1)
```
I get the error
```
Error during wrapup: EEException: Invalid argument specified for ee.List(): 0.0

Detailed traceback:
  File "/home/victor/.virtualenvs/rgee/lib/python3.6/site-packages/ee/apifunction.py", line 205, in <lambda>
    return lambda *args, **kwargs: func.call(*args, **kwargs)  # pylint: disable=unnecessary-lambda
  File "/home/victor/.virtualenvs/rgee/lib/python3.6/site-packages/ee/function.py", line 67, in call
    return self.apply(self.nameArgs(args, kwargs))
  File "/home/victor/.virtualenvs/rgee/lib/python3.6/site-packages/ee/function.py", line 80, in apply
    result = computedobject.ComputedObject(self, self.promoteArgs(named_args))
  File "/home/victor/.virtualenvs/rgee/lib/python3.6/site-packages/ee/function.py", line 107, in promoteArgs
    promoted_args[name] = Function._promoter(args[name], spec['type'])
  File "/home/victor/.virtualenvs/rgee/lib/python3.6/site-packages/ee/__init__.py", line 265, in _Promote
    return List(arg)
  File "/home/victor/.virtualenvs/rgee/lib/python3.6/site-packages/ee/computedobject.py", line 32, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/victor/.virtualenvs/rgee/lib/python3.6/site-packages/ee/ee_list.py", line 42, in __init__
    'Invalid argument specified for ee.List(): %s' % arg)

Error: no more error handlers available (recursive errors?); invoking 'abort' restart
````

**Comment by victorkorir1** [comment]
https://code.earthengine.google.com/2ef38463ebaf5ae133a478f173fd0ab5 
This the function i am trying to replicate in R

**Comment by csaybar** [comment]
Hi @victorkorir1!

Can you help me a bit by creating a small example that shows me where exactly the error appears? I don't have too much experience with SAR data.

**Comment by victorkorir1** [comment]
I first load Sentinel 1 imagery and filter according to my study area,time,VV/VH polarization and ascending or descending path.
` library(rgee)
library(tcltk)
#Load sentinel1 image collection
sentinel1 <-ee$ImageCollection('COPERNICUS/S1_GRD')
#AOI Geometry
Ext <- list(
  c(35.953444081338944, 0.31636293022018336),
  c(36.21024950126082,0.31636293022018336),
  c(36.21024950126082, 0.7475567060026045),
  c(35.953444081338944, 0.7475567060026045))

marigat_plains <- ee$Geometry$Polygon(coords = Ext, proj = "EPSG:4326",
                                      geodesic = FALSE)

#user dateinput
start <- ee$Date('2014-01-01')
end <- ee$Date('2014-12-31')

#Filter to get images with VV and VH polarization,specified date and region
vv <- sentinel1$filter(ee$Filter$listContains('transmitterReceiverPolarisation',
                                              'VV'))
vh <- vv$filter(ee$Filter$listContains('transmitterReceiverPolarisation', 'VH'))
iws <- vh$filter(ee$Filter$eq('instrumentMode', 'IW'))
filtered <- iws$filterBounds(marigat_plains)$filterDate(start, end)
filtered$getInfo()

#select path,ASCENDING or DESCENDING
path <-'ASCENDING'
if (path == 'ASCENDING') {
  selectedPath <- filtered$filter(ee$Filter$eq('orbitProperties_pass',
                                               'ASCENDING'))
} else if(path == 'DESCENDING') {
  selectedPath <- filtered$filter(ee$Filter$eq('orbitProperties_pass',
                                               'ASCENDING'))
} else {
  print("Specifiy whether ASCENDING/DESCENDING")
}`
I then define functions to perform angular corrections as follows:
`toGammaVV <- function(image) {
  return(image$addBands(image$select('VV')$subtract(image$select(
								  'angle')$multiply(pi/180.0)$cos()$log10(
								  )$multiply(10.0))$rename('VV_corr')))
}
toGammaVH <- function(image) {
  return(image$addBands(image$select('VH')$subtract(image$select(
								  'angle')$multiply(pi/180.0)$cos()$log10(
								  )$multiply(10.0))$rename('VH_corr')))
}
 `
I also define functions to convert from natural units to DB and viceversa
`exports_to_natural <- function(img) {
	return (ee$Image(img)$log10()$divide(10.0))
}
exports_to_DB <- function(img) {
	return(ee$Image(img)$log10()$multiply(10.0))
}`
I also define the function to perform speckle filtering,and calling this specific function is causing problems 
`
exports_refinedLee <- function(img) {
  #img must be in natural units,i.e not in DB
  #Set up 3*3 kernels
  weights3 <- ee$List$'repeat'(ee$List$'repeat'(1, 3), 3)
  kernel3 <- ee$Kernel$fixed(3, 3, weights3, 1, 1, FALSE)
  mean3 <- img$reduceNeighborhood(ee$Reducer$mean(), kernel3)
  variance3 <- img$reduceNeighborhood(ee$Reducer$variance(), kernel3)
  
  #Use a sample of the 3*3 windows inside a 7*7 windows to determine gradients
  #directions
  sample_weights <- ee$List(c(c(0,0,0,0,0,0,0),c(0,1,0,1,0,1,0),
                              c(0,0,0,0,0,0,0),c(0,1,0,1,0,1,0),
                              c(0,0,0,0,0,0,0),c(0,1,0,1,0,1,0),
                              c(0,0,0,0,0,0,0)))
  
  sample_kernel <- ee$Kernel$fixed(7,7,sample_weights,3,3,FALSE)
  
  #Calculate mean and variance for the sampled windows and store as 9 bands
  sample_mean <- mean3$neighborhoodToBands(sample_kernel)
  sample_var <- variance3$neighborhoodToBands(sample_kernel)
  
  
  #Determine the 4 gradients for the sampled videos
  gradients <- sample_mean$select(1)$subtract(sample_mean$select(7))$abs()
  gradients <- gradients$addBands(sample_mean$select(6)$
                                    subtract(sample_mean$select(2))$abs())
  gradients <- gradients$addBands(sample_mean$select(3)$
                                    subtract(sample_mean$select(5))$abs()) 
  gradients <- gradients$addBands(sample_mean$select(0)$
                                    subtract(sample_mean$select(8))$abs())
  
  #And find the maximum gradient amongst gradient bands
  max_gradient <- gradients$reduce(ee$Reducer$max())
  
  #Create a mask for band pixels that are the maximum gradient
  gradmask <- gradients$eq(max_gradient)
  
  #Duplicate grandmask bands:each gradient represents 2 directions
  gradmask <-gradmask$addBands(gradmask)
  
  #Determine the 8 directions
 directions <- sample_mean$select(1)$subtract(sample_mean$select(4)
                                              $gt(sample_mean$select(4)
                                              $subtract(sample_mean
                                              $select(7)))$multiply(1)) 
 directions <- directions$addBands(sample_mean$select(6)
                                   $subtract(sample_mean$select(4))
                                   $gt(sample_mean$select(4)
                                  $subtract(sample_mean$select(2)))$multiply(2))
 directions <- directions$addBands(sample_mean$select(3)
                                   $subtract(sample_mean$select(4))
                                   $gt(sample_mean$select(4)
                                  $subtract(sample_mean$select(5)))$multiply(3))
 directions <- directions$addBands(sample_mean$select(0)
                                   $subtract(sample_mean$select(4))
                                   $gt(sample_mean$select(4)
                                $subtract(sample_mean$select(8)))$multiply(4))
 
 # The next 4 are the not() of the previous 4
 directions <- directions$addBands(directions$select(0)$Not()$multiply(5))
 directions <- directions$addBands(directions$select(1)$Not()$multiply(6))
 directions <- directions$addBands(directions$select(2)$Not()$multiply(7))
 directions <- directions$addBands(directions$select(3)$Not()$multiply(8))
 
 #Mask all values that are not 1-8
 directions <- directions$updateMask(gradmask)
 
 #collapse the stack into a single band image 
 #due to masking, each pixel has just one value(1-8) in its directional band
 #and is otherwise masked
 directions <- directions$reduce(ee$Reducer$sum())
 
 sample_stats <-sample_var$divide(sample_mean$multiply(sample_mean))
 
 #calculate the local noise variance
 sigmav <- sample_stats$toArray()$arraySort()$arraySlice(0,0,5)$arrayReduce(ee$Reducer$mean(),c(0))
 #setup 7*7 kernels for directional statistics
 rect_weights <- ee$List$'repeat'(ee$List$'repeat'(0.0,7),3)$
                                cat(ee$List$'repeat'(ee$List$'repeat'(1,7),4))
 diag_weights <- ee$List(Array(c(1,0,0,0,0,0,0), c(1,1,0,0,0,0,0), c(1,1,1,0,0,0,0), 
                         c(1,1,1,1,0,0,0), c(1,1,1,1,1,0,0), c(1,1,1,1,1,1,0),
                              c(1,1,1,1,1,1,1)))
 
  rect_kernel <- ee$Kernel$fixed(7,7, rect_weights, 3, 3,FALSE)
  diag_kernel <- ee$Kernel$fixed(7,7, diag_weights, 3, 3, FALSE)
  #Create stacks for mean and variance using the original kernels. Mask with relevant direction.
  dir_mean <- img$reduceNeighborhood(ee$Reducer$mean(), rect_kernel)$updateMask(directions$eq(1))
  dir_var <- img$reduceNeighborhood(ee$Reducer$variance(), rect_kernel)$updateMask(directions$eq(1))
  
  dir_mean <- dir_mean$addBands(img$reduceNeighborhood(ee$Reducer$mean(),
                                    diag_kernel)$updateMask(directions$eq(2)))
  dir_var <- dir_var.addBands(img$reduceNeighborhood(ee$Reducer$variance(),
                                    diag_kernel)$updateMask(directions$eq(2)))
  # and add the bands for rotated kernels
  for (i in 1:4 ) {
    dir_mean <- dir_mean$addBands(img$reduceNeighborhood(ee$Reducer$mean(),
                        rect_kernel$rotate(i))$updateMask(directions$eq(2*i+1)))
    dir_var <- dir_var$addBands(img$reduceNeighborhood(ee$Reducer$variance(),
                      rect_kernel$rotate(i))$updateMask(directions$eq(2*i+1)))
    dir_mean <- dir_mean$addBands(img$reduceNeighborhood(ee$Reducer$mean(), 
                        diag_kernel$rotate(i))$updateMask(directions$eq(2*i+2)))
    dir_var <- dir_var$addBands(img$reduceNeighborhood(ee$Reducer$variance(),
                        diag_kernel$rotate(i))$updateMask(directions$eq(2*i+2)))
  }
  #"collapse" the stack into a single band image (due to masking, each pixel has just one value in it's directional band, and is otherwise masked)
  dir_mean <- dir_mean$reduce(ee$Reducer$sum())
  dir_var <- dir_var$reduce(ee$Reducer$sum())
  
  # finally generate the filtered value
  varX <- dir_var$subtract(dir_mean$multiply(dir_mean)$multiply(sigmaV))$divide(sigmaV.add(1.0))
  
  b <- varX$divide(dir_var)
  
  result <- dir_mean$add(b$multiply(img$subtract(dir_mean)))
  return(result)
}
`
I then define another function that fetches CFSV2: NCEP Climate Forecast System Version 2, 6-Hourly Products for the purposes of eliminating surface roughening due to windy conditions during acquisition
`ncep <- function(date){
  #rdate <-eedate_to_rdate(eeDate,timestamp = TRUE)
  wx <- ee$ImageCollection('NOAA/CFSV2/FOR6H')$filterDate(date)
  vwind <- wx$select('v-component_of_wind_height_above_ground')
  a <- vwind$max()
  uwind <- wx$select('u-component_of_wind_height_above_ground')
  b <- uwind$max()
  a <- a$pow(2)
  b <- b$pow(2)
  ab <- a$add(b)
  ws <- ab$sqrt()
  ws <- ws$multiply(3.6)
  return (ws$rename('windy')$set('date',date))
}`
What folllows is just calling these methods.Everythings works well apart for the speckle filtering method
`#Get the dates from the image and format them
dates <- selectedPath$map(function(image) {
  return(image$set('date', image$date()$format('Y-MM-dd')))
})
#Get a list of dates
datelist <- dates$aggregate_array('date')

datelist$size()
ws <- ee$List(datelist)$map(ee_utils_pyfunc( #ee_utils_pyfunc is necessary to apply a map function to an ee$List
  ncep))

print(dates)
innerjoin <-ee$Join$inner()
filterDateeq<-ee$Filter$equals()
#Apply the join. We have to join the wind data with the Sentinel-1 data
#in order to apply a mask on VV and VH bands!
innerjoined <- innerjoin$apply(dates,ee$ImageCollection(ws),filterDateeq)

#concatenate images to create an image collection,primary is SENTINEL 1 imagey
#secondary is the wind data
joinedS1pol <- dates$map(function(feature){
  return (ee$Image$cat(feature$get('primary'),feature$get('secondary')))
})
print(joinedS1pol)
#explicit cast to Imagecollection
joinedS1pol <- ee$ImageCollection(joinedS1pol)
#update mask to exclude areas where the wind speed is >=12 m/s
windmask <- function(image){
  mask <- ee$Image(0)$where(image$select('windy')$lt(12.0),1)
  return (image$updateMask(mask))
}
windy <- joinedS1pol$select('windy')$mean()$clip(point)
#reduce region
meanDictionary <- windy$reduceRegion(reducer=ee$Reducer$mean(),
                                     geometry=marigat_plains,scale=2000)
print(meanDictionary)

#Apply the windmask to remove areas >12m/s wind speed
joinedS1pol <- joinedS1pol$map(windmask)
print(joinedS1pol)
angle <- joinedS1pol$mean()$clip(marigat_plains)
#reduce the region
meanDictionary <- angle$select('angle')$reduceRegion(reducer=(ee$Reducer$mean()),
                                                     geometry=marigat_plains,
                                                    scale=20000,bestEffort=TRUE)
#The result is a dictionary,print it
print(meanDictionary)


#create a monthly composite from means at different polarizations and look angles
test1<-exports_to_natural(joinedS1pol$select('VH_corr')$mean())
leefiltered <- exports_refinedLee(test1)`

The error occurs  in the line:
`leefiltered <- exports_refinedLee(test1)`

**Comment by victorkorir1** [comment]
What follows is calling of the above methods.The only cause of error is the speckle filtering method
```#Get the dates from the image and format them
dates <- selectedPath$map(function(image) {
  return(image$set('date', image$date()$format('Y-MM-dd')))
})
#Get a list of dates
datelist <- dates$aggregate_array('date')

datelist$size()
ws <- ee$List(datelist)$map(ee_utils_pyfunc( #ee_utils_pyfunc is necessary to apply a map function to an ee$List
  ncep))

print(dates)
innerjoin <-ee$Join$inner()
filterDateeq<-ee$Filter$equals()
#Apply the join. We have to join the wind data with the Sentinel-1 data
#in order to apply a mask on VV and VH bands!
innerjoined <- innerjoin$apply(dates,ee$ImageCollection(ws),filterDateeq)

#concatenate images to create an image collection,primary is SENTINEL 1 imagey
#secondary is the wind data
joinedS1pol <- dates$map(function(feature){
  return (ee$Image$cat(feature$get('primary'),feature$get('secondary')))
})
print(joinedS1pol)
#explicit cast to Imagecollection
joinedS1pol <- ee$ImageCollection(joinedS1pol)
#update mask to exclude areas where the wind speed is >=12 m/s
windmask <- function(image){
  mask <- ee$Image(0)$where(image$select('windy')$lt(12.0),1)
  return (image$updateMask(mask))
}
windy <- joinedS1pol$select('windy')$mean()$clip(point)
#reduce region
meanDictionary <- windy$reduceRegion(reducer=ee$Reducer$mean(),
                                     geometry=marigat_plains,scale=2000)
print(meanDictionary)

#Apply the windmask to remove areas >12m/s wind speed
joinedS1pol <- joinedS1pol$map(windmask)
print(joinedS1pol)
angle <- joinedS1pol$mean()$clip(marigat_plains)
#reduce the region
meanDictionary <- angle$select('angle')$reduceRegion(reducer=(ee$Reducer$mean()),
                                                     geometry=marigat_plains,
                                                    scale=20000,bestEffort=TRUE)
#The result is a dictionary,print it
print(meanDictionary)


#create a monthly composite from means at different polarizations and look angles
test1<-exports_to_natural(joinedS1pol$select('VH_corr')$mean())
leefiltered <- exports_refinedLee(test1)```

**Comment by victorkorir1** [comment]
The error occurs in the last line 
```leefiltered <- exports_refinedLee(test1)```

**Comment by victorkorir1** [comment]
It is a quite a lengthy piece of code but hopefully you can be able to reproduce it.Thanks

**Comment by victorkorir1** [comment]
I suspect this is the line causing the error ```rect_weights <- ee$List$'repeat'(ee$List$'repeat'(0.0,7),3)$
                                cat(ee$List$'repeat'(ee$List$'repeat'(1,7),4))```
This is because I tried debugging the function and it breaks at this point with the error 
```
Error during wrapup: EEException: Invalid argument specified for ee.List(): 0.0

Detailed traceback:
  File "/home/victor/.virtualenvs/rgee/lib/python3.6/site-packages/ee/apifunction.py", line 205, in <lambda>
    return lambda *args, **kwargs: func.call(*args, **kwargs)  # pylint: disable=unnecessary-lambda
  File "/home/victor/.virtualenvs/rgee/lib/python3.6/site-packages/ee/function.py", line 67, in call
    return self.apply(self.nameArgs(args, kwargs))
  File "/home/victor/.virtualenvs/rgee/lib/python3.6/site-packages/ee/function.py", line 80, in apply
    result = computedobject.ComputedObject(self, self.promoteArgs(named_args))
  File "/home/victor/.virtualenvs/rgee/lib/python3.6/site-packages/ee/function.py", line 107, in promoteArgs
    promoted_args[name] = Function._promoter(args[name], spec['type'])
  File "/home/victor/.virtualenvs/rgee/lib/python3.6/site-packages/ee/__init__.py", line 265, in _Promote
    return List(arg)
  File "/home/victor/.virtualenvs/rgee/lib/python3.6/site-packages/ee/computedobject.py", line 32, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/victor/.virtualenvs/rgee/lib/python3.6/site-packages/ee/ee_list.py", line 42, in __init__
    'Invalid argument specified for ee.List(): %s' % arg)

Error: no more error handlers available (recursive errors?); invoking 'abort' restart

````

**Comment by victorkorir1** [comment]
So I did a simple test line by adding Print statement after every line and the in the function and I establish that it breaks at this line: ```sigmav <- sample_stats$toArray()$arraySort()$arraySlice(0,0,5)$arrayReduce(ee$Reducer$mean(),c(0))```

**Comment by victorkorir1** [comment]
You need to pass a list ee$Numbers not just numbers to arrayReduce,
i.e ```sigmav <- sample_stats$toArray()$arraySort()$arraySlice(0,0,5)$arrayReduce(ee$Reducer$mean(),c(ee$Number(0))```
