### ISSUE TITLE
Trouble with rgeeExtra install

### ISSUE THREAD

**Issue by gltyree** [r-spatial/rgee#209]
* rgee version:
* R version:
* Operating System:

#### At submit an issue, please attached the following information of your `rgee` session:

- [x] You have the Python API installed (from terminal):
```
earthengine -h
```

- [ ] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
```
- [x] You can run a simple EE command from R: 

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())
``` 

Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()
```

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by csaybar** [comment]
Hi @gltyree sorry for the inconveniences with rgeeExtra can u detail a bit more your problem in https://github.com/r-earthengine/rgeeExtra/issues

**Comment by gltyree** [comment]
Hi Cesar,

Certainly! Funny, I thought the issue was still in 'draft mode' and not yet submitted. I'll resend it.

Best,
Gayle Tyree
________________________________
