### ISSUE TITLE
Error with using reduceRegion with a grouped Reducer

### ISSUE THREAD

**Issue by gltyree** [r-spatial/rgee#223]
* rgee version:
* R version:
* Operating System:

#### At submit an issue, please attached the following information of your `rgee` session:

- [ ] You have the Python API installed (from terminal):
```
earthengine -h
```

- [ ] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
```
- [ ] You can run a simple EE command from R: 

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())
``` 

Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()
```

### Description

Hi rgee team, 

I want to get mean values for an image by using a grouped Reducer:

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by csaybar** [comment]
Hi @gltyree, something like this should work

```r
library(rgee)

ee_Initialize()

srtm_model <- ee$Image$Dataset$CGIAR_SRTM90_V4
ee_geom <- ee$Geometry$Point(c(8.76361, 50.81838)) %>% 
  ee$Geometry$buffer(100)
ee_extract(srtm_model, ee_geom, ee$Reducer$mean())
```
