### ISSUE TITLE
Using Planet in rgee

### ISSUE THREAD

**Issue by Leprechault** [r-spatial/rgee#225]
Hi Everyone!!

I'd like to know if is possible to using `rgee` for download Planet's imagery using a personal Planet API key? We have a Planet tutorial for Google Earth Engine (``https://developers.planet.com/docs/integrations/gee/gee/``) but it's possible the `rgee` integration?

Thanks in advance,

Alexandre

**Comment by csaybar** [comment]
Hi @Leprechault.

I'm not familiar with the Planet API, but it seems to be pretty handy! ... There should be no problem planet with rgee: https://developers.planet.com/docs/integrations/gee/quickstart/. Besides, Map$addLayer supports COG object visualization using titiler in the backend.

```r
library(rgee)
server <- "https://storage.googleapis.com/pdd-stac/disasters/"
file <- "hurricane-harvey/0831/20170831_172754_101c_3B_AnalyticMS.tif"
resource <- paste0(server, file)
visParams <- list(bands = c("B3", "B2", "B1"), min = 3000, max = 13500, nodata = 0)
Map$centerObject(resource)
Map$addLayer(resource, visParams = visParams, shown = TRUE)
```

**Comment by Leprechault** [comment]
Thanks @csaybar!!! Using GEE plugin in Google Cloud works!!
