### ISSUE TITLE
Problem with mapping functions over a collection - not working?

### ISSUE THREAD

**Issue by ckukund** [r-spatial/rgee#239]
Hey @csaybar and @davemlz

I seem to have an issue with mapping functions since yesterday. This affects both eemont functions and locally defined functions. Please see the example below;

### Description

```
library(rgee)
ee_Initialize(drive = TRUE,gcs = TRUE)

eemont <- import("eemont")

period_of_interest <- ee$Filter$date('2017-07-01', '2017-11-01');
inBands = c("B2","B3","B4","B6","B8","B11","B12")
archiveBands = c("B2","B3","B4","B5","B6","B7","B8","B8A","B11","B12")
outBands = c(inBands,"NDVI","NDVI_STD","MNDWI","NDBI","BSI")

#Build the Sentinel 2 collection, filtered by date,  and mask clouds
dataset = ee$ImageCollection('COPERNICUS/S2_SR')$ #COPERNICUS/S2_SR for 2020 data
  filter(period_of_interest)$
  maskClouds()$
  index(list("NDVI", "MNDWI"))

#Functions to compute NDBI and BSI
addNDBI = function(image) {
  ndbi = image$normalizedDifference(c('B12', 'B8'))$
    rename('NDBI')$
    copyProperties(image,list('system:time_start'));
  return (image$addBands(ndbi));
};

addBSI <- function(image){
  x <- image$select("B11")$add(image$select("B4"))
  y <- image$select("B8")$add(image$select("B2"))
  numerator <- x$subtract(y)
  denominator <- x$add(y)
  bsi <- numerator$divide(denominator)$rename("BSI")$
    rename('BSI')$
    copyProperties(image,list('system:time_start'));
  return (image$addBands(bsi))
}

#Collection with all images also containing the NDVI, MNDWI, NDBI and BSI indices
collection = dataset$select(c(inBands,"NDVI","MNDWI"))$map(addBSI)$map(addNDBI);

#Define and calculate the median bands and the other index statistics
band_median = collection$select(inBands)$median()

```

I unfortunately miss all the indices up to this point. 

```
#See which image bands are available;
band_median$bandNames()$getInfo()

```
I get the following output when I run the preceeding line;

```
[1] "B2"  "B3"  "B4"  "B6"  "B8"  "B11" "B12"
```

Has something changed in the last two days? The described code was running well on Tuesday 01.03.2022. I will appreciate your support.

**Comment by ckukund** [comment]
Hey guys, 

There is no issue here. My bad as I previously selected "inBands"!

**Comment by davemlz** [comment]
Great, @ckukund!

One thing: [NDBI is already included in Awesome Spectral Indices](https://github.com/davemlz/awesome-spectral-indices#urban-%EF%B8%8F), so, you can directly compute it without using `normalizedDifference()`.

Second: I don't know the BSI, but if you want, you can [add it to Awesome Spectral Indices](https://github.com/davemlz/awesome-spectral-indices#call-for-indices-rotating_light) to make it directly available :)

PD: From `eemont>=0.3.0` the `index()` method is deprecated. I suggest you to use `spectralIndices()` instead! :rocket: 

Cheers!

Dave

**Comment by ckukund** [comment]
Very nice, @davemlz!

It is also cool to notice that ```spectralIndices()``` as well works with TOA data.

I computed BSI according to ([https://www.mdpi.com/2072-4292/9/12/1245](url)) and often use  [https://www.indexdatabase.de/db/i.php](url) as reference to many index equations. 

Sure, I will be happy to contribute some of the indices within my domain/research area to ``spectralIndices()``!

Kind regards, 
Collins
