### ISSUE TITLE
No non-system installation of Python could be found.

### ISSUE THREAD

**Issue by aloboa** [r-spatial/rgee#242]
* rgee version: 
rgee_1.1.3
* R version: 
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Pop!_OS 21.04

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

* Operating System: 
> Sys.info()
                                                           sysname 
                                                           "Linux" 
                                                           release 
                                        "5.15.11-76051511-generic" 
                                                           version 
"#202112220937~1640185481~21.04~b3a2c21-Ubuntu SMP Mon Jan 3 16:5" 
                                                          nodename 
                                                          "pop-os" 
                                                           machine 
                                                          "x86_64" 

### Description

```
> ee_install()
No non-system installation of Python could be found.
Would you like to download and install Miniconda?

```
Nevertheless, I do have miniconda installed and would prefer avoiding a second installation.

The help page mentions
For Miniconda users - Linux/MacOS users
`unix_py_path = paste0("/home/UNICORN/.local/share/r-miniconda/envs/", "rgee/bin/python3"`

but I do not have any r-miniconda directory.

**Comment by csaybar** [comment]
`rgee` use reticulate to find Python ENV paths. https://github.com/rstudio/reticulate/issues/1012
If it can not find them, you can set it manually creating an environment variable. In rgee we have a function to do that:

```r
rgee::ee_install_set_pyenv(
  py_path = "/home/csaybar/.virtualenvs/rgee/bin/python", # Change it for your own Python PATH
  py_env = "rgee" # Change it for your own Python ENV
)
```

**Comment by csaybar** [comment]
> but I do not have any r-miniconda directory.

The path is just a reference, users can change the anaconda/miniconda installation directory anytime. Take a look to the `ee_install_set_pyenv` documentation:

```r
help(ee_install_set_pyenv)

py_path	-> The path to a Python interpreter
py_env    -> The name of the conda or venv environment. If NULL, ee_install_upgrade and py_install functions will not work.
--

**Comment by aloboa** [comment]
Fresh RStudio session:

```
> require(reticulate)
Loading required package: reticulate
> py_discover_config()
No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]: n
Installation aborted.
python:         /usr/bin/python3
libpython:      /usr/lib/python3.9/config-3.9-x86_64-linux-gnu/libpython3.9.so
pythonhome:     //usr://usr
version:        3.9.5 (default, Nov 18 2021, 16:00:48)  [GCC 10.3.0]
numpy:          /home/alobo/.local/lib/python3.9/site-packages/numpy
numpy_version:  1.20.3

python versions found: 
 /usr/bin/python3
 /home/alobo/miniconda3/bin/python
 /home/alobo/miniconda3/envs/qgis_stable/bin/python
```

Instead, the "raw R" session (without RStudio, does not complain:
```
> require(reticulate)
Loading required package: reticulate
> py_discover_config()
python:         /usr/bin/python3
libpython:      /usr/lib/python3.9/config-3.9-x86_64-linux-gnu/libpython3.9.so
pythonhome:     //usr://usr
version:        3.9.5 (default, Nov 18 2021, 16:00:48)  [GCC 10.3.0]
numpy:          /home/alobo/.local/lib/python3.9/site-packages/numpy
numpy_version:  1.20.3

python versions found: 
 /usr/bin/python3
 /home/alobo/miniconda3/bin/python
 /home/alobo/miniconda3/envs/qgis_stable/bin/python
```

 
Console:
```
$ which python
/home/alobo/miniconda3/bin/python
$ which python3
/home/alobo/miniconda3/bin/python3

```

**Comment by aloboa** [comment]
I understand, but considering the last contribution to that issue is from  Jun 29, 2020
and the heavy dependency of rgee on reticulate, it would be useful if you could advice users
like me on what to do (besides trying to shake that issue in the reticulate repo) to be able of using
rgee (which is what I want to do). There has to be some way to circumvent the problem.

**Comment by csaybar** [comment]
Dear @aloboa you don't need to run either `ee_install` or `ee_install_set_pyenv`. If you `/usr/bin/python3` already have installed the `numpy` and `earthengine-api` you shouldn't have any problem. As https://github.com/rstudio/reticulate/issues/710
says just set the environment variable to prevent the miniconda prompt:

```
RETICULATE_MINICONDA_ENABLED=FALSE
```
See [this link](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Sys.setenv.html) to get more information about how to set an environment variable in R. Without a reproducible example, it is not possible to help you (this applies to everything).

```r
# Restart R
Sys.setenv(RETICULATE_MINICONDA_ENABLED=FALSE)
library(rgee)
ee_Initialize()
```

**Comment by aloboa** [comment]
Thanks!
The `Sys.setenv(RETICULATE_MINICONDA_ENABLED=FALSE)`
did the trick. I'm onboard now.
I suggest mentioning this command in the documentation for installing rgee. Despite being an issue related to reticulate, it
does affect users willing to install rgee.

**Comment by csaybar** [comment]
Hi @aloboa I don't agree with your suggestion (reticulate is not rgee! both are active packages so this little bug will most likely be fixed in the future), but we understand that the installation process can be a bit frustrating. 

We want to remark that the issue here was never related to the installation. 

> ee_install()
No non-system installation of Python could be found.
Would you like to download and install Miniconda?

Just selecting "no" here, would be enough to utilize reticulate without issues (**it was just a wrong reticulate prompt!**). We recommend adding "RETICULATE MINICONDA ENABLED=FALSE" to your .Renviron to avoid running "Sys.setenv" every time R is initialized.

**Comment by csaybar** [comment]
Hi @aloboa, sorry but, we don't agree with this suggestion (reticulate is not rgee! both are active packages so this little bug will most likely be fixed in the future), but we understand that the installation process can be a bit frustrating. 

We want to remark that the issue here was never related to the installation. 

> ee_install()
No non-system installation of Python could be found.
Would you like to download and install Miniconda?

Just selecting "no" here, would be enough to utilize reticulate without issues (**it was just a wrong reticulate prompt!**). We recommend adding "RETICULATE MINICONDA ENABLED=FALSE" to your .Renviron to avoid running "Sys.setenv" every time R is initialized.

**Comment by aloboa** [comment]
@csaybar, do not want to make you waste your time, but I do want to show the user's point of view.

> Just selecting "no" here, would be enough to utilize reticulate without issue
But the user does not know that, just sees that something is going wrong

> We recommend adding "RETICULATE MINICONDA ENABLED=FALSE" to your .Renviron to avoid running "Sys.setenv" every time R is initialized.
Perfect!, but I just suggest putting that recommendation where it is most useful for the users. Perhaps not at the installation section, but at the 1st run. Note that while reticulate has a very dynamic development, this particular issue, that affects rgee, is 2 y old.
Anyway, having said that, the decision is up to you and, again, do not think you have to invest more time discussing this issue.
Many thanks for your work.

**Comment by csaybar** [comment]
Hi @aloboa, not all Linux users experience this issue (this is a very particular case, which unfortunately you have had to experience). As you may have noticed, reticulate has hundreds of open issues regarding the installation (and each one is unique).  Including all of these isolated one-off cases in the rgee documentation would be too much work for us.

We believe that [rgee/issues](https://github.com/r-spatial/rgee/issues/) is a more appropriate space, as people can attempt to solve the problem on their own. We always try to help all users, but if a bug is impossible for us to reproduce, assisting becomes very hard. I hope this helps to understand our position related to installation issues and sorry for the inconvenience!
