### ISSUE TITLE
Security concern with permissions to Tidyverse API Packages for ee_as_raster()

### ISSUE THREAD

**Issue by aloboa** [r-spatial/rgee#246]
I understand that, in order to be able of using `ee_as_raster() `and similar functions, I must run
`ee_Initialize(drive=TRUE)`

I am bit concerned about having to let Tidyverse API Packages
"See, edit, create, and delete all of your Google Drive files"
Could this be a security risk? 
Is this permission forever or just for the current session?
Are edit and delete really needed? I would prefer having to manually clean up my drive afterwards.
Would that be possible?

**Comment by csaybar** [comment]
> Could this be a security risk?

Hi @aloboa, **googledrive** via [gargle](https://gargle.r-lib.org/index.html) create a *service account token* that will give you privileges to edit, create, and delete GD files. But this **token will never leave your computer**, so there shouldn't be any security issues unless you share your key with someone else.  However, if you run a certain script, you could delete all your GD files!, it's the same as running, for example, a bash bomb `:(){ :|: & };:` with root privileges in Linux.

> Is this permission forever or just for the current session?

you probably need to refresh your token if there is an important change in the GD API.

> Are edit and delete really needed?

We only need delete privileges in `ee_clean_container` function, all the other functions don't need it.

> Would that be possible?

Yes of course, `ee_as_raster` just needs reading privileges.

Remenber that:

- ee_as_raster:  move data from EE -> GD -> local.

but you can use:

- ee_image_to_drive: move data from EE -> GD
- ee_drive_to_local: move data from GD -> local.

**Comment by aloboa** [comment]
But both in `ee_as_raster() `and `ee_image_to_drive()` the examples from the documentation start by
`ee_Initialize(drive = TRUE)`
which opens a window in which I do not see how I can grant reading permissions only, it is everything or nothing:

![image](https://user-images.githubusercontent.com/6074054/158759905-87962b21-e224-436c-a1a2-a27bf1f40287.png)

**Comment by csaybar** [comment]
@aloboa rgee depends on googledrive, and it seems that it does not support this feature with the Oauth app prompt (idk why). However, if you need more flexibility you can create a [service account token](https://developers.google.com/identity/protocols/oauth2/scopes) to define the IAM policy you desire. Something like this should work:

```
library(rgee)
library(googledrive)

ee_Initialize()

# use a service account token
drive_auth(path = "foofy-83ee9e7c9c48.json")


```

**Comment by aloboa** [comment]
Cesar,
I have checked that link. I understand the section rgee users would need is [Drive API](https://developers.google.com/drive), v3 , but
I'm frankly overwhelmed for a tide of information that I do not understand. How did you get the token you include in your example? I've not been able to find it.

By looking at `?drive_auth()`, I have tried:
```
## use a 'read only' scope, so it's impossible to edit or delete files
drive_auth(
  scopes = "https://www.googleapis.com/auth/drive.readonly"
)
```
I'm prompted:
```
→ Is it OK to cache OAuth access credentials in the folder ~/.cache/gargle between R sessions?
1: Yes
2: No

```
I select 2 (not knowing too much what I'm doing)
and I get a panel in the browser in which I can authorize Tidyverse API Packages to 
"see and download all your Google Drive files" (which is what I want, I think).

Unfortunately, when I try
`testima <- ee_as_raster(image)`

I get again the panel where I am asked to authorize Tidyverse API Packages to
"See, edit, create, and delete all of your Google Drive files"

Regarding
```
## use a service account token
drive_auth(path = "foofy-83ee9e7c9c48.json")
```
I do not really see where/how to get that token.

**Comment by csaybar** [comment]
Hi @aloboa I need to investigate a bit more this, but I agree that users should have the option to control privileges. If my memory serves me well, this was a feature from older versions of googledrive (R package).


> I'm frankly overwhelmed by a tide of information that I do not understand. How did you get the token you include in your example? I've not been able to find it.

Unfortunately, this is something that must be done outside R.

**Comment by aloboa** [comment]
In order to circumvent the problem, by now I'm using
`ee_image_to_asset()`
for a set of images and then go to the GEE gui to 
save them from asset to a locally synced folder in drive.
I wonder if you could not use `Export.image.toDrive() `from within rgee,
bypassing the R package googledrive (I do not need to
save data from R to drive, but from GEE assets to drive. Then I can read
those files into R from the local folder). But I'm a total ignorant on these issues.

**Comment by darabihamid** [comment]
Hi,
I have got this error when I want to use rgee!!
Access blocked: Tidyverse API Packages’s request is invalid


You can’t sign in because Tidyverse API Packages sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of Tidyverse API Packages, see [error details](https://accounts.google.com/).
Error 400: invalid_request.
I would appreciate it if some one could help me.
Thanks
