### ISSUE TITLE
package or namespace load failed -- .Rdata

### ISSUE THREAD

**Issue by tcalegario** [r-spatial/rgee#247]
* rgee version: 1.1.3
* R version: 4.1.0
* Operating System: Windows 10

#### At submit an issue, please attached the following information of your `rgee` session:

- [ No] You have the Python API installed (from terminal):
```
earthengine -h
```

- [No] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
```
- [depends] You can run a simple EE command from R: 

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())
``` 

Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()
```

![image](https://user-images.githubusercontent.com/28005796/158862317-947fed4c-9008-4f6f-849a-2761c6e58205.png)

### Description

Hi. Im working with rgee and it works perfectly, but when i save my project, close it and open again loadin rgee i get this "Loadspace error".

![image](https://user-images.githubusercontent.com/28005796/158861484-56118ba2-6f9f-4af8-aaa2-0c7b2a35a3f0.png)

When i try it in other new project, even in parallel, it work perfectly.

![image](https://user-images.githubusercontent.com/28005796/158861275-99bb32af-1baf-49a0-b27a-acf462f97799.png)

Suggestions?

Thanks

**Comment by tcalegario** [comment]
Using old project i got this:

![image](https://user-images.githubusercontent.com/28005796/158878070-3d0dbc12-47de-4178-a353-92a5c430c3e1.png)

Using new project:

![image](https://user-images.githubusercontent.com/28005796/158878130-02252855-2855-4c54-bf95-00494a345ccf.png)

**Comment by tcalegario** [comment]
Tool -> Global options -> python -> select python interpreter -> conda-> choose rgee env.

**Comment by csaybar** [comment]
Hi @tcalegario, what do you mean with save a project?. If you create a `.Rdata` remember that you can not save the `reticulate` pointers. 

> Tool -> Global options -> python -> select python interpreter -> conda-> choose rgee env.

You don't need to do this if you set your Python ENV with `ee_install` or `ee_install_set_pyenv` (.Renviron).
