### ISSUE TITLE
Add option to enable the high-volume endpoint instead of the default endpoint

### ISSUE THREAD

**Issue by SvenVw** [r-spatial/rgee#252]
Hi, when making automated requests to Earth Engine it advised to use the high-volume endpoint instead of the default endpoint (https://developers.google.com/earth-engine/cloud/highvolume). At the moment it looks like `ee_Initialize`  always uses the default endpoint. Would it be possible to enable the use of the high-volume endpoint by for example adding an extra argument to `ee_Initialize`. If needed, I can submit a PR as a proposal.

**Comment by csaybar** [comment]
Hi @SvenVw this looks great, I will apply it to the high QPS, after that, I will try to add this new feature. Please a PR would be very helpful :pray: Thanks! :)

**Comment by csaybar** [comment]
Hi, it was solved now!
