### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) :  AttributeError: module 'collections' has no attribute 'Callable' during ee_Initialize()

### ISSUE THREAD

**Issue by olehprylutskyi** [r-spatial/rgee#256]
* rgee version: 1.1.3.9000
* R version: 4.1.2
* Operating System: Ubuntu 22.04 LTS
* Python (reticulate) configuration:

```
> py_config()
python:         /home/oleh/.virtualenvs/rgee/bin/python
libpython:      /usr/lib/python3.10/config-3.10-x86_64-linux-gnu/libpython3.10.so
pythonhome:     /home/oleh/.virtualenvs/rgee:/home/oleh/.virtualenvs/rgee
version:        3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
numpy:          /home/oleh/.virtualenvs/rgee/lib/python3.10/site-packages/numpy
numpy_version:  1.22.3
ee:             /home/oleh/.virtualenvs/rgee/lib/python3.10/site-packages/ee
```

Hello! I have successfully installed and set up `rgee` package, as well as the `earthengine` environment.` ee_check()` confirms successful installation. But when I try `ee_Initialize()`, it results in an Error message:

```
> ee_Initialize()
── rgee 1.1.3.9000 ─────────────────── earthengine-api 0.1.307 ── 
 ✔ user: not_defined
 ✔ Initializing Google Earth Engine:Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: module 'collections' has no attribute 'Callable'
```
I suppose that happened due to some Python issues, but, as a weak Python user, need help.
With previous version of Ubuntu (21.10) everything was Okay.

**Comment by csaybar** [comment]
Sorry for the late reply,

It seems it is a bug in Python 3.10 
https://stackoverflow.com/questions/69515086/beautifulsoup-attributeerror-collections-has-no-attribute-callable
Probably it has been solved now.

Let me know if the issue persist.
