### ISSUE TITLE
 reduceRegions not adding property to Feature Collection

### ISSUE THREAD

**Issue by btavernia** [r-spatial/rgee#258]
* rgee version: 1.1.3
* R version: 4.1.2
* Operating System: Windows (64-bit)

The rgee session indicates that I have earthengine-api 0.1.302.  

I have been able to locate the credentials file on my system:

C:\Users\Brian.Tavernia\.config\earthengine\credentials

I have been able to run simply EE commands from R (e.g., reading Feature and Image Collections).

My Python (reticulate configuration is:

python:         C:/Users/Brian.Tavernia/AppData/Local/r-miniconda/envs/rgee/python.exe
libpython:      C:/Users/Brian.Tavernia/AppData/Local/r-miniconda/envs/rgee/python38.dll
pythonhome:     C:/Users/Brian.Tavernia/AppData/Local/r-miniconda/envs/rgee
version:        3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:00) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/Brian.Tavernia/AppData/Local/r-miniconda/envs/rgee/Lib/site-packages/numpy
numpy_version:  1.22.3
ee:             C:\Users\BRIAN~1.TAV\AppData\Local\R-MINI~1\envs\rgee\lib\site-packages\ee\__init__.p

### Description

I am attempting to use reduceRegions to determine the mean value for band 10 from Landsat 8 for polygons representing US cities.  
The returned FeatureCollection does not have the mean property attribute.  There is no error thrown, the FeatureCollection simply does not have the mean property.  

### What I Did

#Getting temperature band from Landsat 8
start <- ee$Date$fromYMD(2021,6,1) #Start date for filtering
end <- ee$Date$fromYMD(2021,9,30) #End date for filtering

imgC <- ee$ImageCollection("LANDSAT/LC08/C02/T1_L2")%>% #Landsat 8
  ee$ImageCollection$filterDate(start,end)%>% #filtering by date
  ee$ImageCollection$map(qFn) #Masking image collection

l8 <- imgC$select("ST_B10")%>% #Selecting thermal band
  ee$ImageCollection$median()%>% #Getting image by taking median
  ee$Image$clip(city)#Clipping image to city boundaries

l8m <- l8$multiply(0.00341802)$add(149.0)%>% #Converting to Kelvin
  ee$Image$set('yr',end$format('YYYY')) #Setting year property

#Calculating mean of cities - tempMean feature collection does not contain a mean property
tempMean = l8ma$reduceRegions(
  
  collection = city,
  reducer = ee$Reducer$mean(),
  scale = 30
  
)

ee_print(tempMean)

**Comment by ambarja** [comment]
Hello @btavernia, please Can you share your featurecollection (`city`)? 
Also, I recommend you to use [`ee_extract`](https://r-spatial.github.io/rgee/reference/ee_extract.html) function instead of  `Reduce$Region`

**Comment by btavernia** [comment]
Note that I tried ee_extract, and it did not return the mean. 

Here's the link to the asset.

https://code.earthengine.google.com/?asset=projects/ee-btavernia/assets/tl_2021_us_uac10_1_500

I appreciate your assistance.

**Comment by ambarja** [comment]
@btavernia  Here is a reproducible code :point_down:  , to extract the value take 2 min max
```r
library(rgee)
library(tidyverse)
ee_Initialize()

# Reading featurecollection
city <- ee$FeatureCollection("projects/ee-btavernia/assets/tl_2021_us_uac10_1_500")

# Getting temperature band from Landsat 8
start <- ee$Date$fromYMD(2021,6,1) # Start date for filtering
end <- ee$Date$fromYMD(2021,9,30)  # End date for filtering

imgC <- ee$ImageCollection("LANDSAT/LC08/C02/T1_L2") %>% 
  ee$ImageCollection$filterDate(start,end) %>% 
  # ee$ImageCollection$map(qFn) 

l8 <- imgC$select("ST_B10") %>%   # Selecting thermal band
  ee$ImageCollection$median() %>% # Getting image by taking median
  ee$Image$clip(city)             # Clipping image to city boundaries

l8m <- l8$multiply(0.00341802)$add(149.0)%>% # Converting to Kelvin
  ee$Image$set('yr',end$format('YYYY'))      # Setting year property

# Calculating mean of cities - tempMean feature collection does not contain a mean property

data_city <- ee_extract(
  x = l8m,
  y = city,
  sf = TRUE,
  fun = ee$Reducer$mean(),
  scale = 30
)
```

**Comment by btavernia** [comment]
Thanks!  This works.  It doesn't work when I map the user-defined qFn function on image collection (which is commented out in the code above).  I developed this function (and bitwise function) to mask shadow, cloud, and snow from the images.  Any notion why the user defined functions might be causing an issue?  

#Helper function to extract the values from specific bits
#The input parameter can be a ee.Number() or ee.Image()
#Code adapted from https://gis.stackexchange.com/a/349401/5160

bitwiseExtract <- function(input,fromBit,toBit){
  
  maskSize <- ee$Number(1)$add(toBit)$subtract(1)
  mask <- ee$Number(1)$leftShift(maskSize)$subtract(1)
  input$rightShift(fromBit)$bitwiseAnd(mask)
  
}

#Function to mask cloud, shadow, and snow pixels
qFn <- function(image){
  
  qCdata <- image$select("QA_PIXEL")
  cloudMask <- bitwiseExtract(qCdata,6,6)$eq(1)
  shadowMask <- bitwiseExtract(qCdata,4,4)$eq(0)
  snowMask <- bitwiseExtract(qCdata,5,5)$eq(0)
  mask <- cloudMask$And(shadowMask)$And(snowMask)
  image$updateMask(mask)
  
}
