### ISSUE TITLE
ee_Initialize in a non-interactive R session

### ISSUE THREAD

**Issue by poniitty** [r-spatial/rgee#265]
* rgee version: 1.1.0
* R version: 4.1.1
* Operating System: Linux 64-bit

Thanks for the great resource!

I have a workflow in R including download of rasters from GEE via Google Drive.

Everything runs perfectly when running the code interactively in RStudio but I'm running into troubles when trying to run the R code via SLURM on the same super-cluster it works otherwise.

The problem seems to be that the `ee_Initialize()` fails to find the Google Drive credentials when in non-interactive mode.

Is there any way to work around this issue?

I have tried to go through the _rgee_ and _googledrive_ references, but not really figuring out if there is somenthing I could do.

Here is the error message I got printed out.

```
> Error in `googledrive::drive_auth()`:
> ! Can't get Google credentials
> i Are you running googledrive in a non-interactive session? Consider:
> * `drive_deauth()` to prevent the attempt to get credentials
> * Call `drive_auth()` directly with all necessary specifics
> i See gargle's "Non-interactive auth" vignette for more details:
> i <https://gargle.r-lib.org/articles/non-interactive-auth.html>
> Backtrace:
>     x
>  1. \-rgee::ee_Initialize(drive = T)
>  2.   \-rgee:::ee_create_credentials_drive(user, quiet = quiet)
>  3.     +-base::suppressMessages(...)
>  4.     | \-base::withCallingHandlers(...)
>  5.     \-googledrive::drive_auth(email = email, cache = ee_path_user)
>  6.       \-googledrive:::drive_abort(...)
>  7.         \-cli::cli_abort(message = message, ..., .envir = .envir)
>  8.           \-rlang::abort(message, ..., call = call, use_cli_format = TRUE)
```

**Comment by csaybar** [comment]
I think it is not possible directly with rgee/Python API. A workaround would be to preload the credentials of Earth Engine and Google Drive. See https://github.com/csaybar/rgee-docker/blob/2aaf780c51ceec70ec42cda936cc7b7cbadaa3d5/Dockerfile#L97
