### ISSUE TITLE
Error in array$arrayLength : object of type 'closure' is not subsettable

### ISSUE THREAD

**Issue by TianyaImpression** [r-spatial/rgee#277]
* rgee version: 1.1.3
* R version: 4.2.1
* Operating System: win10

I tried this example:
https://github.com/csaybar/rgee/blob/examples//Array/array_transformations.R

I get an error when running this line of code
`array <- collection$map(makeVariables)$toArray()`

![image](https://user-images.githubusercontent.com/22004043/182084468-5619167b-8abe-496e-99b1-1fe49af55487.png)

I want to know where is the problem and how to solve it.

Thank you!

**Comment by csaybar** [comment]
Sorry, my bad just change "image" by "img". I did 
![image](https://user-images.githubusercontent.com/16768318/193427138-a61ebb40-f9db-452f-9e7f-d8c7c602b29b.png)
