### ISSUE TITLE
Image collection  `COPERNICUS/S2_SR`  considering changes in band data after 25 Jan 2022 

### ISSUE THREAD

**Issue by Leprechault** [r-spatial/rgee#279]
Hi Everyone!!

I'd like the BOA extraction in my target area in a temporal series from 2019 to today. The "ee_extract" using image collection  `COPERNICUS/S2_SR` considering updating the Sentinel-2 processing baseline 44 in January 2022 or some baseline transformation is needed?
Thanks in advance,
Alexandre

**Comment by csaybar** [comment]
I think `COPERNICUS_S2_SR_HARMONIZED` is what you are looking for!!

https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_SR_HARMONIZED

**Comment by Leprechault** [comment]
Thanks @csaybar and this explains a lot of strange values in my dataset this year!!
