### ISSUE TITLE
Initializing rgee on M1 Mac

### ISSUE THREAD

**Issue by grantfalvo** [r-spatial/rgee#280]
Hello, 

I recently failed to install and use 'rgee' on my M1 Mac and ran out of ideas after trouble shooting it for a while. 

Simply, when I run rgee::ee_install(), it starts up but fails at the 'Building wheel for numpy (PEP 517)' step and gives the message:

'ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly'

Any ideas on how to resolve this? 

Thanks much.

python:         /usr/bin/python3    #version 3.8.2
RStudio: 2022.02.3+492
R: 4.1.3 Big Sur ARM build

**Comment by csaybar** [comment]
Deeply sorry I never use mac :c, but it looks like a problem on the Python side I hope you have solved it
