### ISSUE TITLE
MODIS raster data acquired with projection problem

### ISSUE THREAD

**Issue by rokoeh** [r-spatial/rgee#281]
* rgee version: rgee 1.1.4
* R version: 4.2.1
* Operating System: Win 10

Hello

I was trying to download MODIS data from product MOD13Q1 and I am facing a projection problem. The data that I downloaded using ee_as_raster came with an offset. It is not in the same area of my FeatureCollection.

```r
require(rgee)
ee_Initialize(drive = TRUE)
mod09q1 <- ee$ImageCollection$Dataset$MODIS_006_MOD09Q1$filterDate("2022-06-01","2022-06-08")
shp<-ee$FeatureCollection("users/******/test1")
start <- ee$Date("2022-06-01")
end <- ee$Date("2022-06-08")
filter<-mod09q1$filterDate(start,end)
img <- filter$first()
img<-img$clip(shp)
img_b1<-img$select(c("sur_refl_b01"))
img_b2<-img$select(c("sur_refl_b02"))
img_qa<-img$select(c("QA"))
Map$setCenter(-46.8,-12.8, zoom = 7)
Map$addLayer(img,
             visParams=list(bands = c("sur_refl_b01", "sur_refl_b02"), min =100, max = 8000, gamma = c(1.9,1.7)),
             "False Color Image") 
ee_raster <- ee_as_raster(
  image = img_b1,
  region = shp$geometry(),
  dsn = "D:/temp/gee/test1_b1.tif",
  via = "drive"
)
```
Shapefile used in this test:
[test1.zip](https://github.com/r-spatial/rgee/files/9303790/test1.zip)

Results:

![p1](https://user-images.githubusercontent.com/13200656/184013753-e76980f3-268b-4f9f-be20-162c6293eba9.png)

![p2](https://user-images.githubusercontent.com/13200656/184013801-49006575-d2ea-4f76-982a-90af90eff7c4.png)

![p3](https://user-images.githubusercontent.com/13200656/184013844-b240c71d-634e-436d-b29f-a7241b5db399.png)

With best regards

**Comment by ambarja** [comment]
Excellent observation @rokoeh, but MODIS usually works with the Sinusual projection, however it can be solved using the following :point_down: 

```r
ee_raster <- ee_as_raster(
  image = img_b1$reproject('EPSG:4326', NULL, 500),
  region = shp,
  dsn = "/home/am/Imágenes/modis.tif",
  via = "drive"
  )
```

**Comment by rokoeh** [comment]
That did it. Thank you.
