### ISSUE TITLE
Error in In ee_install()

### ISSUE THREAD

**Issue by wilson733** [r-spatial/rgee#309]
### Description

Hi, iam new in RGEE, i wanted to intalate but an error stopped me. Can someone help me?

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
> library(reticulate)
> library(rgee)
> # Use the py_discover_config() function to see what version of Python will be
> # used without actually loading Python (no initialize R-Python connection!)
> py_discover_config()
python:         C:/Users/win10/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/win10/AppData/Local/r-miniconda/envs/r-reticulate/python38.dll
pythonhome:     C:/Users/win10/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:42:03) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/win10/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.24.1
> # Use the py_config() function to query for information about the specific 
> # version of Python IN USE as well as a list of other Python versions discovered
> # on the system. (initialize R-Python connection!)
> py_config()
python:         C:/Users/win10/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/win10/AppData/Local/r-miniconda/envs/r-reticulate/python38.dll
pythonhome:     C:/Users/win10/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:42:03) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/win10/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.24.1
> # Verify current Python path 
> import("sys")$executable
[1] "C:/Users/win10/AppData/Local/r-miniconda/envs/r-reticulate/python.exe"
> # >>> rgee needs that the Python version IN USE is Python3.
> # >>> rgee (reticulate) needs that your system is x64 rather than x86.
> # >>> If you are a Window users, rgee (reticulate) needs conda environment (see
> #     https://docs.conda.io/en/latest/miniconda.html), linux or MacOS users could
> #     use either virtualenv or conda.
> use_python("C:/Users/win10/AppData/Local/r-miniconda/envs/r-reticulate/python.exe")
> # -------------------------------
> # 4. Set a Python Env to rgee
> # -------------------------------
> ee_install()
─────────────────────────────────────────────────────────────────────────────────── Python configuration used to create rgee ──
python:         C:/Users/win10/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/win10/AppData/Local/r-miniconda/envs/r-reticulate/python38.dll
pythonhome:     C:/Users/win10/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:42:03) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/win10/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.24.1
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
1. Removing the previous Python Environment (rgee), if it exists ...
+ "C:/Users/win10/AppData/Local/r-miniconda/condabin/conda.bat" "remove" "--yes" "--name" "rgee" "--all"

2. Creating a Python Environment (rgee)
+ "C:/Users/win10/AppData/Local/r-miniconda/condabin/conda.bat" "create" "--yes" "--name" "rgee" "python=3.8" "--quiet" "-c" "conda-forge"
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\win10\AppData\Local\R-MINI~1\envs\rgee

  added / updated specs:
    - python=3.8

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4 
  ca-certificates    conda-forge/win-64::ca-certificates-2022.12.7-h5b45459_0 
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5 
  libsqlite          conda-forge/win-64::libsqlite-3.40.0-hcfcfb64_0 
  libzlib            conda-forge/win-64::libzlib-1.2.13-hcfcfb64_4 
  openssl            conda-forge/win-64::openssl-3.0.7-hcfcfb64_1 
  pip                conda-forge/noarch::pip-22.3.1-pyhd8ed1ab_0 
  python             conda-forge/win-64::python-3.8.15-h4de0772_0_cpython 
  setuptools         conda-forge/noarch::setuptools-65.6.3-pyhd8ed1ab_0 
  tk                 conda-forge/win-64::tk-8.6.12-h8ffe710_0 
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0 
  vc                 conda-forge/win-64::vc-14.3-h3d8a991_9 
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.32.31332-h1d6e394_9 
  wheel              conda-forge/noarch::wheel-0.38.4-pyhd8ed1ab_0 
  xz                 conda-forge/win-64::xz-5.2.6-h8d14728_0 

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

rgee::ee_install want to store the environment variables: EARTHENGINE_PYTHON 
and EARTHENGINE_ENV in your .Renviron file to use the Python path:
C:\Users\win10\AppData\Local\r-miniconda\envs\rgee/python.exe in future sessions.
Would you like to continues? [Y/n]:y

3. The Environment Variables: 'EARTHENGINE_PYTHON=C:\Users\win10\AppData\Local\r-miniconda\envs\rgee/python.exe' and 'EARTHENGINE_ENV=rgee'
were saved in the .Renviron (C:/Users/win10/Documents/.Renviron) file. Remember that you
could remove EARTHENGINE_PYTHON and EARTHENGINE_ENV using rgee::ee_clean_pyenv().

4. Installing the earthengine-api. Running: 
reticulate::py_install(packages = 'earthengine-api', envname = 'C:/Users/win10/AppData/Local/r-miniconda/envs/rgee')

+ "C:/Users/win10/AppData/Local/r-miniconda/condabin/conda.bat" "install" "--yes" "--prefix" "C:/Users/win10/AppData/Local/r-miniconda/envs/rgee" "-c" "conda-forge" "earthengine-api" "numpy"
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\win10\AppData\Local\r-miniconda\envs\rgee

  added / updated specs:
    - earthengine-api
    - numpy

The following NEW packages will be INSTALLED:

  aiohttp            conda-forge/win-64::aiohttp-3.8.3-py38h91455d4_1 
  aiosignal          conda-forge/noarch::aiosignal-1.3.1-pyhd8ed1ab_0 
  async-timeout      conda-forge/noarch::async-timeout-4.0.2-pyhd8ed1ab_0 
  attrs              conda-forge/noarch::attrs-22.2.0-pyh71513ae_0 
  brotlipy           conda-forge/win-64::brotlipy-0.7.0-py38h91455d4_1005 
  c-ares             conda-forge/win-64::c-ares-1.18.1-h8ffe710_0 
  cachetools         conda-forge/noarch::cachetools-5.2.0-pyhd8ed1ab_0 
  certifi            conda-forge/noarch::certifi-2022.12.7-pyhd8ed1ab_0 
  cffi               conda-forge/win-64::cffi-1.15.1-py38h57701bc_3 
  charset-normalizer conda-forge/noarch::charset-normalizer-2.1.1-pyhd8ed1ab_0 
  cryptography       conda-forge/win-64::cryptography-39.0.0-py38h95f5157_0 
  earthengine-api    conda-forge/noarch::earthengine-api-0.1.334-pyhd8ed1ab_1 
  frozenlist         conda-forge/win-64::frozenlist-1.3.3-py38h91455d4_0 
  future             conda-forge/noarch::future-0.18.2-pyhd8ed1ab_6 
  google-api-core    conda-forge/noarch::google-api-core-2.11.0-pyhd8ed1ab_0 
  google-api-python~ conda-forge/noarch::google-api-python-client-2.71.0-pyhd8ed1ab_0 
  google-auth        conda-forge/noarch::google-auth-2.15.0-pyh1a96a4e_0 
  google-auth-httpl~ conda-forge/noarch::google-auth-httplib2-0.1.0-pyhd8ed1ab_1 
  google-cloud-core  conda-forge/noarch::google-cloud-core-2.3.2-pyhd8ed1ab_0 
  google-cloud-stor~ conda-forge/noarch::google-cloud-storage-2.7.0-pyh1a96a4e_0 
  google-crc32c      conda-forge/win-64::google-crc32c-1.1.2-py38h40ab01b_4 
  google-resumable-~ conda-forge/noarch::google-resumable-media-2.4.0-pyhd8ed1ab_0 
  googleapis-common~ conda-forge/noarch::googleapis-common-protos-1.57.1-pyhd8ed1ab_0 
  grpcio             conda-forge/win-64::grpcio-1.51.1-py38head4879_0 
  httplib2           conda-forge/noarch::httplib2-0.21.0-pyhd8ed1ab_0 
  idna               conda-forge/noarch::idna-3.4-pyhd8ed1ab_0 
  intel-openmp       conda-forge/win-64::intel-openmp-2023.0.0-h57928b3_25922 
  libabseil          conda-forge/win-64::libabseil-20220623.0-cxx17_h1a56200_6 
  libblas            conda-forge/win-64::libblas-3.9.0-16_win64_mkl 
  libcblas           conda-forge/win-64::libcblas-3.9.0-16_win64_mkl 
  libcrc32c          conda-forge/win-64::libcrc32c-1.1.2-h0e60522_0 
  libgrpc            conda-forge/win-64::libgrpc-1.51.1-h6a6baca_0 
  libhwloc           conda-forge/win-64::libhwloc-2.8.0-h039e092_1 
  libiconv           conda-forge/win-64::libiconv-1.17-h8ffe710_0 
  liblapack          conda-forge/win-64::liblapack-3.9.0-16_win64_mkl 
  libprotobuf        conda-forge/win-64::libprotobuf-3.21.12-h12be248_0 
  libxml2            conda-forge/win-64::libxml2-2.10.3-hc3477c8_1 
  mkl                conda-forge/win-64::mkl-2022.1.0-h6a75c08_874 
  multidict          conda-forge/win-64::multidict-6.0.4-py38h91455d4_0 
  numpy              conda-forge/win-64::numpy-1.24.1-py38h90ce339_0 
  protobuf           conda-forge/win-64::protobuf-4.21.12-py38hd3f51b4_0 
  pthreads-win32     conda-forge/win-64::pthreads-win32-2.9.1-hfa6e2cd_3 
  pyasn1             conda-forge/noarch::pyasn1-0.4.8-py_0 
  pyasn1-modules     conda-forge/noarch::pyasn1-modules-0.2.7-py_0 
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0 
  pyopenssl          conda-forge/noarch::pyopenssl-23.0.0-pyhd8ed1ab_0 
  pyparsing          conda-forge/noarch::pyparsing-3.0.9-pyhd8ed1ab_0 
  pysocks            conda-forge/noarch::pysocks-1.7.1-pyh0701188_6 
  python_abi         conda-forge/win-64::python_abi-3.8-3_cp38 
  pyu2f              conda-forge/noarch::pyu2f-0.1.5-pyhd8ed1ab_0 
  re2                conda-forge/win-64::re2-2022.06.01-h0e60522_1 
  requests           conda-forge/noarch::requests-2.28.1-pyhd8ed1ab_1 
  rsa                conda-forge/noarch::rsa-4.9-pyhd8ed1ab_0 
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0 
  tbb                conda-forge/win-64::tbb-2021.7.0-h91493d7_1 
  typing-extensions  conda-forge/noarch::typing-extensions-4.4.0-hd8ed1ab_0 
  typing_extensions  conda-forge/noarch::typing_extensions-4.4.0-pyha770c72_0 
  uritemplate        conda-forge/noarch::uritemplate-4.1.1-pyhd8ed1ab_0 
  urllib3            conda-forge/noarch::urllib3-1.26.13-pyhd8ed1ab_0 
  win_inet_pton      conda-forge/noarch::win_inet_pton-1.1.0-pyhd8ed1ab_6 
  yarl               conda-forge/win-64::yarl-1.8.2-py38h91455d4_0 
  zlib               conda-forge/win-64::zlib-1.2.13-hcfcfb64_4 

Downloading and Extracting Packages

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

Well done! rgee has been successfully installed on your system.
You need restart R to see changes (Windows users must terminate R!). After that, we recommend
running ee_check() to perform a full check of all non-R rgee dependencies.
Do you want restart your R session? 

1: yes
2: no

Selection: 1

Restarting R session...

> library(reticulate)
> library(rgee)
> # https://twitter.com/csaybar/status/1292015511547580416
> ee_Initialize("Wilson")
── rgee 1.1.6 ────────────────────────────────────────────────────────────────────────────────────── earthengine-api 0.1.334 ── 
 ✔ user: Wilson 
 ✔ Initializing Google Earth Engine:Fetching credentials using gcloud
Error in py_call_impl(callable, dots$args, dots$keywords) :
Exception: gcloud command not found. Please ensure that gcloud is installed.
More information: https://developers.google.com/earth-engine/guides/python_install

**Comment by csaybar** [comment]
Hi @wilson733 gcloud CLI is a Earth Engine dependency. Installed from: "https://developers.google.com/earth-engine/guides/python_install", restart your computer and try it again.

**Comment by wilson733** [comment]
> rgee::ee_Initialize(drive = T)
── rgee 1.1.6 ────────────────────────────────────────────────────────────────────────────────────── earthengine-api 0.1.335 ── 
 ✔ user: not_defined 
 ✔ Google Drive credentials:  FOUND
 ✔ Initializing Google Earth Engine:Fetching credentials using gcloud
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Exception: gcloud command not found. Please ensure that gcloud is installed.
More information: https://developers.google.com/earth-engine/guides/python_install

> library(rgee)
> ee_Authenticate(auth_mode='notebook')
 ✔ Initializing Google Earth Engine:
Enter verification code: 4/1AWgavdcrFK-2uIChEb2hTASlRSmUyLEQS2OBqdYFfA_cyT3Ibnmerp3xD6s
 ✔ Initializing Google Earth Engine:  DONE!
credentials are cached in the path: C:\Users\win10/.config/earthengine/
To authorize access needed by Earth Engine, open the following URL in a web browser and follow the instructions. If the web browser does not start automatically, please manually browse the URL below.

    https://code.earthengine.google.com/client-auth?scopes=https%3A//www.googleapis.com/auth/earthengine%20https%3A//www.googleapis.com/auth/devstorage.full_control&request_id=444LuXsv37fdyPcjLwKOg4B98qG24bl1rE0D1gB03bA&tc=b-QczjO0GWdcsvmiIpRQwMupfIsP2kP125a54eLXtqA&cc=_TbVM8d44r-fkSDGGxOw4vE3jp0FEd8l1zFyUkh83Cw

The authorization workflow will generate a code, which you should paste in the box below.

Successfully saved authorization token.

**Comment by wilson733** [comment]
> ee_check()
◉  Python version
✔ [Ok] C:/Users/win10/AppData/Local/r-miniconda/envs/rgee_py/python.exe v3.9
◉  Python packages:
✔ [Ok] numpy
✔ [Ok] earthengine-api
El sistema no puede encontrar la ruta especificada.
Error in ee_check_gcloud() : 
  gcloud failed [os.system('gcloud --help')]. Please check
      for any errors above and install gcloud if needed (https://cloud.google.com/sdk/docs/install).

**Comment by csaybar** [comment]
HI @wilson733 , ee_Initialize still no working?

**Comment by wilson733** [comment]
Ahh..ok i have to initialize next, i got it. It work, thanks!!!
