### ISSUE TITLE
ee_print Error in strsplit(code, ":") : non-character argument

### ISSUE THREAD

**Issue by TianyaImpression** [r-spatial/rgee#313]
* rgee version:1.1.5
* R version:4.2.2
* Operating System:win10

#### At submit an issue, please attached the following information of your `rgee` session:

- [Yes ] You have the Python API installed (from terminal):
```
earthengine -h
```

- [ Yes] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
```
- [Yes ] You can run a simple EE command from R: 

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())
``` 

Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()
```

### Description
I tried to use rgee to download terraclimate data, I use ee_print() to see the metadata, it failed.
```
library(rgee)

ee_Initialize(drive = T)

terraclimate = ee$ImageCollection('IDAHO_EPSCOR/TERRACLIMATE')
ee_print(terraclimate)
```
![image](https://user-images.githubusercontent.com/22004043/217016808-79a35740-7312-4d83-b43f-e10f17532a55.png)

I tried to see the MODIS ImageCollection metadata, it's ok.

![image](https://user-images.githubusercontent.com/22004043/217016917-4c78ec7c-7eb1-4728-8428-e4dfae5d2378.png)

I wonder if there is a bug in ee_print(). The Earth Engine Snippet of terraclimate data has an underscore. Is the underscore in front of the slash affecting the work of ee_print()?

![image](https://user-images.githubusercontent.com/22004043/217018373-353a2972-f4b5-4ef4-a04b-de61f3f1f5eb.png)

Thank you!

**Comment by csaybar** [comment]
Hi  @TianyaImpression, I just fixed this issue in the latest version. Thank you so much for reporting!

**Comment by TianyaImpression** [comment]
The bug didnot fixed. I updated rgee 1.1.6 and tried to ee_print terraclimate data again, it report error: Error in strsplit(code, ":") : object 'band_metadata' not found

**Comment by TianyaImpression** [comment]
> Hi @TianyaImpression, I just fixed this issue in the latest version. Thank you so much for reporting!

The bug didnot fixed. I updated rgee 1.1.6 and tried to ee_print terraclimate data again, it report error: Error in strsplit(code, ":") : object 'band_metadata' not found

**Comment by csaybar** [comment]
Deeply sorry for the late reply, I just fixed this. Please let us know if the problem persists. I will work on it ASAP.

**Comment by beatsandwich** [comment]
That fixed it. Thank you @csaybar !

**Comment by beatsandwich** [comment]
Hi @csaybar . I am receiving the original error from this thread: Error in strsplit(code, ":") : non-character argument

This only occurs for certain Images and Image Collections I've tried.

For instance, running either of these generates the error:
climate = ee$ImageCollection("OREGONSTATE/PRISM/Norm91m")
ee_print(climate)

clay = ee$Image("projects/soilgrids-isric/clay_mean")
ee_print(clay)

cdl = ee$ImageCollection('USDA/NASS/CDL')
ee_print(cdl)

But these do not generate the error:
cdl = ee$ImageCollection('USDA/NASS/CDL')$filterDate('2022-01-01','2022-12-31')$first()
ee_print(cdl)

Here is the traceback for one of the errors:
> ee_print(climate)
Error in strsplit(code, ":") : non-character argument
> traceback()
8: strsplit(code, ":")
7: tolower(strsplit(code, ":")[[1]][1])
6: ee_utils_get_crs(img_proj$crs)
5: ee_image_info(image = selected_img, compression_ratio = compression_ratio, 
       quiet = TRUE)
4: ee_print.ee.image.Image(eeobject = img, img_band = img_band, 
       time_end = time_end, compression_ratio = compression_ratio, 
       quiet = TRUE, clean = TRUE)
3: ee_print(eeobject = img, img_band = img_band, time_end = time_end, 
       compression_ratio = compression_ratio, quiet = TRUE, clean = TRUE)
2: ee_print.ee.imagecollection.ImageCollection(climate)
1: ee_print(climate)


gee version: 1.1.5
MacOS version: Ventura 13.2.1

**Comment by beatsandwich** [comment]
That should say 'rgee version' not 'gee version'
