### ISSUE TITLE
infinite loop when install rgee on ubuntu 22.04

### ISSUE THREAD

**Issue by Technew94** [r-spatial/rgee#314]
* rgee version: 1.1.5
* R version: 4.1.2
* Operating System: Ubuntu 22.04.1 LTS

#### At submit an issue, please attached the following information of your `rgee` session:

- [ ] You have the Python API installed (from terminal):
```
earthengine -h
```
usage: earthengine [-h] [--ee_config EE_CONFIG] [--service_account_file SERVICE_ACCOUNT_FILE] [--project PROJECT_OVERRIDE]
                   {authenticate,acl,asset,cp,create,ls,licenses,du,mv,model,rm,set_project,task,unset_project,upload,upload_manifest,upload_table_manifest}
                   ...

Earth Engine Command Line Interface.

options:
  -h, --help            show this help message and exit
  --ee_config EE_CONFIG
                        Path to the earthengine configuration file. Defaults to "~/.config/earthengine/credentials".
  --service_account_file SERVICE_ACCOUNT_FILE
                        Path to a service account credentialsfile. Overrides any ee_config if specified.
  --project PROJECT_OVERRIDE
                        Specifies a Google Cloud Platform Project id to override the call.

Commands:
  {authenticate,acl,asset,cp,create,ls,licenses,du,mv,model,rm,set_project,task,unset_project,upload,upload_manifest,upload_table_manifest}
    authenticate        Prompts the user to authorize access to Earth Engine via OAuth2.
    acl                 Prints or updates the access control list of the specified asset.
    asset               Prints or updates metadata associated with an Earth Engine asset.
    cp                  Creates a new Earth Engine asset as a copy of another asset.
    create              Creates assets and folders.
    ls                  Prints the contents of a folder or collection.
    licenses            Prints the name and license of all third party dependencies.
    du                  Prints the size and names of all items in a given folder or collection.
    mv                  Moves or renames an Earth Engine asset.
    model               TensorFlow model related commands.
    rm                  Deletes the specified assets.
    set_project         Sets the default user project to be used for all API calls.
    task                Prints information about or manages long-running tasks.
    unset_project       UnSets the default user project to be used for all API calls.
    upload              Uploads assets to Earth Engine.
    upload_manifest     Uploads an image to Earth Engine using the given manifest file.
    upload_table_manifest
                        Uploads a table to Earth Engine using the given manifest file.

- [ ] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
```
> ee_path <- path.expand("~/.config/earthengine/credentials")
> file.exists(ee_path)
[1] FALSE

- [ ] You can run a simple EE command from R: 

not now, I'm stuck in initialize step.

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()
It doesn't work for me now.

# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())
``` 

Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()
```

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
when I type ee_Initialize(),

── rgee 1.1.5 ───────────────────────────────────────────────────────────────────────── earthengine-api 0.1.339 ── 
 ✔ user: not_defined
 ✔ Initializing Google Earth Engine:Fetching credentials using gcloud
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
Exception: gcloud command not found. Please ensure that gcloud is installed.
More information: https://developers.google.com/earth-engine/guides/python_install

ee_Initialize(gcs = TRUE)
── rgee 1.1.5 ───────────────────────────────────────────────────────────────────────── earthengine-api 0.1.339 ── 
 ✔ user: not_defined
 ✔ GCS credentials: NOT FOUND
 ✔ Initializing Google Earth Engine:Fetching credentials using gcloud
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
Exception: gcloud command not found. Please ensure that gcloud is installed.
More information: https://developers.google.com/earth-engine/guides/python_install

ee_check()
◉  Python version
✔ [Ok] /home/shuxin/.virtualenvs/rgee/bin/python v3.10
◉  Python packages:
✔ [Ok] numpy
✔ [Ok] earthengine-api
NOTE: The Earth Engine Python API version 0.1.339 is installed
correctly in the system but rgee was tested using the version
0.1.323. To avoid possible issues, we recommend install the
version used by rgee (0.1.323). You might use:
* rgee::ee_install_upgrade()
* reticulate::py_install('earthengine-api==0.1.323', envname='PUT_HERE_YOUR_PYENV')
* pip install earthengine-api==0.1.323 (Linux and Mac0S)
* conda install earthengine-api==0.1.323 (Linux, Mac0S, and Windows)

ee_get_earthengine_path()
Error in ee_get_earthengine_path() : 
  rgee_sessioninfo.txt does not exist, run rgee::ee_Initialize() to fixed.

```
Can anybody help me to solve this problem?
Thanks in advance!

**Comment by Technew94** [comment]
Solved by 
system("curl -sSL https://sdk.cloud.google.com | bash")

Thanks guys, please close this issue in your convenient.

**Comment by csaybar** [comment]
Hi @Technew94  are you using rgee dev version? The latest version does not need gcloud by default.

```
remotes::install_github("r-spatial/rgee")
```

**Comment by Technew94** [comment]
> Hi @Technew94 are you using rgee dev version? The latest version does not need gcloud by default.
> 
> ```
> remotes::install_github("r-spatial/rgee")
> ```

Hi there,

I think the problem occours because the mess up between conda and root env, but finally it works now followed by the guidence on the first page install guidence.

Thanks you so much~
