### ISSUE TITLE
Small typo in error message for Drive credentials

### ISSUE THREAD

**Issue by fBedecarrats** [r-spatial/rgee#318]
Hello, this is a very small error I'm reporting here. When the package has not been given the authorization to access Google Drive, it throws the following error: 
```
Error in test_drive_privileges(user) : 
  Your googledrive token does not have permission
to view or modify files from Google Drive.
Did you cross the check box when Google asked for permissions?
See: https://github.com/r-spatial/rgee/issues/175#issuecomment-905611278
Run **ee_clean_credentials('ndef')** to fix.
```
Note that there is a slight misspecification in the solution provided. The function should read `ee_clean_user_credentials('ndef')` and not `ee_clean_credentials('ndef')`. Many thanks for this great package!

**Comment by csaybar** [comment]
Hi, @fBedecarrats thanks I fixed this typo in the last release, please use:

```r
remotes::install_github("r-spatial/rgee")
```
