### ISSUE TITLE
Buy me a coffee doesn't work

### ISSUE THREAD

**Issue by fBedecarrats** [r-spatial/rgee#319]
Hi there and many thanks for this great package.
I wanted to support your efforts by using the buy me a coffee app, but I get the following error: "This Connect account cannot currently make live charges. The `requirements.disabled_reason` property on the account will provide information about why this account is currently disabled. If you are a customer trying to make a purchase, please contact the owner of this site. Your transaction has not been processed."
I'm just trying to pay with a standard French Visa card. Any adjustment to do on your side to enable visa payments?

**Comment by csaybar** [comment]
Hi @fBedecarrats, 

I made some changes in the app,  it should work now!

**Comment by fBedecarrats** [comment]
Yes, it works now. Many thanks for this package!

**Comment by csaybar** [comment]
very thank you for the coffee :D
