### ISSUE TITLE
ee.ee_exception.EEException: Request had insufficient authentication scopes.

### ISSUE THREAD

**Issue by qianmoeast** [r-spatial/rgee#350]
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  ee.ee_exception.EEException: Request had insufficient authentication scopes.

**Comment by jdbcode** [comment]
This sounds like you did not have the proper role on a cloud project to make the request. Please check what project you initialized with and whether you have permission to do the thing you'd like.

https://developers.google.com/earth-engine/cloud/roles_permissions
