### ISSUE TITLE
cannot remove prior installation of package ‘Rcpp’ when install rgee

### ISSUE THREAD

**Issue by xiaoxiaokuishu** [r-spatial/rgee#65]
when i used remotes::install_github("r-spatial/rgee") to install rgee. The below
error appears. Is there anyone know how to deal with it, actually i have not installed Rcpp before.

Error: Failed to install 'rgee' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘Rcpp’

Thanks

**Comment by csaybar** [comment]
Can you try installing Rcpp separately?. It does not seem a rgee problem. Maybe this could help.
https://stackoverflow.com/questions/45922418/error-in-install-packages-cannot-remove-prior-installation-of-package-dbi

**Comment by xiaoxiaokuishu** [comment]
> Can you try installing Rcpp separately?. It does not seem a rgee problem. Maybe this could help.
> https://stackoverflow.com/questions/45922418/error-in-install-packages-cannot-remove-prior-installation-of-package-dbi

Thanks for csaybar's comments. It is the 'Rcpp' problem, i have fixed it and it work now, thanks.
