### ISSUE TITLE
GEE export image is too large, how to make the image automatically export in blocks

### ISSUE THREAD

**Issue by hlepYU** [r-spatial/rgee#66]
When I output images, the request payload size exceeds the limit: 4194304 bytes. Below is the code and problem I am running. How to solve this problem? If the problem is because the image is too large, how can I automatically output the image in blocks.Thank you very much.
https://code.earthengine.google.com/f2b1d26221aba811fa4174ae06c6af8a
![image](https://user-images.githubusercontent.com/67032638/84844014-fbc9e500-b07b-11ea-8f43-4f63d79686c0.png)

**Comment by csaybar** [comment]
You can try increasing the argument MaxPixels. I have never tried but I think there is a maximum of 10 **13. If your data retrieve is higher than this threshold. A code like this could help:
```
library(sf)
library(rgee)

ee_Initialize()

my_img <- ee$Image(0)
nc <- st_read(system.file("shape/nc.shp", package="sf")) %>% 
  st_bbox() %>% 
  st_as_sfc()
nc_grid <- st_make_grid(nc, n = 2)

plot(nc)
plot(nc_grid)

# Iterate in each grid
for (index in seq_along(nc_grid)) {
  ee_as_raster(
    my_img,
    region = sf_as_ee(nc_grid[index,])$geometry(),
    dsn = sprintf("raster_%02d.tif", index) # Output filename
    scale = 1000 # put your scale here
  )
}
```

**Comment by csaybar** [comment]
Closed after two months without a response
