### ISSUE TITLE
Listing the assets available for reading

### ISSUE THREAD

**Issue by vivirbr** [r-spatial/rgee#67]
Hi,
I never really managed to do this in python, but we are having some problems listing the assets that a specific account has granted access to as a reader.
Basically, we have a user with a lot of assets and scripts and we want more people to use these assets as readers, but unlike the scripts listed in the left panel, the assets available for reading are not listed anywhere.
Any suggestion to request a list of assets from the reader account?

**Comment by csaybar** [comment]
Hi @vivirbr, thanks for open this issue!.  You can use the `ee$data$setIamPolicy` to accomplish what you want. In rgee, the code below could help you:

```r
library(rgee)
ee_Initialize("csaybar@gmail.com") #put your email here (important)

# Create a data.frame with all your EE assets
ee_assets <- ee_manage_assetlist(path_asset = "users/csaybar/")

# Change the policy of each asset
for (index in seq_len(nrow(ee_assets))) {
  ee_manage_asset_access(
    path_asset = ee_assets$ID[1],
    editor = c("leslyab@gmail.com","aybar1994@gmail.com"), #put here all people will have editor privileges
    all_users_can_read = TRUE
  )
}
```
`ee_manage_asset_access` is a little buggy, I apologize, and if you do not define your email in ee_Initialize will not work. We will enhance it in the next release. Please, tell us if it solves your problem!.

**Comment by giswqs** [comment]
@vivirbr Have you tried `ee.data.listAssets()` in Python? 

https://developers.google.com/earth-engine/command_line#ls

![](https://i.imgur.com/xS0PLJ9.png)

**Comment by vivirbr** [comment]
Hi @csaybar, thanks for being super fast.
The code is returning the first level of my assets, but I am more interested in the ones that another account shared with me by setting my user as a reader. Maybe it is an argument or something like that, to expand the request to everything. Is it correct?

**Comment by giswqs** [comment]
See below. I can list assets belonged to other GEE account. 
![](https://i.imgur.com/RNPExVq.png)

**Comment by vivirbr** [comment]
is this assets public?
I tried the same in my account and it's working but when I try the other account I have a "not found" return

**Comment by giswqs** [comment]
Yes, those assets were set public.

**Comment by vivirbr** [comment]
Yep, I think it needs to be public to request the list from another account. The assets I want to list are not public, but I am a reader.

**Comment by csaybar** [comment]
I think this cannot be done. But it would be great if you could send your question to the gee developers group. https://groups.google.com/forum/#!forum/google-earthengine-announce.
