### ISSUE TITLE
Error: unexpected symbol in "docker pull"

### ISSUE THREAD

**Issue by xiaoxiaokuishu** [r-spatial/rgee#71]
when perform ' docker pull csaybar/rgee', below error appears
error: unexpected symbol in "docker pull"

**Comment by csaybar** [comment]
Hi @xiaoxiaokuishu  `docker pull csaybar/rgee` is not an R command but a system OS command. 
![image](https://user-images.githubusercontent.com/16768318/86530594-a36a5400-be7f-11ea-99e6-8f2288de446b.png)
