### ISSUE TITLE
how to get today date

### ISSUE THREAD

**Issue by jimoreira** [r-spatial/rgee#80]
hi, 
i'm trying to get the current date. 
Into gee python API i used to use 

```
import datetime
now = datetime.datetime.now()
endDate = ee.Date(now)
```
using rgee and reticulate i'm trying 

```
library(reticulate)

dt <- import("datetime")
today = dt$datetime$now() %>% ee$Date()
```
and having the following error

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  EEException: Invalid argument specified for ee.Date(): ['2020-07-20T20:03:03.620696064'] `

i have read some of the issues of the date formats, but still unable to use the current time within rgee script.
If anybody have an idea..

thanks

**Comment by csaybar** [comment]
Dates could cause some troubles. I highly recommend revising [consideration vignettes](https://r-spatial.github.io/rgee/articles/considerations.html). Also we have a example [here](https://github.com/r-spatial/rgee/blob/examples/rgee/04_dates.R).
```r
library(rgee)
ee_Initialize()

Sys.Date() %>% as.character() %>% ee$Date()
```

**Comment by jimoreira** [comment]
I use this
```
today = Sys.Date() %>% as.character() %>% ee$Date()

end = ee$Date$parse('yyyy-MM-dd',today)

dataset = ee$ImageCollection('MODIS/006/MOD11A1')$
  filter(ee$Filter$date(ini, end))


```
and when i'm trying to map

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  EEException: Date.parse, argument 'date': Invalid type.
Expected type: String.
Actual type: Date.
Actual value: 2020-07-20T00:00:00
`

**Comment by csaybar** [comment]
You can pass dates directly!

```
dataset <- ee$ImageCollection('MODIS/006/MOD11A1')$
  filterDate("2011-01-01", "2015-01-01")

dataset <- ee$ImageCollection('MODIS/006/MOD11A1')$
  filterDate(rdate_to_eedate("2011-01-01"), rdate_to_eedate("2015-01-01"))
```

**Comment by csaybar** [comment]
```r
library(rgee)
ee_Initialize()

today <- Sys.Date() %>% as.character()
yesterday <-  (Sys.Date() -1 )%>% as.character()

dataset <- ee$ImageCollection('MODIS/006/MOD11A1')$
  filterDate(yesterday, today)
Map$addLayer(dataset$first(),name = "modis")
```

**Comment by jimoreira** [comment]
great thanks
