### ISSUE TITLE
Sentinel mask2clouds filter translation to rgee - Bitwise Operators

### ISSUE THREAD

**Issue by jimoreira** [r-spatial/rgee#81]
### Description

I'm trying to perform a cloud filter over COPERNICUS/S2 imageCollection. It's the standard filter suggested on gee. I have used it both in Javascript code and python, but I can't use it within R language. 

### What I Did
```
maskS2clouds= function (image) {
  qa = image$select('QA60')
  # Bits 10 and 11 are clouds and cirrus, respectively.
  cloudBitMask(1 << 10)
  cirrusBitMask (1 << 11)
  #Both flags should be set to zero, indicating clear conditions.
  mask = qa$bitwiseAnd(cloudBitMask)$eq(0)$
    and(qa$bitwiseAnd(cirrusBitMask)$eq(0))
  #Return the masked and scaled data, without the QA bands.
  return(image$updateMask(mask)$divide(10000)$
    select("B.*")$
    copyProperties(image, ("system:time_start")))
  }

OLI = ee$ImageCollection("COPERNICUS/S2")$
  filterBounds(table)$
  map(maskS2clouds)$
  filterMetadata('CLOUDCOVER','less_than',10)$
  map(app)
```
`
Error: unexpected input in:
"  # Bits 10 and 11 are clouds and cirrus, respectively.
  cloudBitMask(1 <<"
`

The symbol used in python (and javascript) can't work within R. 

If you have any ideas to try..
thanks!

**Comment by csaybar** [comment]
We have an example [here](https://github.com/r-spatial/rgee/blob/examples/Algorithms/CloudMasking/sentinel-2.R)!

**Comment by jimoreira** [comment]
Sorry! I couldn't find it.
Thanks for your help!
