### ISSUE TITLE
'rgee_sessioninfo.txt' doesn't exist

### ISSUE THREAD

**Issue by BVR089** [r-spatial/rgee#83]
* rgee version: 1.0.0
* R version: 4.0.2
* Operating System: Win10 Pro

### Description

While working on downloading a raster I got an error regarding the file 'rgee_sessioninfo.txt', then I tried to get information about the address of the file and it doesn't exist, I checked the installation and made sure that ee_Initialize () and ee_check () worked, and I did not find the file 'rgee_sessioninfo.txt'. I am using RStudio Desktop 1.2.5033.
I would like to know more about the error, and if it is due to a bad installation. What I would like to get is a raster stack object to parse under common r libraries like "raster", "rgdal" ... thanks for any help.

### What I Did

```

> imge <- ee_as_raster(
   image = img$select("B4"),
   region = roi,
   via = "getInfo"
 )
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '~/.config/earthengine//rgee_sessioninfo.txt': No such file or directory

> imge <- ee_as_raster(
   image = img$select("B4"),
   region = roi,
   via = "drive"
 )
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '~/.config/earthengine//rgee_sessioninfo.txt': No such file or directory


> ee_get_earthengine_path()
Error in ee_get_earthengine_path() : 
  rgee_sessioninfo.txt does not exist, run rgee::ee_Initialize() to fixed.

> ee_Initialize(email = '#####@gmail.com', drive = TRUE)
Welcome to the Earth Engine client library for R!
-- rgee 1.0.0 --------------------------------------- earthengine-api 0.1.227 -- 
 √ email: #####@gmail.com 
 √ Google Drive credentials:  FOUND
 √ Initializing Google Earth Engine:  DONE!

> ee_check()
(*)  Python version
√ [Ok] .../AppData/Local/r-miniconda/envs/r-reticulate/python.exe v3.6
(*)  Python packages:
√ [Ok] numpy
√ [Ok] earthengine-api

> ee_path <- path.expand("~/.config/earthengine/credentials")
> file.exists(ee_path)
[1] TRUE
```
> ee_get_earthengine_path()
Error in ee_get_earthengine_path() : 
  rgee_sessioninfo.txt does not exist, run rgee::ee_Initialize() to fixed.

**Comment by csaybar** [comment]
Hi, @BVR089 thanks a lot to open this issue. It is an old bug that surprised me that continues in rgee v.1.0.0. The `rgee_sessioninfo.txt` is created after run ee_Initialize(). It helps to identify the credentials path. We save the 
`rgee_sessioninfo.txt` file in the path below:
```r
library(rgee)
oauth_func_path <- system.file("python/ee_utils.py", package = "rgee")
utils_py <- rgee:::ee_source_python(oauth_func_path)
ee_utils_py_to_r(utils_py$ee_path())
```

Can you confirm that `rgee_sessioninfo.txt` exists after run:

```r
devtools::install_github("r-spatial/rgee") #Please upgrade your rgee version 
library(rgee)
ee_Initialize()
```
You must get TRUE in both cases after run:

```r
ee_path <- path.expand("~/.config/earthengine/credentials")
# TRUE
ee_path <- path.expand("~/.config/earthengine/rgee_sessioninfo.txt")
# TRUE
```

**Comment by BVR089** [comment]
Thank you so much @csaybar , after trying it several times the error remained while executing the instructions, however I realized that it was my error since I had not configured the EE home repository yet; had already been discussed in the following issue: https://github.com/gee-community/gee_tools/issues/25
Now everything works correctly.

**Comment by csaybar** [comment]
@BVR089 in 'rgee' v1.0.2 we fix this bug.  Thanks for notified us!.

**Comment by fcastaldi** [comment]
Hi @csaybar, I am encountering the same issue using Rgee 1.1.7, only credentials file is created  without rgee_sessioninfo.txt after running ee_Initialize().
Therefore, using
`ee_get_earthengine_path()`
I got
Error in ee_get_earthengine_path() : 
  rgee_sessioninfo.txt does not exist, run rgee::ee_Initialize() to fixed

Thanks for any help
