### ISSUE TITLE
rgee on Google Colab: expose link for authentication

### ISSUE THREAD

**Issue by amsantac** [r-spatial/rgee#85]
Hi,

First of all, thanks and kudos for such a great package.

I'm trying to run rgee on Colab and I got stuck at ee_Initialize() where it asks for the Authentication code, see screenshot attached:

![fig1](https://user-images.githubusercontent.com/8917061/89111186-5e065b80-d418-11ea-8480-fe0e4c250f71.png)

As there is no link to click or pop-up as one gets when using the Python API, it is not possible to continue with the authentication process with rgee. 

Would it be possible for the link to be printed as when it is shown when using the Python API, as seen below:

![fig2](https://user-images.githubusercontent.com/8917061/89111178-521a9980-d418-11ea-917d-65d1be1cc896.png)

To reproduce the issue you can start an R Colab notebook: https://colab.research.google.com/notebook#create=true&language=r and then run the following lines:

```
system('sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable')
system('sudo apt-get update')
system('sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev')
install.packages('sf')
remotes::install_github("r-spatial/rgee")
reticulate::install_miniconda()
library(rgee)
ee_install()
ee_Initialize()
```

Note that I had to run reticulate::install_miniconda() before running ee_install(). For some reason that line inside ee_install() failed on Colab.

Thank you very much in advance,

Ali

* rgee version: rgee_1.0.2
* R version: R version 3.6.3 (2020-02-29)
* Operating System: Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

**Comment by csaybar** [comment]
Thanks, @amsantac for putting this on a discussion. At the beginning, I thought this will not be possible but after some tries, I made that it works :). Let me know if you have any problem.
https://colab.research.google.com/github/r-spatial/rgee/blob/examples/rgee_colab.ipynb

**Comment by amsantac** [comment]
Superb! Thank you very much. I just tried it and worked perfect. And thanks for adding the examples and extra functions. You guys rock!
