### ISSUE TITLE
ee_imagecollection_to_local  - geodesic : Error in cat("- region parameters\n", "WKT :", sf::st_as_text(sf_region))

### ISSUE THREAD

**Issue by cedlfc44** [r-spatial/rgee#87]
* rgee version: 
* R version: 4
* Operating System: windows

hi:
I am having this problem, I need to download MODIS data series for EVI 250m, I started researching with rgee and encountered some problems. this problems are are in the middle and at the bottom of the code.
1: : To make a quality mask, the bit values ​​in the examples for getQABits are generally "11" for MODIS and "110000000000000000" for Sentinel. Could you explain this to me, because I don't understand what these values ​​are and where can I get them?
2: when I go to download information using "ee_imagecollection_to_local" I get this:
------------------------------------- Downloading ImageCollection - via drive --- region parameters
 WKT      : POLYGON ((-64.60063 -21.24018, -64.60351 -21.23902, -64.60702 -21.23749, -64.60867 -21.23658, -64.61124 -21.2366, -64.61136 -21.23672, -64.61149 -21.23686, -64.6115 -21.23686, -64.61182 -21.23689, -64.61191 -21.23701, -64.61201 -21.23714, -64.61202 -21.23742, -64.61183 -21.2378, -64.61179 -21.23813, -64.6119 -21.23861, -64.61191 -21.23903, -64.61162 -21.23923, ...........................here i have many coordinates........................................................................................., -64.54438 -21.28957, -64.54604 -21.28246, -64.54736 -21.28164, -64.55532 -21.2812, -64.55955 -21.28309, -64.566 -21.28602, -64.58781 -21.28641, -64.58931 -21.28242, -64.58564 -21.25925, -64.5814 -21.24774, -64.58197 -21.24692, -64.58711 -21.23954, -64.59371 -21.24, -64.59696 -21.24028, -64.60063 -21.24018)) 
 CRS      : 4326 
 geodesic : Error in cat("- region parameters\n", "WKT      :", sf::st_as_text(sf_region),  : 
  el argumento 9 (type 'environment') no es soportado por 'cat'

3: As I commented above, I am trying to fix these errors and make a code to download a series of EVI time data, get a raster stack and trim this with my shape and then download the resulting tiff to my PC, can you guide me, or if you have an example to follow.
Thank you
```r
#############################################################
rm(list=ls(all=TRUE))

library(sp)
library(raster)
library(abind)
library(sf)
library(stars)
library(tmap)
library(rgee)
library(cptcity)## paletas de colores

ee_Initialize("cedlfc", drive = TRUE)

############################################################

ee_filename <- st_read("./shape/shape.shp")%>%
st_geometry()%>%             
sf_as_ee()

############################################################3

class(ee_filename)
##[1] "ee.geometry.Geometry"             "ee.computedobject.ComputedObject" "ee.encodable.Encodable"  [4] "python.builtin.object"    

#############################################################

print(ee_filename,type = "json")

ee_search_dataset() %>%
  ee_search_title("mod13") %>%
  ee_search_title("MOD13Q1") %>%
 # ee_search_title("250m") %>%
  ee_search_display()                 

m <- ee$ImageCollection("MODIS/006/MOD13Q1")

##########################################################

getQABits <- function(image, qa) {
  # Convert binary (character) to decimal (little endian)
  qa <- sum(2^(which(rev(unlist(strsplit(as.character(qa), "")) == 1))-1))
  # Return a mask band image, giving the qa value.
  image$bitwiseAnd(qa)$lt(1)
}

##########################################################

# Using getQABits we construct a single-argument function 'mod13A2_clean'
m_clean <- function(img) {
  evi_values <- img$select("EVI")
  evi_qa <- img$select("SummaryQA")
  quality_mask <- getQABits(evi_qa, "110000000000000")

## examples here: getQABits generally are  11 to MODIS and  110000000000000000 to Sentinel. Why?
  
  # Mask pixels with value zero.
  evi_values$updateMask(quality_mask)
}

#########################################################

ptm <- proc.time()   
m_filename <- m$
  filterBounds(ee_filename)$
  filter(ee$Filter$date('2010-01-01', '2017-01-31'))$
  map(m_clean)

############################################################

nimages <- m_filename$size()$getInfo()
ic_date <- ee_get_date_ic(m_filename)

tf<-proc.time() - ptm  

#########################################################

ptm2 <- proc.time()   
sf::m_ic_local <- ee_imagecollection_to_local(
  ic = m_filename,
  scale = 1,
  region = ee_filename,
  via = 'drive'
)
```
------------------------------------- Downloading ImageCollection - via drive --- region parameters
 WKT      : POLYGON ((-64.60063 -21.24018, -64.60351 -21.23902, -64.60702 -21.23749, -64.60867 -21.23658, -64.61124 -21.2366, -64.61136 -21.23672, -64.61149 -21.23686, -64.6115 -21.23686, -64.61182 -21.23689, -64.61191 -21.23701, -64.61201 -21.23714, -64.61202 -21.23742, -64.61183 -21.2378, -64.61179 -21.23813, -64.6119 -21.23861, -64.61191 -21.23903, -64.61162 -21.23923, ...........................here i have many coordinates........................................................................................., -64.54438 -21.28957, -64.54604 -21.28246, -64.54736 -21.28164, -64.55532 -21.2812, -64.55955 -21.28309, -64.566 -21.28602, -64.58781 -21.28641, -64.58931 -21.28242, -64.58564 -21.25925, -64.5814 -21.24774, -64.58197 -21.24692, -64.58711 -21.23954, -64.59371 -21.24, -64.59696 -21.24028, -64.60063 -21.24018)) 
 CRS      : 4326 
 geodesic : Error in cat("- region parameters\n", "WKT      :", sf::st_as_text(sf_region),  : 
  el argumento 9 (type 'environment') no es soportado por 'cat'

**Comment by csaybar** [comment]
Hi @cedlfc44 thanks for open this issue.

1) It is how I manage bits in QA bands other approaches closer to Earth Engine examples  [here](https://github.com/r-spatial/rgee/tree/examples/Algorithms).

2) Can you confirm that it was fixed in rgee v1.0.4?. Please upgrade and restart R  before continues.

```r
library(sp)
library(raster)
library(abind)
library(sf)
library(stars)
library(tmap)
library(rgee)
library(cptcity)## paletas de colores

ee_Initialize(drive = TRUE)

ee_filename <- st_read(system.file("shape/nc.shp", package="sf")) %>%
  st_geometry()%>%             
  sf_as_ee()

m <- ee$ImageCollection("MODIS/006/MOD13Q1")

getQABits <- function(image, qa) {
  # Convert binary (character) to decimal (little endian)
  qa <- sum(2^(which(rev(unlist(strsplit(as.character(qa), "")) == 1))-1))
  # Return a mask band image, giving the qa value.
  image$bitwiseAnd(qa)$lt(1)
}

# Using getQABits we construct a single-argument function 'mod13A2_clean'
m_clean <- function(img) {
  evi_values <- img$select("EVI")
  evi_qa <- img$select("SummaryQA")
  quality_mask <- getQABits(evi_qa, "110000000000000")
  
  ## examples here: getQABits generally are  11 to MODIS and  110000000000000000 to Sentinel. Why?
  
  # Mask pixels with value zero.
  evi_values$updateMask(quality_mask)
}

m_filename <- m$
  filterBounds(ee_filename)$
  filter(ee$Filter$date('2010-01-01', '2017-01-31'))$
  map(m_clean)

nimages <- m_filename$size()$getInfo()
ic_date <- ee_get_date_ic(m_filename)

m_ic_local <- ee_imagecollection_to_local(
  ic = m_filename,
  scale = 1000000,
  region = ee_filename$geometry()$bounds(),
  via = 'drive'
)
```

**Comment by cedlfc44** [comment]
This bug is fixed in rgee v1.0.4. 
thanks Cesar.

**Comment by dante136677** [comment]
Hola Cesar, déjame felicitarte por lo que lograste. ahora tengo problemas con descargar las imágenes me aparece este error

Downloading: E:/0.1-Proyectos/PLANTILLA R/R_GEE/precipitación y evapotrasnpiraciónET_MODIS2003.tifERROR in Earth Engine servers: Pixel type not supported: Type<Long>. Convert the image to a floating point type or a smaller integer type, for example, using ee.Image.toDouble().
Error in ee_monitoring(task = task, quiet = quiet) : 
  ee_monitoring was forced to stop before getting results

#este es el ultimo codigo que escribi.
ee_imagecollection_to_local (et_a, 
                            ee_roi$geometry(), 
                            dsn = "E:/0.1-Proyectos/PLANTILLA R/R_GEE/precipitación y evapotrasnpiración")

**Comment by csaybar** [comment]
hola @dante136677 el error que menciones es un problema de GEE y no de rgee, como menciona el error que nos muestras.

> ERROR in Earth Engine servers: Pixel type not supported: Type. Convert the image to a floating point type or a smaller integer type, for example, using ee.Image.toDouble().

Veo que estas usando `ee_imagecollection_to_local` por lo que et_a debe ser un `ee.ImageCollection`.
Trata de cambiar el tipo de datos de  cada imagen de tu collection a float o int, usando ee.Image.Collection.map.

**Comment by agonzest** [comment]
Hola Cesar, he seguido tus comentarios y me has ayudado bastante en lo que estoy haciendo, te agradezco. Ahora estoy teniendo el mismo problema de @dante136677 y no puedo descargar ee.ImageCollection porque aparece el siguiente mensaje:

ERROR in Earth Engine servers: Pixel type not supported: Type<Long>. Convert the image to a floating point type or a smaller integer type, for example, using ee.Image.toDouble().
Error in ee_monitoring(task = task, quiet = quiet) : 
  ee_monitoring was forced to stop before getting results

De qué forma puedo cambiar el tipo de imagen? o tienes un ejemplo en que pueda guiarme para solucionar el problema? Muchas gracias
