### ISSUE TITLE
Error in ee_Initialize() : reticulate refuse to connect with rgee

### ISSUE THREAD

**Issue by pjaguirreh** [r-spatial/rgee#91]
Hi!

I'm getting the following error when trying to execute the ee_Initialize() command: **Error in ee_Initialize() : reticulate refuse to connect with rgee.**

I followed the instructions from the [rgee site](https://r-spatial.github.io/rgee/) and when I run ee_check() I get the following message, I don't know if it's related:
> ee_check()
(*)  Python version
√ [Ok] C:/Users/pjagu/AppData/Local/r-miniconda/envs/rgee/python.exe v3.8
√ **[X] earthengine-api not installed**

Any guidance?
Thanks

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Chile.1252  LC_CTYPE=Spanish_Chile.1252    LC_MONETARY=Spanish_Chile.1252
[4] LC_NUMERIC=C                   LC_TIME=Spanish_Chile.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.16 rgee_1.0.4     

loaded via a namespace (and not attached):
 [1] compiler_4.0.2   magrittr_1.5     assertthat_0.2.1 Matrix_1.2-18    cli_2.0.2        tools_4.0.2     
 [7] glue_1.4.1       rstudioapi_0.11  rappdirs_0.3.1   Rcpp_1.0.5       crayon_1.3.4     fansi_0.4.1     
[13] grid_4.0.2       jsonlite_1.7.0   lattice_0.20-41

**Comment by LouiseLeroux** [comment]
Hi, 

I just found the solution! Apparently this come from an update of Conda version.  You have just to update your conda version with the following :`conda update -n base conda`. It works for me.

**Comment by csaybar** [comment]
Hi @pjaguirreh your conda env looks good. It seems the problem is that `ee_install` (for some reason) does not install the earthengine-api Python API. You can install it manually as follow:
```
rgee::ee_install_upgrade()
```
If it doesn't work try:

```
conda install --name rgee earthengine-api
```
If you persist presenting this problem please attached us your rgee env:

```
Sys.getenv("EARTHENGINE_PYTHON")
Sys.getenv("EARTHENGINE_ENV")
```

**Comment by pjaguirreh** [comment]
Tried both suggestions and didn't work (I'm attaching two related images).

Regarding your request:

> Sys.getenv("EARTHENGINE_PYTHON")
[1] "C:\\Users\\pjagu\\AppData\\Local\\r-miniconda\\envs\\rgee\\python.exe"
> Sys.getenv("EARTHENGINE_ENV")
[1] "rgee"



![image](https://user-images.githubusercontent.com/47273633/89958991-62e1c100-dc09-11ea-8e85-267ecaf86232.png)

![image](https://user-images.githubusercontent.com/47273633/89958971-5493a500-dc09-11ea-9d6f-66c2b25a1519.png)

**Comment by csaybar** [comment]
Please attached us the following information:

```r
library(rgee)
library(reticulate)
Sys.setenv(RETICULATE_PYTHON = earthengine_python)
reticulate::py_config()
```

**Comment by pjaguirreh** [comment]
![image](https://user-images.githubusercontent.com/47273633/89959500-8ce7b300-dc0a-11ea-9af7-3fe7e1ef7b42.png)

**Comment by csaybar** [comment]
Please, Can you run again? I updated the message

**Comment by pjaguirreh** [comment]
![image](https://user-images.githubusercontent.com/47273633/89959653-efd94a00-dc0a-11ea-9399-837dd6ad57be.png)



ps: Yes, I'm restarting R each time I try a new instruction

**Comment by ryali93** [comment]
Hi, I solved the problem terminating my R session. After terminated your R session, can you attached us again the following:
```r
library(rgee)
ee_check()
ee_Initialize()
reticulate::py_config()
```
![image](https://user-images.githubusercontent.com/20345946/89961711-38dbcf00-dc08-11ea-9913-351a7749d795.png)

**Comment by pjaguirreh** [comment]
Thank you all for the time. I did it and still the same problem

![image](https://user-images.githubusercontent.com/47273633/89962079-adffd200-dc11-11ea-93bf-67586f80aff9.png)

**Comment by csaybar** [comment]
Hi @pjaguirreh really strange, but for some reason, you have miniconda with Python36 and Python38.
https://github.com/r-spatial/rgee/issues/91#issuecomment-672367167
https://github.com/r-spatial/rgee/issues/91#issuecomment-672396792
Please can you share with us a traceback of your error?

```r
ee_Initialize()
traceback()
```
Do not forget to restart your R session.

**Comment by pjaguirreh** [comment]
![image](https://user-images.githubusercontent.com/47273633/90028809-21dcc180-dc88-11ea-9c38-278044f52268.png)

**Comment by csaybar** [comment]
Ok, it helps. Can you run the follows please, if you get an error please share with us the traceback()

```r
library(rgee)

earthengine_python <- Sys.getenv("EARTHENGINE_PYTHON", unset = NA)
print(earthengine_python)
Sys.setenv(RETICULATE_PYTHON = earthengine_python)
ee_current_version <- system.file("python/ee_utils.py", package = "rgee")
ee_utils <- rgee:::ee_source_python(ee_current_version)
print(ee_utils$ee$'__version__')
```

OBS: You need to restart R before to run rgee:::ee_source_python

**Comment by pjaguirreh** [comment]
Apparently that worked!

But if I start a new R session I have to run again the code you attach.

![image](https://user-images.githubusercontent.com/47273633/90070096-4e60ff80-dcc1-11ea-9cbd-ca79ebd058a9.png)

**Comment by pjaguirreh** [comment]
And I can't run it after I "do the check" because I get the following:

![image](https://user-images.githubusercontent.com/47273633/90070217-81a38e80-dcc1-11ea-9ef2-43a936c672e1.png)

But if I restart the session and run again the code you attach it works once again.

**Comment by pjaguirreh** [comment]
Apparently, if I just don't run "ee_check()" there's no problem with "ee_Initialize()". I was already able to run the examples in the rgee site.

> ee_Initialize()
-- rgee 1.0.4 --------------------------------------- earthengine-api 0.1.229 -- 
 √ email: not_defined
 √ Initializing Google Earth Engine:  DONE!
 √ Earth Engine user: users/gee_earth_engine 
--------------------------------------------------------------------------------

**Comment by csaybar** [comment]
HI @pjaguirreh, I really do not understand why you get refuse error. Does the code below work for you?

```r
earthengine_python <- Sys.getenv("EARTHENGINE_PYTHON", unset = NA)
print(earthengine_python)
Sys.setenv(RETICULATE_PYTHON = earthengine_python)
ee_current_version <- system.file("python/ee_utils.py", package = "rgee")
ee_utils <- try(rgee:::ee_source_python(ee_current_version), silent = TRUE)
con_reticulate_counter <- 0
while (any(class(ee_utils) %in% "try-error")) {
  ee_utils <- try(rgee:::ee_source_python(ee_current_version), 
                  silent = TRUE)
  con_reticulate_counter <- con_reticulate_counter + 1
  if (con_reticulate_counter == 4) {
    stop("reticulate refuse to connect with rgee")
  }
}
```

**Comment by pjaguirreh** [comment]
Apparently, if I just don't run "ee_check()" there's no problem with "ee_Initialize()". I was already able to run the examples in the rgee site.

ee_Initialize()
-- rgee 1.0.4 --------------------------------------- earthengine-api 0.1.229 --
√ email: not_defined
√ Initializing Google Earth Engine: DONE!
√ Earth Engine user: users/gee_earth_engine

**Comment by csaybar** [comment]
Thanks, happy to see `rgee` working, thanks to notifying us, we study in deeper the problem with ee_check().

**Comment by DANYPORRAS** [comment]
> ee_Initialize('DanielPorras')
Error in ee_connect_to_py(path = ee_current_version, n = 5) : 
  The current Python PATH: C:/Users/DANIEL/AppData/Local/r-miniconda/envs/rgee/python.exe
does not have the Python package "earthengine-api" installed. Are you restarted/terminated.
your R session after install miniconda or run ee_install()?
If no do it, please try again:
> ee_install(): To create and set a Python environment with all rgee dependencies.
> ee_install_set_pyenv(): To set a specific Python environment.

**Comment by h-a-graham** [comment]
Thanks to the suggestions above, the following solved the issue for me: 

```
earthengine_python <- Sys.getenv("EARTHENGINE_PYTHON", unset = NA)
Sys.setenv(RETICULATE_PYTHON = earthengine_python)
.rs.restartR()
```
