### ISSUE TITLE
Invalid GeoJSON geometry

### ISSUE THREAD

**Issue by malikarrahiem** [r-spatial/rgee#95]
Hey Cesar, this is really a great job! I like it a lot.

I face a problem which I dont know the solution. Can you help me?

Whenever I did ee_extract (this is tutorial from getting precipitation data from terraclimate), I keep getting this error:

**Error in py_call_impl(callable, dots$args, dots$keywords) :
EEException: Invalid GeoJSON geometry.

Detailed traceback:
File "C:\Program Files\R\R-4.0.0\library\rgee\python\sf_as_ee.py", line 17, in sfg_as_ee_py
return ee.Geometry(geo_json = eval(x),
File "C:\Users\Administrator\AppData\Local\r-miniconda\envs\rgee\lib\site-packages\ee\computedobject.py", line 32, in call
return type.call(cls, *args, kwargs)
File "C:\Users\Administrator\AppData\Local\r-miniconda\envs\rgee\lib\site-packages\ee\geometry.py", line 83, in init
raise ee_exception.EEException('Invalid GeoJSON geometry.')

I dont know how to solve this. Can you help me?

Thank you.

**Comment by csaybar** [comment]
Hi, @malikarrahiem thanks, do you refer to this [one](https://github.com/r-spatial/rgee/blob/examples/rgee/08_extract.R)? I do not get an error, could you attach the link please?
```r
library(tidyverse)
library(gganimate)
library(rgee)
library(sf)

ee_Initialize()
ee_user_info()

# Define a Image or ImageCollection: Terraclimate
terraclimate <- ee$ImageCollection("IDAHO_EPSCOR/TERRACLIMATE")$
  filterDate("2001-01-01", "2002-01-01")$
  map(function(x){
    date <- ee$Date(x$get("system:time_start"))$format('YYYY_MM_dd')
    name <- ee$String$cat("Terraclimate_pp_", date)
    x$select("pr")$reproject("EPSG:4326")$set("RGEE_NAME", name)
  })

# Define a geometry
nc <- st_read(
  dsn = system.file("shape/nc.shp", package = "sf"),
  stringsAsFactors = FALSE,
  quiet = TRUE
)

# Extract values
ee_nc_rain <- ee_extract(
  x = terraclimate,
  y = nc,
  scale = 250,
  fun = ee$Reducer$mean(),
  sf = FALSE
)
```

**Comment by malikarrahiem** [comment]
Hi Cesar, thanks for your response. I really appreciate it. 

Yes this one. So whenever I tried to change the shape to desired shape, the error is appear. 

This is what I do:

location <- "Sub-KHG-1"
sub_khg <- st_read("subkhg.shp", quiet = TRUE) %>% 
  st_transform(crs= "+proj=longlat +datum=WGS84") %>%
  filter(NAMA == location)

start <- "1981-01-01"
end <- "2020-01-01"

chirps <- ee$ImageCollection("UCSB-CHG/CHIRPS/DAILY")$
  filterDate(start, end)$
  map(function(x) x$reproject("EPSG:4326")$select("precipitation"))

rainfall_chirps <- ee_extract(x = chirps, 
                         y = sub_khg, 
                         fun=ee$Reducer$mean(), 
                         sf = FALSE)

the result is an error: 

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  EEException: Invalid GeoJSON geometry.

Detailed traceback: 
  File "C:\Program Files\R\R-4.0.0\library\rgee\python\sf_as_ee.py", line 17, in sfg_as_ee_py
    return ee.Geometry(geo_json = eval(x),
  File "C:\Users\Administrator\AppData\Local\r-miniconda\envs\rgee\lib\site-packages\ee\computedobject.py", line 32, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\r-miniconda\envs\rgee\lib\site-packages\ee\geometry.py", line 83, in __init__
    raise ee_exception.EEException('Invalid GeoJSON geometry.')

do you know what is wrong with my code?

Sorry if the question is not clear enough. This is the first time I ask a question in a forum. 

Thank you.

**Comment by csaybar** [comment]
Hi, @malikarrahiem no problem!. It seems that there is a problem with your geometry. Could you give me access to your shapefile by some means?, maybe Google Drive.

**Comment by malikarrahiem** [comment]
Oh dear, yes the shape is the problem. I check the coordinate system, somehow it is not recognized. I change it in QGIS and it works fine now. 

Thank you Cesar. I really appreciate your work!
